(function(){'use strict';
var esc=function(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})};
var safeUrl=function(v){try{var u=new URL(String(v||''),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch(_){return ''}};
var sourceDomain=function(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch(_){return ''}};
var cache={claims:null,events:null,assessment:null,status:null};
function ensure(){if(document.getElementById('gp-intelligence-center'))return document.getElementById('gp-intelligence-center');var map=document.getElementById('map');if(!map)return null;var host=map.closest('.panel')||map.parentElement;var p=document.createElement('section');p.id='gp-intelligence-center';p.className='panel';p.innerHTML='<div class="section-head"><div><h2>Global Pulse Intelligence Center</h2><div class="gp-ic-sub">Public-source intelligence with evidence, uncertainty and provenance visible.</div></div><div id="gp-ic-updated" class="muted"></div></div><div class="tools gp-ic-tabs"><button data-tab="pulse" class="filter active">Pulse</button><button data-tab="claims" class="filter">Investigate</button><button data-tab="watch" class="filter">Watchlist</button><button data-tab="health" class="filter">Data Health</button></div><div id="gp-ic-content"></div>';host.parentNode.insertBefore(p,host);p.querySelectorAll('[data-tab]').forEach(function(b){b.addEventListener('click',function(){p.querySelectorAll('[data-tab]').forEach(function(x){x.classList.remove('active')});b.classList.add('active');renderTab(b.dataset.tab)})});return p}
function card(title,body,cls){return '<article class="item '+(cls||'')+'"><strong>'+esc(title)+'</strong>'+body+'</article>'}
function confidenceBadge(c){var x=String(c||'LOW').toUpperCase();var cls=x==='HIGH'?'green':x==='MODERATE'?'blue':x==='DISPUTED'?'red':'amber';return '<span class="tag '+cls+'">'+esc(x)+'</span>'}
function normalizeClaims(){var cs=cache.claims&&Array.isArray(cache.claims.claims)?cache.claims.claims:[];return cs.map(function(c){var ev=Array.isArray(c.evidence)?c.evidence:[];var domains={};ev.forEach(function(e){var d=sourceDomain(e.url);if(d)domains[d]=1});return Object.assign({},c,{_domains:Object.keys(domains).length||Number(c.independentSourceDomains||0),_evidence:ev})})}
function renderPulse(){var el=document.getElementById('gp-ic-content');if(!el)return;var events=cache.events&&Array.isArray(cache.events.events)?cache.events.events:[];var claims=normalizeClaims();var recent=events.slice().sort(function(a,b){return String(b.lastSeen||b.firstSeen||'').localeCompare(String(a.lastSeen||a.firstSeen||''))}).slice(0,8);var hot=claims.filter(function(c){return String(c.confidence).toUpperCase()==='HIGH'||String(c.status).toUpperCase()==='DISPUTED'}).slice(0,5);var html='<div class="kpis"><div class="kpi"><strong>'+events.length+'</strong><span>Recent events</span></div><div class="kpi"><strong>'+claims.length+'</strong><span>Claim clusters</span></div><div class="kpi"><strong>'+hot.length+'</strong><span>Needs attention</span></div></div><div class="gp-ic-grid"><div><h2>What changed</h2><div class="items">'+(recent.length?recent.map(function(e){var rc=Number(e.reportCount||0);var sc=Number(e.sourceCount||0);if(!sc&&Array.isArray(e.reports)){var d={};e.reports.forEach(function(r){var q=sourceDomain(r.source||r.url);if(q)d[q]=1});sc=Object.keys(d).length}return card(e.title||'Untitled event','<div class="muted">'+esc(e.category||'general')+' · '+rc+' reports · '+sc+' source domains</div><div class="muted">'+esc(e.confidence||'developing')+'</div>')}).join(''):'<div class="empty">No recent events available.</div>')+'</div></div><div><h2>Evidence watch</h2><div class="items">'+(hot.length?hot.map(function(c){return card(c.claim||'Claim',confidenceBadge(c.confidence)+' <span class="tag">'+esc(c._domains)+' independent domains</span><div class="muted">'+esc(c.status||'developing')+'</div>')}).join(''):'<div class="empty">No high-priority evidence issues.</div>')+'</div></div></div>';el.innerHTML=html}
function renderClaims(){var el=document.getElementById('gp-ic-content');if(!el)return;var list=normalizeClaims().slice(0,20);el.innerHTML='<div class="muted gp-ic-note">A source count is not proof. Global Pulse distinguishes domains, preserves contradictions, and shows original evidence where available.</div><div class="items">'+(list.length?list.map(function(c){var ev=c._evidence;return '<article class="item gp-claim"><div>'+confidenceBadge(c.confidence)+' <span class="tag">'+esc(c.category||'general')+'</span> <span class="tag">'+esc(c._domains)+' independent domains</span></div><strong>'+esc(c.claim||'Unspecified claim')+'</strong><div class="muted">'+esc(c.status||'developing')+' · '+esc(c.sourceCount||ev.length)+' reports</div><details><summary>Evidence & contradictions</summary><div class="gp-claim-evidence">'+(ev.length?ev.map(function(e){var u=safeUrl(e.url);return '<div class="item"><b>'+esc(e.source||'Source')+'</b><br><span class="muted">'+esc(e.time||'Time unavailable')+'</span>'+(u?'<br><a href="'+esc(u)+'" target="_blank" rel="noopener noreferrer">Open original source</a>':'')+'</div>'}).join(''):'<div class="empty">No evidence records attached.</div>')+'</div></details></article>'}).join(''):'<div class="empty">No claim clusters are available yet. The service will populate this panel as public reports are processed.</div>')+'</div>'}
function getWatch(){try{var x=JSON.parse(localStorage.getItem('gp_watchlist')||'[]');return Array.isArray(x)?x.filter(function(v){return typeof v==='string'&&v.length<80}).slice(0,25):[]}catch(_){return []}}
function setWatch(a){try{localStorage.setItem('gp_watchlist',JSON.stringify(a.slice(0,25)))}catch(_){} }
function renderWatch(){var el=document.getElementById('gp-ic-content');if(!el)return;var w=getWatch();el.innerHTML='<div class="tools"><input id="gp-watch-input" maxlength="80" placeholder="Add country, topic, entity…"><button id="gp-watch-add">Add</button></div><div class="muted gp-ic-note">Watchlists stay in this browser only. They are not uploaded to Global Pulse.</div><div class="items">'+(w.length?w.map(function(x){return '<div class="item"><strong>'+esc(x)+'</strong><button data-remove="'+esc(x)+'" style="float:right;padding:5px 8px;min-height:28px">Remove</button></div>'}).join(''):'<div class="empty">Your local watchlist is empty.</div>')+'</div>';var input=document.getElementById('gp-watch-input');document.getElementById('gp-watch-add').onclick=function(){var v=(input.value||'').trim();if(!v)return;var a=getWatch();if(a.indexOf(v)===-1)a.push(v);setWatch(a);renderWatch()};el.querySelectorAll('[data-remove]').forEach(function(b){b.onclick=function(){setWatch(getWatch().filter(function(x){return x!==b.dataset.remove}));renderWatch()}})}
function renderHealth(){var el=document.getElementById('gp-ic-content');if(!el)return;var s=cache.status||{};var a=cache.assessment||{};var sourceCount=Number(s.sourceCount||s.sources||0);var ok=Number(s.onlineSources||s.healthySources||0);var updated=s.updatedAt||cache.events&&cache.events.updatedAt||cache.claims&&cache.claims.updatedAt||'';var stale='';if(updated){var age=Date.now()-Date.parse(updated);if(Number.isFinite(age)&&age>30*60*1000)stale='<span class="tag red">STALE</span>'}el.innerHTML='<div class="kpis"><div class="kpi"><strong>'+esc(ok||'—')+(sourceCount?'/'+esc(sourceCount):'')+'</strong><span>Healthy sources</span></div><div class="kpi"><strong>'+esc((a.assessments||a.items||[]).length||0)+'</strong><span>Assessments</span></div><div class="kpi"><strong>'+esc(updated?new Date(updated).toLocaleTimeString():'—')+'</strong><span>Latest data '+stale+'</span></div></div><div class="item"><strong>Trust controls</strong><div class="muted">Stale data is labeled; missing sources do not silently become confirmation; source links are opened without an opener; visitor watchlists remain local.</div></div>'}
function renderTab(tab){if(tab==='claims')renderClaims();else if(tab==='watch')renderWatch();else if(tab==='health')renderHealth();else renderPulse()}
function loadOne(path,key){return fetch(path+'?v='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error(r.status);return r.json()}).then(function(d){cache[key]=d}).catch(function(){})}
function load(){ensure();return Promise.all([loadOne('data/claims.json','claims'),loadOne('data/live_events.json','events'),loadOne('data/intelligence_assessment.json','assessment'),loadOne('data/live_status.json','status')]).then(function(){var p=ensure();if(p){document.getElementById('gp-ic-updated').textContent='Updated '+new Date().toLocaleTimeString();renderTab((p.querySelector('[data-tab].active')||{}).dataset?.tab||'pulse')}})}
function boot(){load();setInterval(load,60000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();
