/* Global Pulse — reliable embedded intelligence web. Uses the standalone renderer so the dashboard and graph do not compete over the same DOM/data lifecycle. */
(function(){
'use strict';
if(window.__GP_PRO_INTEL__)return;window.__GP_PRO_INTEL__=true;
function css(){if(document.getElementById('gp-pro-intel-css'))return;const s=document.createElement('style');s.id='gp-pro-intel-css';s.textContent=`#gp-intel-web.gp-pro{order:-100;padding:14px;overflow:hidden}.gp-pro .pro-head{display:flex;justify-content:space-between;align-items:end;gap:12px;margin-bottom:10px}.gp-pro .pro-k{font-size:9px;letter-spacing:.2em;color:#39ff88;font-weight:950}.gp-pro .pro-title{font-size:19px;font-weight:950;margin-top:2px}.gp-pro .pro-sub{font-size:10px;color:var(--muted);margin-top:4px}.gp-pro .pro-live{font-size:8px;color:#39ff88;white-space:nowrap}.gp-pro .pro-live:before{content:'';display:inline-block;width:6px;height:6px;border-radius:50%;background:#39ff88;box-shadow:0 0 10px #39ff88;margin-right:5px}.gp-pro .pro-frame{width:100%;height:720px;border:1px solid #193046;border-radius:13px;overflow:hidden;background:#03070b;display:block}.gp-pro .pro-foot{display:flex;justify-content:space-between;gap:8px;margin-top:8px;font-size:8px;color:var(--muted)}.gp-pro .pro-open{color:#62a0ff}.gp-pro .pro-error{padding:30px;text-align:center;color:#91a4b8;border:1px dashed #1b2b3d;border-radius:10px}.gp-pro .pro-error b{display:block;color:#ff6678;margin-bottom:5px}@media(max-width:700px){.gp-pro{padding:10px!important}.gp-pro .pro-head{display:block}.gp-pro .pro-live{margin-top:6px}.gp-pro .pro-frame{height:650px}}`;document.head.appendChild(s)}
function make(){let old=document.getElementById('gp-intel-web');if(old)old.remove();let wrap=document.querySelector('.wrap');if(!wrap)return null;css();let sec=document.createElement('section');sec.id='gp-intel-web';sec.className='panel wide gp-pro';sec.innerHTML=`<div class="pro-head"><div><div class="pro-k">GLOBAL PULSE / NETWORK INTELLIGENCE</div><div class="pro-title">INTELLIGENCE WEB</div><div class="pro-sub">Evidence-linked relationships across countries, politics, economics, energy, resources and military activity.</div></div><div class="pro-live">LIVE SNAPSHOT · 3D NETWORK</div></div><iframe class="pro-frame" title="Global Pulse 3D Intelligence Web" src="intelligence-web.html?embed=1&v=20260903" loading="eager" referrerpolicy="same-origin"></iframe><div class="pro-foot"><span>Drag nodes · rotate · zoom · click a node for deeper evidence</span><a class="pro-open" href="intelligence-web.html?v=20260903">OPEN FULL INTELLIGENCE WEB ↗</a></div>`;let cmd=document.getElementById('gp-command-center');if(cmd&&cmd.parentNode===wrap)wrap.insertBefore(sec,cmd.nextSibling);else{let top=document.getElementById('top');if(top&&top.parentNode===wrap)wrap.insertBefore(sec,top.nextSibling);else wrap.insertBefore(sec,wrap.firstElementChild)}return sec}
function start(){const sec=make();if(!sec)return;const frame=sec.querySelector('iframe');frame.addEventListener('load',()=>{try{const d=frame.contentDocument;const loading=d&&d.getElementById('loading');if(loading&&loading.textContent.includes('FAILED'))console.warn('Global Pulse embedded intelligence web: renderer reported failure')}catch(e){console.warn('Global Pulse embedded intelligence web:',e)}});frame.addEventListener('error',()=>{frame.outerHTML='<div class="pro-error"><b>INTELLIGENCE WEB COULD NOT LOAD</b>Refresh the page to retry the 3D renderer.</div>'})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else setTimeout(start,0);
})();
