/* Global Pulse V2.2 — trend, source health and escalation monitor. */
(function(){
  'use strict';
  const esc=v=>String(v==null?'':v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const n=v=>Number.isFinite(Number(v))?Number(v):0;
  const ago=v=>{const t=Date.parse(v||'');if(!Number.isFinite(t))return '';const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<1?'just now':m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
  function css(){if(document.getElementById('gp-v22-css'))return;const s=document.createElement('style');s.id='gp-v22-css';s.textContent='.gp-v22-grid{display:grid;grid-template-columns:1.5fr 1fr;gap:14px;margin-bottom:14px}.gp-v22-chart,.gp-v22-health{background:var(--panel2);border:1px solid var(--line);border-radius:11px;padding:11px}.gp-v22-chart svg{width:100%;height:170px;display:block}.gp-v22-axis{font-size:8px;fill:var(--muted)}.gp-v22-health-list{display:grid;gap:6px;max-height:210px;overflow:auto}.gp-v22-health-row{display:flex;justify-content:space-between;gap:8px;padding:7px 8px;border:1px solid var(--line);border-radius:7px;font-size:9px}.gp-v22-ok{color:var(--green)}.gp-v22-bad{color:var(--red)}.gp-v22-warn{color:var(--amber)}.gp-v22-escalation{margin-top:10px;padding:9px;border-left:2px solid var(--amber);background:#07111a;border-radius:7px;font-size:9px;color:var(--muted)}.gp-v22-escalation b{color:var(--text)}@media(max-width:720px){.gp-v22-grid{grid-template-columns:1fr}.gp-v22-chart svg{height:150px}}';document.head.appendChild(s)}
  async function loadHistory(){try{const r=await fetch('data/history.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}catch(e){return[]}}
  function trendSvg(points){const vals=points.map(x=>n(x.tension));const w=760,h=170,p=18;if(!vals.length)return '<div class="muted">Trend history unavailable.</div>';const min=Math.max(0,Math.min(...vals)-5),max=Math.min(100,Math.max(...vals)+5),range=Math.max(1,max-min);const xy=(v,i)=>[p+(i/Math.max(1,vals.length-1))*(w-p*2),h-p-((v-min)/range)*(h-p*2)];const pts=vals.map((v,i)=>xy(v,i).map(x=>x.toFixed(1)).join(',')).join(' ');const last=xy(vals[vals.length-1],vals.length-1);return '<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Global tension trend"><line x1="18" y1="152" x2="742" y2="152" stroke="#1b2b3d"/><line x1="18" y1="18" x2="18" y2="152" stroke="#1b2b3d"/><polyline points="'+pts+'" fill="none" stroke="#62a0ff" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/><circle cx="'+last[0].toFixed(1)+'" cy="'+last[1].toFixed(1)+'" r="4" fill="#ffc857"/><text x="24" y="30" class="gp-v22-axis">'+Math.round(max)+'</text><text x="24" y="148" class="gp-v22-axis">'+Math.round(min)+'</text><text x="680" y="30" class="gp-v22-axis">'+Math.round(vals[vals.length-1])+'</text></svg>'}
  function escalation(d,history){const p=history.slice(-8).map(x=>n(x.tension));const jump=p.length>1?p[p.length-1]-p[0]:0;const hot=(d.conflicts||[]).filter(c=>n(c.activityScore??c.score)>70).length;return jump>=5||hot>=5?`<div class="gp-v22-escalation"><b>Escalation watch:</b> reporting pressure is elevated across recent snapshots${jump>=5?' and the aggregate tension trend is rising':''}. '+hot+' conflict records currently exceed the high-activity threshold.</div>':`<div class="gp-v22-escalation"><b>Escalation watch:</b> no broad acceleration threshold triggered in the current snapshot.</div>`}
  function render(d,h){css();let p=document.getElementById('gp-v22-monitor');const wrap=document.querySelector('.wrap');if(!wrap)return;if(!p){p=document.createElement('section');p.id='gp-v22-monitor';p.className='panel wide';const anchor=document.getElementById('gp-early-warning')||document.getElementById('conflictSection');wrap.insertBefore(p,anchor||null)}const health=Array.isArray(d.sourceHealth)?d.sourceHealth:[];const ok=health.filter(x=>x.status==='ok').length;const recent=h.slice(-48);p.innerHTML='<div class="section-head"><div><h2>V2.2 · TREND &amp; SOURCE HEALTH</h2><div class="muted">Momentum, feed reliability and broad escalation signals from the public-data pipeline.</div></div><span class="gp-layer-count">'+ok+'/'+health.length+' sources healthy</span></div><div class="gp-v22-grid"><div class="gp-v22-chart"><div class="muted">GLOBAL TENSION · LAST 48 SNAPSHOTS</div>'+trendSvg(recent)+'</div><div class="gp-v22-health"><div class="muted" style="margin-bottom:7px">SOURCE HEALTH</div><div class="gp-v22-health-list">'+(health.length?health.map(x=>'<div class="gp-v22-health-row"><span>'+esc(x.name)+'</span><b class="'+(x.status==='ok'?'gp-v22-ok':'gp-v22-bad')+'">'+(x.status==='ok'?'ONLINE':'FAILED')+'</b></div>').join(''):'<div class="muted">Source health is unavailable.</div>')+'</div></div></div>'+escalation(d,h)+'<div class="muted" style="margin-top:7px;font-size:9px">Trend updated '+esc(ago(d.updatedAt)||'when the next snapshot arrives')+'. Source health reflects the latest collector run; a failed feed does not mean the underlying event is false.</div>'}
  async function boot(){const d=window.DATA;if(!d||document.getElementById('gp-v22-monitor'))return;const h=await loadHistory();render(d,Array.isArray(h)?h:[])}
  function start(){boot();document.addEventListener('globalpulse:dataready',boot);setInterval(boot,60000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
