/* Global Pulse — Active Conflicts / NOW tension display. */
(function(){"use strict";
var SELECTORS=["#active-conflicts","#activeConflicts","#active-conflict-list","#conflict-list","[data-section='active-conflicts']"];
function findRoot(){for(var i=0;i<SELECTORS.length;i++){var x=document.querySelector(SELECTORS[i]);if(x)return x}return null}
function num(v){var n=Number(v);return isFinite(n)?Math.max(0,Math.min(100,n)):null}
function scoreOf(x){return num(x.tension_score!=null?x.tension_score:x.tensionScore!=null?x.tensionScore:x.tension!=null?x.tension:x.intensity!=null?x.intensity:x.score)}
function level(s){return s==null?"UNAVAILABLE":s>=80?"CRITICAL":s>=60?"HIGH":s>=35?"ELEVATED":"LOW"}
function trend(x){var t=String(x.trend||x.direction||x.tensionTrend||"").toLowerCase();if(/rise|up|increas|escalat/.test(t))return "RISING";if(/fall|down|decreas|cool/.test(t))return "FALLING";return "STABLE"}
function render(root,data){if(!root||!Array.isArray(data))return;var old=root.querySelector(".gp-now-tension-list");if(old)old.remove();var wrap=document.createElement("div");wrap.className="gp-now-tension-list";data.slice(0,5).forEach(function(x){var s=scoreOf(x),row=document.createElement("div");row.className="gp-now-tension-row";var name=document.createElement("div");name.className="gp-now-tension-name";name.textContent=String(x.name||x.title||x.conflict||x.label||"Active conflict");row.appendChild(name);var value=document.createElement("strong");value.className="gp-now-tension-value";value.textContent=s==null?"—":Math.round(s)+"/100";row.appendChild(value);var meta=document.createElement("div");meta.className="gp-now-tension-meta";meta.textContent=level(s)+" · "+trend(x);row.appendChild(meta);var bar=document.createElement("div");bar.className="gp-now-tension-track";var fill=document.createElement("div");fill.className="gp-now-tension-fill";fill.style.width=(s==null?0:s)+"%";bar.appendChild(fill);row.appendChild(bar);wrap.appendChild(row)});if(data.length)root.appendChild(wrap)}
window.GlobalPulseTensionUI={render:render,scoreOf:scoreOf};
function boot(){var root=findRoot();if(!root)return;var c=[window.activeConflicts,window.active_conflicts,window.conflicts,window.GLOBAL_PULSE_DATA&&window.GLOBAL_PULSE_DATA.activeConflicts];for(var i=0;i<c.length;i++)if(Array.isArray(c[i])){render(root,c[i]);break}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();})();
