(function(){'use strict';
var DATA='data/snapshot.json',REG='data/regional_intelligence.json';
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function norm(s){return String(s||'').toLowerCase()}
function ageHours(v){var t=Date.parse(v||'');return isNaN(t)?999:Math.max(0,(Date.now()-t)/3600000)}
function sourceName(m){return m.source||m.sourceDomain||'Unknown source'}
function weight(m){var text=norm([m.title,m.category,m.type,m.description].join(' ')),w=1;['conflict','military','terrorism','attack','protest','political','crime','disaster'].forEach(function(k){if(text.indexOf(k)>=0)w=Math.max(w,{conflict:2.2,military:1.8,terrorism:2.2,attack:2.1,protest:1.2,political:.8,crime:1,disaster:1.1}[k])});var age=ageHours(m.observedAt||m.updatedAt||m.publishedAt);if(age<6)w*=1.35;else if(age<24)w*=1.15;else if(age>168)w*=.35;return w}
function confidence(markers){var sources={};markers.forEach(function(m){sources[sourceName(m)]=1});var n=Object.keys(sources).length;return n>=4?'HIGH':n>=2?'MEDIUM':'LOW'}
function regionOf(m){var c=norm(m.country||m.location),r=norm(m.region);if(r) return r;var map={Africa:/nigeria|sudan|somalia|ethiopia|kenya|congo|south sudan|mali|burkina|niger|chad|libya|egypt|algeria|morocco|ghana|uganda|tanzania|mozambique|south africa|angola|senegal|guinea|benin|togo|cameroon/, 'South America':/brazil|colombia|venezuela|ecuador|peru|bolivia|paraguay|uruguay|argentina|chile|guyana|suriname/, 'South Asia':/india|pakistan|bangladesh|afghanistan|sri lanka|nepal|bhutan|maldives|myanmar/, 'Middle East':/iran|iraq|israel|gaza|palestine|syria|lebanon|yemen|jordan|saudi|qatar|uae|hormuz|red sea/, Europe:/ukraine|russia|united kingdom|britain|france|germany|poland|belarus|baltic|europe|nato/, 'East Asia':/china|taiwan|japan|south korea|north korea/, 'Southeast Asia':/myanmar|thailand|vietnam|philippines|indonesia|malaysia/, 'North America':/canada|united states|america|mexico/};for(var k in map)if(map[k].test(c))return k;return 'Other'}
function ensure(){if(document.getElementById('gp-intel-panel'))return document.getElementById('gp-intel-panel');var map=document.getElementById('map');if(!map)return null;var host=map.closest('.panel')||map.parentElement,p=document.createElement('section');p.id='gp-intel-panel';p.className='panel';p.innerHTML='<div class="section-head"><div><h2>GLOBAL PULSE INTELLIGENCE</h2><div class="gp-intel-sub">Regional activity and source diversity from current public signals.</div></div><div id="gp-intel-updated" class="muted"></div></div><div id="gp-intel-kpis" class="gp-intel-kpis"></div><div id="gp-intel-regions" class="gp-intel-regions"></div><div id="gp-intel-sources" class="gp-intel-sources"></div>';host.parentNode.insertBefore(p,host);return p}
function render(d,rd){var p=ensure();if(!p)return;var markers=(d.markers||[]).filter(function(m){return m&&m.lat!=null&&m.lng!=null}),active=markers.filter(function(m){return ageHours(m.observedAt||m.updatedAt||m.publishedAt)<=24}),src={};markers.forEach(function(m){src[sourceName(m)]=(src[sourceName(m)]||0)+1});var sources=Object.keys(src).sort(function(a,b){return src[b]-src[a]}),score=Math.min(100,Math.round(markers.reduce(function(a,m){return a+weight(m)},0)/Math.max(1,markers.length)*18+Math.min(35,active.length*.25)));document.getElementById('gp-intel-updated').textContent='Updated '+new Date(rd?.updatedAt||d.updatedAt||Date.now()).toLocaleTimeString();document.getElementById('gp-intel-kpis').innerHTML='<div class="gp-intel-kpi"><strong>'+score+'</strong><span>Activity signal</span></div><div class="gp-intel-kpi"><strong>'+active.length+'</strong><span>Events &lt;24h</span></div><div class="gp-intel-kpi"><strong>'+sources.length+'</strong><span>Sources represented</span></div><div class="gp-intel-kpi"><strong>'+Object.keys(rd?.regions||{}).length+'</strong><span>Regions monitored</span></div><div class="gp-intel-kpi"><strong>'+confidence(markers)+'</strong><span>Source diversity</span></div>';var rs=rd?.regions||{},names=Object.keys(rs).filter(function(r){return r!=='Other'}).sort(function(a,b){return (rs[b].active24h||0)-(rs[a].active24h||0)});if(!names.length){rs={};markers.forEach(function(m){var r=regionOf(m);if(!rs[r])rs[r]={reports:0,active24h:0,conflictReports:0};rs[r].reports++;if(ageHours(m.observedAt||m.updatedAt||m.publishedAt)<=24)rs[r].active24h++;});names=Object.keys(rs).filter(function(r){return r!=='Other'}).sort(function(a,b){return rs[b].active24h-rs[a].active24h})}document.getElementById('gp-intel-regions').innerHTML='<div class="gp-intel-title">Regional activity</div>'+names.slice(0,9).map(function(r){var x=rs[r]||{};return '<div class="gp-intel-row"><b>'+esc(r)+'</b><div class="gp-intel-track"><i style="width:'+Math.min(100,Number(x.active24h||0)*12)+'%"></i></div><span>'+Number(x.active24h||0)+' active / '+Number(x.reports||0)+' reports · '+Number(x.conflictReports||0)+' conflict signals</span></div>'}).join('');document.getElementById('gp-intel-sources').innerHTML='<div class="gp-intel-title">Source mix</div>'+sources.slice(0,8).map(function(s){return '<span class="gp-intel-source">'+esc(s)+' <b>'+src[s]+'</b></span>'}).join('')}
function load(){Promise.all([fetch(DATA+'?v='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error(r.status);return r.json()}),fetch(REG+'?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{}}).catch(function(){return {}})]).then(function(x){render(x[0],x[1])}).catch(function(e){var p=ensure();if(p)p.querySelector('.gp-intel-sub').textContent='Intelligence panel unavailable: '+e.message})}
function boot(){load();setInterval(load,60000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();
