/* Global Pulse — V2.3 interactive conflict intelligence layer. */
(function(){
  'use strict';
  const esc=v=>String(v==null?'':v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const n=v=>Number.isFinite(Number(v))?Number(v):0;
  const cleanUrl=v=>{try{const u=new URL(String(v||'').trim(),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const articleUrl=a=>cleanUrl(a&&(a.url||a.original_link||a.source_url||a.link||a.sourceUrl||a.href));
  function applyCore(){
    const d=window.DATA||{};
    const score=n(d.tension??d.globalIndex??d.globalTension??d.score);
    const scoreEl=document.getElementById('globalScore');if(scoreEl)scoreEl.textContent=Math.round(score);
    const delta=document.getElementById('globalDelta');if(delta)delta.textContent=score>=70?'Elevated global pressure':score>=45?'Moderate global pressure':'Lower global pressure';
    const b=d.breakdownScores||d.breakdown||d.tensionBreakdown||d.drivers||{};
    const keys=[['Conflict activity','conflictActivity','conflict_activity'],['Diplomatic strain','diplomaticStrain','diplomatic_strain'],['Economic pressure','economicPressure','economic_pressure'],['Market volatility','marketVolatility','market_volatility'],['Military posture','militaryPosture','military_posture']];
    document.querySelectorAll('#breakdown .bar').forEach((row,i)=>{if(!keys[i])return;let v=0;for(const k of keys[i])if(b[k]!=null){v=n(b[k]);break}v=Math.max(0,Math.min(100,v));const fill=row.querySelector('.fill'),val=row.querySelector('b');if(fill)fill.style.width=v+'%';if(val)val.textContent=Math.round(v)});
    renderConflicts(d);
    const cc=document.getElementById('conflictCount');if(cc)cc.textContent=Array.isArray(d.conflicts)?d.conflicts.length:0;
    const sc=document.getElementById('storyCount');if(sc)sc.textContent=Array.isArray(d.stories)?d.stories.length:0;
    const mc=document.getElementById('markerCount');if(mc)mc.textContent=Array.isArray(d.markers)?d.markers.length:0;
    renderEarlyWarning(d);
    if(!document.getElementById('gp-list-more-css')){const s=document.createElement('style');s.id='gp-list-more-css';s.textContent='.gp-list-more{display:block;width:100%;margin:10px 0 2px;padding:10px;border:1px solid var(--line);border-radius:9px;background:var(--panel2);color:var(--text);font-weight:700;cursor:pointer}.gp-list-more:hover{filter:brightness(1.15)}.gp-conflict-card{cursor:pointer;transition:transform .15s ease,border-color .15s ease}.gp-conflict-card:hover{transform:translateY(-1px);border-color:rgba(98,160,255,.55)}.gp-conflict-card:focus{outline:2px solid #62a0ff;outline-offset:2px}.gp-conflict-modal{position:fixed;inset:0;z-index:1200;display:flex;align-items:center;justify-content:center;padding:16px;background:rgba(0,0,0,.76);backdrop-filter:blur(7px)}.gp-conflict-dialog{width:min(720px,100%);max-height:88vh;overflow:auto;background:#0b131d;color:var(--text);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 24px 80px rgba(0,0,0,.55)}.gp-conflict-close{float:right;width:34px;height:34px;border-radius:50%;font-size:19px}.gp-conflict-score{display:grid;grid-template-columns:110px 1fr;gap:14px;align-items:center;margin:12px 0 16px}.gp-conflict-number{font-size:42px;font-weight:900;line-height:1}.gp-conflict-track{height:12px;background:#142231;border-radius:999px;overflow:hidden}.gp-conflict-fill{height:100%;background:#ff6678;border-radius:999px}.gp-conflict-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.gp-conflict-meta>div{padding:9px;border:1px solid var(--line);border-radius:9px;background:var(--panel2)}.gp-conflict-meta span,.gp-conflict-meta strong{display:block}.gp-conflict-meta span{font-size:9px;color:var(--muted)}.gp-conflict-meta strong{margin-top:4px;font-size:11px}.gp-conflict-source{padding:11px 0;border-top:1px solid var(--line)}.gp-conflict-source strong{display:block;font-size:11px}.gp-conflict-source small{display:block;color:var(--muted);margin:4px 0 7px}.gp-conflict-open{display:inline-block;padding:7px 10px;border:1px solid rgba(98,160,255,.35);border-radius:8px;background:transparent;color:#62a0ff;font-weight:800;font-size:10px;cursor:pointer}.gp-conflict-method{font-size:9px;color:var(--muted);line-height:1.5;margin-top:12px}@media(max-width:620px){.gp-conflict-score{grid-template-columns:80px 1fr}.gp-conflict-number{font-size:34px}.gp-conflict-meta{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
  }
  function renderConflicts(d){
    const conflicts=Array.isArray(d.conflicts)?d.conflicts:[],stories=Array.isArray(d.stories)?d.stories:[],list=document.getElementById('conflictList');if(!list)return;
    const expanded=list.dataset.expanded==='true',visible=expanded?conflicts.slice(0,30):conflicts.slice(0,5);
    list.innerHTML=visible.map((c,i)=>{const s=Math.max(0,Math.min(100,n(c.activityScore??c.score??c.tension??c.priority)));const sev=String(c.escalation||c.severity||c.status||'MONITOR');return '<article class="ccard gp-conflict-card" tabindex="0" role="button" data-conflict-index="'+i+'"><span class="tag red">'+esc(sev)+'</span><h3>'+esc(c.name||c.title||c.conflict||('Conflict '+(i+1)))+'</h3><div class="muted">'+esc(c.region||c.location||'Global')+' · '+esc(c.confidence||'OPEN-DATA SIGNAL')+'</div><div class="scoreline"><span>Activity signal</span><b>'+Math.round(s)+'</b></div><div class="track"><div class="fill" style="width:'+s+'%"></div></div><div class="muted" style="margin-top:7px">'+esc(c.recent||'Tap for conflict intelligence and sources')+'</div></article>'}).join('');
    list.querySelectorAll('[data-conflict-index]').forEach(el=>{const act=()=>openConflict(visible[Number(el.dataset.conflictIndex)],stories);el.addEventListener('click',act);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();act()}})});
    if(conflicts.length>5){const btn=document.createElement('button');btn.className='gp-list-more';btn.type='button';btn.textContent=expanded?'Show Less ↑':'See More ('+conflicts.length+') ↓';btn.onclick=()=>{list.dataset.expanded=expanded?'false':'true';renderConflicts(d)};list.appendChild(btn)}
    if(!visible.length)list.innerHTML='<div class="empty">No active conflict records in the current snapshot.</div>';
  }
  function openExternal(url){const clean=cleanUrl(url);if(!clean)return false;const w=window.open(clean,'_blank','noopener,noreferrer');if(w){try{w.opener=null}catch{};return true}window.location.assign(clean);return true}
  function conflictSources(c,stories){
    const terms=String([c.name,c.title,c.conflict,c.id,c.region,c.location,...(c.keywords||[])].filter(Boolean).join(' ')).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>3);
    const stop=new Set(['conflict','regional','front','risk','civil','war','security','insurgency','insurgency','criminal','flashpoint','spillover','internal','residual','political','organized','crime']);
    const wanted=terms.filter(x=>!stop.has(x));
    return stories.map((a,i)=>{const text=String([a.title,a.summary,a.sourceLabel,a.sourceName,a.sourceType,a.tag].filter(Boolean).join(' ')).toLowerCase();let hits=0;wanted.forEach(t=>{if(text.includes(t))hits++});const conflictBoost=/war|conflict|military|attack|strike|missile|drone|ceasefire|troops|killed|fighting/.test(text)?2:0;return {a,rank:hits*3+conflictBoost-(i*.0001)}}).filter(x=>x.rank>0&&articleUrl(x.a)).sort((a,b)=>b.rank-a.rank).slice(0,4).map(x=>x.a);
  }
  function openConflict(c,stories){
    if(!c)return;
    const score=Math.max(0,Math.min(100,n(c.activityScore??c.score??c.tension??c.priority))),sources=conflictSources(c,stories),name=c.name||c.title||c.conflict||'Active conflict';
    const modal=document.createElement('div');modal.className='gp-conflict-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');
    const dialog=document.createElement('div');dialog.className='gp-conflict-dialog';
    const close=document.createElement('button');close.className='gp-conflict-close';close.type='button';close.textContent='×';close.setAttribute('aria-label','Close conflict intelligence');dialog.appendChild(close);
    const h=document.createElement('h2');h.textContent=name;dialog.appendChild(h);
    const sub=document.createElement('div');sub.className='muted';sub.textContent=(c.region||c.location||'Global')+' · '+String(c.escalation||c.severity||c.status||'MONITOR')+' · '+String(c.confidence||'OPEN-DATA SIGNAL');dialog.appendChild(sub);
    const scoreWrap=document.createElement('div');scoreWrap.className='gp-conflict-score';scoreWrap.innerHTML='<div><div class="gp-conflict-number">'+Math.round(score)+'</div><div class="muted" style="font-size:9px">ACTIVITY SCORE / 100</div></div><div><div class="gp-conflict-track"><div class="gp-conflict-fill" style="width:'+score+'%"></div></div><div class="muted" style="margin-top:7px">'+esc(c.recent||'Current reporting activity across monitored public sources.')+'</div></div>';dialog.appendChild(scoreWrap);
    const meta=document.createElement('div');meta.className='gp-conflict-meta';[['Type',c.type||c.category||'Conflict'],['Region',c.region||c.location||'Global'],['Signal',c.recent||'Active monitoring']].forEach(x=>{const d=document.createElement('div');d.innerHTML='<span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong>';meta.appendChild(d)});dialog.appendChild(meta);
    const sh=document.createElement('h3');sh.textContent='Supporting public sources';sh.style.marginTop='18px';dialog.appendChild(sh);
    if(!sources.length){const p=document.createElement('p');p.className='muted';p.textContent='No directly matching source links were found in this snapshot. The conflict remains an indexed monitoring record, not a claim that a new event occurred.';dialog.appendChild(p)}
    sources.forEach(a=>{const row=document.createElement('div');row.className='gp-conflict-source';const title=document.createElement('strong');title.textContent=a.title||'Untitled report';row.appendChild(title);const meta=document.createElement('small');meta.textContent=String(a.sourceLabel||a.sourceName||a.sourceType||'Public source')+(a.publishedDate||a.published_date||a.time?' · '+(a.publishedDate||a.published_date||a.time):'');row.appendChild(meta);const u=articleUrl(a);const btn=document.createElement('button');btn.type='button';btn.className='gp-conflict-open';btn.textContent='Read source report ↗';btn.onclick=e=>{e.preventDefault();e.stopPropagation();openExternal(u)};row.appendChild(btn);dialog.appendChild(row)});
    const method=document.createElement('div');method.className='gp-conflict-method';method.textContent='How this score works: Global Pulse uses the stored conflict record, recent public reporting signals, and deterministic activity scoring. A high score indicates stronger monitored activity; it does not mean the conflict is certain to escalate.';dialog.appendChild(method);
    modal.appendChild(dialog);document.body.appendChild(modal);const closeIt=()=>{modal.remove();document.removeEventListener('keydown',key)};const key=e=>{if(e.key==='Escape')closeIt()};close.onclick=closeIt;modal.addEventListener('click',e=>{if(e.target===modal)closeIt()});document.addEventListener('keydown',key);close.focus();
  }
  function renderEarlyWarning(d){
    let panel=document.getElementById('gp-early-warning'),wrap=document.querySelector('.wrap');if(!wrap)return;if(!panel){panel=document.createElement('section');panel.id='gp-early-warning';panel.className='panel wide';const anchor=document.getElementById('conflictSection')||document.getElementById('newsSection');wrap.insertBefore(panel,anchor||null)}
    const ew=d.earlyWarning||{},level=String(ew.level||'WATCH').toUpperCase(),direction=String(ew.direction||'stable').toLowerCase(),arrow=direction==='rising'?'↑':direction==='falling'?'↓':'→',cls=level==='HIGH'?'high':level==='ELEVATED'?'elevated':'watch';
    panel.innerHTML='<div class="section-head"><div><h2>EARLY WARNING</h2><div class="muted">Trend signal derived from recent Global Pulse snapshots — not a prediction.</div></div><div class="gp-ew-badge '+cls+'">'+esc(level)+'</div></div><div class="gp-ew-grid"><div><span class="muted">Current tension</span><strong>'+Math.round(n(ew.score||d.tension))+'</strong></div><div><span class="muted">Momentum</span><strong>'+arrow+' '+(n(ew.momentum)>0?'+':'')+n(ew.momentum).toFixed(1)+'</strong></div><div><span class="muted">Strongest driver</span><strong>'+esc(ew.strongestDriver||'—')+'</strong></div><div><span class="muted">Driver score</span><strong>'+Math.round(n(ew.strongestDriverScore))+'</strong></div></div><div class="muted gp-ew-method">'+esc(ew.method||'Waiting for trend history to accumulate.')+'</div>';
    if(!document.getElementById('gp-ew-css')){const s=document.createElement('style');s.id='gp-ew-css';s.textContent='#gp-early-warning{margin-bottom:12px}.gp-ew-badge{padding:6px 10px;border-radius:999px;font-size:10px;font-weight:900;letter-spacing:.08em}.gp-ew-badge.watch{background:rgba(98,160,255,.14);color:#62a0ff}.gp-ew-badge.elevated{background:rgba(255,200,87,.14);color:#ffc857}.gp-ew-badge.high{background:rgba(255,102,120,.14);color:#ff6678}.gp-ew-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.gp-ew-grid>div{border:1px solid var(--line);border-radius:10px;padding:10px;background:var(--panel2)}.gp-ew-grid span,.gp-ew-grid strong{display:block}.gp-ew-grid span{font-size:9px}.gp-ew-grid strong{margin-top:5px;font-size:15px}.gp-ew-method{margin-top:9px;font-size:9px}@media(max-width:620px){.gp-ew-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}';document.head.appendChild(s)}
  }
  function addStatus(){if(document.getElementById('gp-production-status'))return;const wrap=document.querySelector('.wrap');if(!wrap)return;const bar=document.createElement('div');bar.id='gp-production-status';bar.className='gp-statusbar';bar.innerHTML='<span class="gp-status-live"><i></i><strong>OPEN-DATA MONITOR</strong> <span>auto-checks every 60s</span></span><span>Dashboard initialized</span>';wrap.insertBefore(bar,wrap.firstElementChild)}
  function ready(){addStatus();applyCore()}
  document.addEventListener('globalpulse:dataready',applyCore);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else setTimeout(ready,0);
})();