/* Global Pulse V2.5 — climate-to-geopolitical linkage, hazard intelligence and risk pathways. */
(function(){
  'use strict';
  const esc=v=>String(v==null?'':v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const n=v=>Number.isFinite(Number(v))?Number(v):0;
  const clean=v=>{try{const u=new URL(String(v||'').trim(),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const articleUrl=a=>clean(a&&(a.url||a.original_link||a.source_url||a.link||a.sourceUrl||a.href));
  const COUNTRY_TERMS=['United States','China','Russia','Ukraine','Iran','Israel','Saudi Arabia','Turkey','India','Pakistan','Taiwan','North Korea','South Korea','Japan','United Kingdom','Mexico','Canada','Brazil','Venezuela','Colombia','Haiti','Sudan','Democratic Republic of Congo','Somalia','Nigeria','Yemen','Syria','Iraq','Lebanon','Egypt','Kenya','Uganda','Madagascar','Nepal','Myanmar','Philippines','Thailand','Indonesia','Algeria','Zambia','Mozambique'];
  const HAZARDS={
    'Drought / water':/drought|water shortage|water stress|water scarcity|reservoir|water supply/i,
    'Flood / storm':/flood|flooding|cyclone|hurricane|typhoon|storm surge|landslide/i,
    'Heat / fire':/heatwave|heat wave|extreme heat|wildfire|forest fire|bushfire/i,
    'Food insecurity':/famine|food insecurity|food crisis|acute hunger|crop failure|harvest failure|food shortage/i,
    'Health outbreak':/epidemic|outbreak|cholera|malaria|avian flu|pandemic|disease outbreak/i
  };
  function text(a){return String([a.title,a.summary,a.summary_snippet,a.tag,a.sourceLabel,a.sourceType,a.category,a.region,a.location].join(' '));}
  function scoreFor(d){return n((d.breakdownScores||{})['Climate & humanitarian pressure']);}
  function classify(t){for(const [k,rx] of Object.entries(HAZARDS))if(rx.test(t))return k;return 'Climate / humanitarian';}
  function countries(t){return COUNTRY_TERMS.filter(c=>new RegExp('\\b'+c.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','i').test(t));}
  function css(){if(document.getElementById('gp-v25-css'))return;const s=document.createElement('style');s.id='gp-v25-css';s.textContent='.gp-v25-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.gp-v25-card{background:var(--panel2);border:1px solid var(--line);border-radius:11px;padding:11px}.gp-v25-path{display:grid;grid-template-columns:110px 1fr auto;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid var(--line)}.gp-v25-path:last-child{border-bottom:0}.gp-v25-hazard{font-size:9px;font-weight:900;letter-spacing:.04em}.gp-v25-country{font-size:10px;font-weight:800;color:var(--text)}.gp-v25-evidence{font-size:9px;color:var(--muted);margin-top:3px}.gp-v25-score{font-size:11px;font-weight:900}.gp-v25-bar{height:6px;background:#142231;border-radius:99px;overflow:hidden;margin-top:5px}.gp-v25-fill{height:100%;background:linear-gradient(90deg,var(--green),var(--amber),var(--red))}.gp-v25-link{font-size:9px;color:var(--blue);font-weight:800}.gp-v25-note{font-size:9px;line-height:1.5;color:var(--muted);margin-top:9px}.gp-v25-badges{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.gp-v25-badge{padding:4px 7px;border-radius:999px;border:1px solid var(--line);font-size:9px;color:var(--muted)}.gp-v25-hot{color:var(--red);border-color:rgba(255,102,120,.3);background:rgba(255,102,120,.07)}@media(max-width:760px){.gp-v25-grid{grid-template-columns:1fr}.gp-v25-path{grid-template-columns:95px 1fr auto}}';document.head.appendChild(s)}
  function render(d){css();const wrap=document.querySelector('.wrap');if(!wrap)return;let sec=document.getElementById('gp-v25-pathways');if(!sec){sec=document.createElement('section');sec.id='gp-v25-pathways';sec.className='panel wide';const anchor=document.getElementById('gp-v24-climate')||document.getElementById('gp-v23-monitor')||document.getElementById('conflictSection');wrap.insertBefore(sec,anchor?anchor.nextSibling:null)}
    const stories=Array.isArray(d.stories)?d.stories:[];const conflicts=Array.isArray(d.conflicts)?d.conflicts:[];const score=scoreFor(d);
    const climate=stories.filter(a=>Object.values(HAZARDS).some(rx=>rx.test(text(a))));
    const links=[];const seen=new Set();
    climate.forEach(a=>{const t=text(a), hz=classify(t), cs=countries(t);cs.forEach(c=>{const key=hz+'|'+c;if(seen.has(key))return;seen.add(key);const related=conflicts.find(x=>{const ct=String([x.name,x.region,x.location,x.type,x.description].join(' '));return new RegExp(c.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i').test(ct)});const s=Math.max(15,Math.min(100,Math.round((n(related&&(related.activityScore??related.score??related.tension??related.priority))*0.55)+(Math.min(45,climate.filter(z=>countries(text(z)).includes(c)&&classify(text(z))===hz).length*9)))));links.push({c,hz,s,a,related})})});
    links.sort((a,b)=>b.s-a.s);const top=links.slice(0,12);const hazardCounts={};climate.forEach(a=>{const h=classify(text(a));hazardCounts[h]=(hazardCounts[h]||0)+1});
    const pathways=top.length?top.map(x=>'<div class="gp-v25-path"><div><div class="gp-v25-hazard">'+esc(x.hz)+'</div><div class="gp-v25-country">'+esc(x.c)+'</div></div><div><div class="gp-v25-bar"><div class="gp-v25-fill" style="width:'+x.s+'%"></div></div><div class="gp-v25-evidence">'+esc(x.a.title||'Public reporting')+'</div></div><div><div class="gp-v25-score">'+x.s+'</div>'+(articleUrl(x.a)?'<a class="gp-v25-link" href="'+esc(articleUrl(x.a))+'" target="_blank" rel="noopener noreferrer">Source ↗</a>':'')+'</div></div>').join(''):'<div class="muted">No country-linked climate pathways were found in the current snapshot.</div>';
    const badges=Object.entries(hazardCounts).sort((a,b)=>b[1]-a[1]).map(([k,v])=>'<span class="gp-v25-badge '+(v>=5?'gp-v25-hot':'')+'">'+esc(k)+' · '+v+'</span>').join('');
    sec.innerHTML='<div class="section-head"><div><h2>V2.5 · CLIMATE → GEOPOLITICAL PRESSURE</h2><div class="muted">Connects environmental and humanitarian signals to countries and conflict pressure when the same public evidence supports the linkage.</div></div><span class="gp-v23-badge '+(score>=70?'gp-v23-high':score>=45?'gp-v23-watch':'gp-v23-stable')+'">INDEX '+Math.round(score)+'</span></div><div class="gp-v25-grid"><div class="gp-v25-card"><div class="muted" style="margin-bottom:7px">RISK PATHWAYS</div>'+(pathways)+'</div><div class="gp-v25-card"><div class="muted">HAZARD SIGNAL MIX</div><div class="gp-v25-badges">'+(badges||'<span class="muted">No climate/humanitarian signals detected.</span>')+'</div><div style="margin-top:13px"><div class="muted">HOW TO READ THIS</div><div class="gp-v25-note">A pathway appears only when public reporting contains both a recognized hazard/humanitarian signal and a country reference. Where a matching conflict exists, its stored activity score contributes to the pathway strength. This is an evidence-linking aid, not proof that climate conditions caused a conflict.</div></div><div class="gp-v25-note">V2.5 is designed to surface compounding pressure: water stress → food pressure → displacement → political instability → conflict risk. Each arrow requires separate evidence; the dashboard does not assume causation.</div></div></div>';
  }
  function boot(){if(window.DATA)render(window.DATA)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);document.addEventListener('globalpulse:dataready',boot);setInterval(boot,60000);
})();
