/* Global Pulse — dashboard enhancements and compatibility bridge. */
(function(){
  'use strict';
  function loadCore(){
    if(window.__gpCoreLoader)return;
    window.__gpCoreLoader=true;
    if(document.querySelector('script[data-gp-core]'))return;
    const s=document.createElement('script');s.src='global_pulse_core.js?v=1';s.defer=true;s.dataset.gpCore='1';document.head.appendChild(s);
  }
  function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
  function n(v){return Number.isFinite(Number(v))?Number(v):0;}
  function articleUrl(a){try{const u=new URL(String(a&&(a.url||a.original_link||a.source_url||a.link||a.sourceUrl||a.href)||''),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}}
  function applyCore(){
    const d=window.DATA||{};
    const score=n(d.tension??d.globalIndex??d.globalTension??d.score),scoreEl=document.getElementById('globalScore');if(scoreEl)scoreEl.textContent=Math.round(score);
    const delta=document.getElementById('globalDelta');if(delta)delta.textContent=score>=70?'Elevated global pressure':score>=45?'Moderate global pressure':'Lower global pressure';
    document.querySelectorAll('#breakdown .bar').forEach((row,i)=>{const keys=[['conflictActivity','conflict_activity'],['diplomaticStrain','diplomatic_strain'],['economicPressure','economic_pressure'],['marketVolatility','market_volatility'],['militaryPosture','military_posture']][i];if(!keys)return;let v=0;for(const k of keys)if(d.breakdownScores?.[k]!=null){v=n(d.breakdownScores[k]);break}const fill=row.querySelector('.fill'),val=row.querySelector('b');if(fill)fill.style.width=Math.max(0,Math.min(100,v))+'%';if(val)val.textContent=Math.round(v)});
    renderConflicts(d);const cc=document.getElementById('conflictCount');if(cc)cc.textContent=Array.isArray(d.conflicts)?d.conflicts.length:0;const sc=document.getElementById('storyCount');if(sc)sc.textContent=Array.isArray(d.stories)?d.stories.length:0;const mc=document.getElementById('markerCount');if(mc)mc.textContent=Array.isArray(d.markers)?d.markers.length:0;
    loadCore();
  }
  function renderConflicts(d){
    const conflicts=Array.isArray(d.conflicts)?d.conflicts:[],list=document.getElementById('conflictList');if(!list)return;const expanded=list.dataset.expanded==='true',visible=expanded?conflicts.slice(0,30):conflicts.slice(0,5);
    list.innerHTML=visible.map((c,i)=>{const s=Math.max(0,Math.min(100,n(c.activityScore??c.score??c.tension??c.priority))),sev=String(c.escalation||c.severity||c.status||'MONITOR');return '<article class="ccard gp-conflict-card" tabindex="0" role="button" data-conflict-index="'+i+'"><span class="tag red">'+esc(sev)+'</span><h3>'+esc(c.name||c.title||c.conflict||('Conflict '+(i+1)))+'</h3><div class="muted">'+esc(c.region||c.location||'Global')+' · '+esc(c.confidence||'OPEN-DATA SIGNAL')+'</div><div class="scoreline"><span>Activity signal</span><b>'+Math.round(s)+'</b></div><div class="track"><div class="fill" style="width:'+s+'%"></div></div><div class="muted" style="margin-top:7px">'+esc(c.recent||'Tap for conflict intelligence and sources')+'</div></article>'}).join('');
    list.querySelectorAll('[data-conflict-index]').forEach(el=>{el.onclick=()=>openConflict(visible[Number(el.dataset.conflictIndex)],d);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openConflict(visible[Number(el.dataset.conflictIndex)],d)}}});
    if(conflicts.length>5){const b=document.createElement('button');b.className='gp-list-more';b.type='button';b.textContent=expanded?'Show Less ↑':'See More ('+conflicts.length+') ↓';b.onclick=()=>{list.dataset.expanded=expanded?'false':'true';renderConflicts(d)};list.appendChild(b)}
    if(!visible.length)list.innerHTML='<div class="empty">No active conflict records in the current snapshot.</div>';
  }
  function openConflict(c,d){if(!c)return;document.querySelectorAll('.gp-conflict-modal').forEach(x=>x.remove());const score=Math.max(0,Math.min(100,n(c.activityScore??c.score??c.tension??c.priority)));const words=String([c.name,c.title,c.region,c.location,c.id].filter(Boolean).join(' ')).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>3&&!/^(the|and|for|with|from|war|conflict|risk|front|security|regional|civil|internal|armed|groups|pressure|spillover|political|residual|instability|insurgency|criminal|flashpoint|militia)$/.test(x));const stories=Array.isArray(d.stories)?d.stories:[],sources=stories.map(s=>{const text=String([s.title,s.summary,s.sourceLabel,s.sourceType,s.source].filter(Boolean).join(' ')).toLowerCase();const hits=words.filter(w=>text.includes(w)).length;return{s,hits,url:articleUrl(s)}}).filter(x=>x.hits&&x.url).sort((a,b)=>b.hits-a.hits).slice(0,4);
    const modal=document.createElement('div');modal.className='gp-conflict-modal';const box=document.createElement('div');box.className='gp-conflict-dialog';const close=document.createElement('button');close.className='gp-conflict-close';close.type='button';close.textContent='×';box.appendChild(close);const h=document.createElement('h2');h.textContent=c.name||c.title||c.conflict||'Active Conflict';box.appendChild(h);const sub=document.createElement('div');sub.className='muted';sub.textContent=(c.region||c.location||'Global')+' · '+String(c.confidence||'OPEN-DATA SIGNAL');box.appendChild(sub);const track=document.createElement('div');track.className='gp-conflict-track';track.innerHTML='<i style="width:'+score+'%"></i>';box.appendChild(track);const sh=document.createElement('h3');sh.textContent='Supporting public sources';box.appendChild(sh);if(!sources.length){const p=document.createElement('p');p.className='muted';p.textContent='No directly matched source links were found in this snapshot.';box.appendChild(p)}sources.forEach(x=>{const r=document.createElement('div');r.className='gp-conflict-source';r.innerHTML='<strong>'+esc(x.s.title||'Public report')+'</strong><small>'+esc(x.s.sourceLabel||x.s.source||'Public source')+'</small><a href="'+esc(x.url)+'" target="_blank" rel="noopener noreferrer">Read source report ↗</a>';box.appendChild(r)});modal.appendChild(box);document.body.appendChild(modal);const done=()=>modal.remove();close.onclick=done;modal.onclick=e=>{if(e.target===modal)done()};}
  function boot(){applyCore()}
  document.addEventListener('globalpulse:dataready',boot);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();
