/* Global Pulse V2.7 — live intelligence quality, markets, evidence and map hygiene. */
(function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const arr=v=>Array.isArray(v)?v:[];
  const url=v=>{try{const u=new URL(String(v||''),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const ageText=iso=>{const t=Date.parse(iso||'');if(!Number.isFinite(t))return 'time unavailable';const m=Math.max(0,Math.round((Date.now()-t)/60000));if(m<2)return 'just now';if(m<60)return m+'m ago';const h=Math.round(m/60);if(h<24)return h+'h ago';return Math.round(h/24)+'d ago'};
  const sign=v=>Number(v)>0?'▲':Number(v)<0?'▼':'—';
  const fmt=(v,d)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
  const css=()=>{if(document.getElementById('gp-v27-css'))return;const s=document.createElement('style');s.id='gp-v27-css';s.textContent=`
.gp-v27-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.gp-v27-card{background:var(--panel2);border:1px solid var(--line);border-radius:12px;padding:12px}.gp-v27-market{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.gp-v27-quote{padding:10px;border:1px solid var(--line);border-radius:10px;background:#07111b}.gp-v27-quote-top{display:flex;justify-content:space-between;gap:7px;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.05em}.gp-v27-quote-value{font-size:19px;font-weight:900;margin-top:4px;font-variant-numeric:tabular-nums}.gp-v27-change{font-size:9px;margin-top:3px}.gp-v27-up{color:var(--green)}.gp-v27-down{color:var(--red)}.gp-v27-flat{color:var(--muted)}.gp-v27-stale{color:var(--amber)}.gp-v27-health{display:grid;gap:9px}.gp-v27-health-row{display:grid;grid-template-columns:9px 1fr auto;gap:8px;align-items:center}.gp-v27-dot{width:8px;height:8px;border-radius:50%;background:var(--muted)}.gp-v27-dot.live{background:var(--green);box-shadow:0 0 0 3px rgba(72,223,131,.1)}.gp-v27-dot.stale{background:var(--amber)}.gp-v27-dot.failed{background:var(--red)}.gp-v27-health-row b{font-size:11px}.gp-v27-health-row span{font-size:9px;color:var(--muted)}.gp-v27-health-num{font-weight:900;font-size:12px}.gp-v27-headline{display:grid;gap:7px}.gp-v27-headline a{display:block;color:var(--text);font-size:12px;font-weight:800;line-height:1.35}.gp-v27-headline a:hover{color:var(--blue)}.gp-v27-meta{font-size:9px;color:var(--muted)}.gp-v27-badges{display:flex;gap:6px;flex-wrap:wrap}.gp-v27-badge{padding:4px 7px;border:1px solid var(--line);border-radius:999px;font-size:9px;color:var(--muted)}.gp-v27-note{margin-top:8px;color:var(--muted);font-size:9px;line-height:1.5}.gp-v27-two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.gp-v27-conflict{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;padding:8px 0;border-bottom:1px solid var(--line)}.gp-v27-conflict:last-child{border-bottom:0}.gp-v27-conflict b{font-size:11px}.gp-v27-conflict span{display:block;color:var(--muted);font-size:9px;margin-top:2px}.gp-v27-score{font-weight:900;font-size:13px;color:var(--amber)}@media(max-width:760px){.gp-v27-grid,.gp-v27-two{grid-template-columns:1fr}.gp-v27-market{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s)};
  function dedupeMarkers(d){
    const markers=arr(d&&d.markers), seen=new Set(), out=[];
    markers.forEach(m=>{const source=String(m&&m.source||'');let key;if(/usgs/i.test(source)||/earthquake/i.test(String(m&&m.eventType||m&&m.type||''))){key='quake|'+String(m.url||m.id||m.eventId||[m.title,m.lat??m.latitude,m.lng??m.lon].join('|'))}else{key=String(m.id||m.url||[m.source,m.title,m.lat??m.latitude,m.lng??m.lon].join('|'))}if(seen.has(key))return;seen.add(key);out.push(m)});return out;
  }
  function marketCards(m){return arr(m&&m.indicators).map(q=>{const p=Number(q.price), ch=Number(q.change), pct=Number(q.changePercent), cls=ch>0?'gp-v27-up':ch<0?'gp-v27-down':'gp-v27-flat';const checked=ageText(q.checkedAt);const marketAge=ageText(q.marketTime);const status=q.status==='stale'?'STALE':q.status==='live'?'LIVE':'CLOSED';return `<div class="gp-v27-quote"><div class="gp-v27-quote-top"><span>${esc(q.name)}</span><span class="${q.status==='stale'?'gp-v27-stale':''}">${status}</span></div><div class="gp-v27-quote-value">${fmt(p,Number(q.decimals)||2)}${q.unit==='%'?'%':''}</div><div class="gp-v27-change ${cls}">${sign(ch)} ${fmt(Math.abs(ch),Number(q.decimals)||2)} · ${pct>=0?'+':''}${fmt(pct,2)}%</div><div class="gp-v27-meta">${esc(q.symbol)} · checked ${checked}${q.status==='closed'?' · close '+marketAge:''}</div></div>`}).join('');}
  function render(d){
    if(!d)return;css();
    const wrap=document.querySelector('.wrap');if(!wrap)return;
    const markers=dedupeMarkers(d);
    const originalMarkers=d.markers;d.markers=markers;
    try{if(typeof window.renderMap==='function')window.renderMap();}finally{d.markers=originalMarkers}
    let sec=document.getElementById('gp-v27-intel');if(!sec){sec=document.createElement('section');sec.id='gp-v27-intel';sec.className='panel wide';const anchor=document.getElementById('top')||document.querySelector('.grid');if(anchor&&anchor.parentNode)anchor.parentNode.insertBefore(sec,anchor.nextSibling);else wrap.insertBefore(sec,wrap.firstChild)}
    const md=d.marketData||{}, inds=arr(md.indicators), live=inds.filter(x=>x.status==='live').length, stale=inds.filter(x=>x.status==='stale').length;
    const sh=arr(d.sourceHealth), online=sh.filter(x=>x.status==='online'||x.status==='ok').length, degraded=sh.filter(x=>x.status==='degraded'||x.status==='stale').length, failed=sh.filter(x=>x.status==='failed'||x.status==='error').length;
    const stories=arr(d.stories).slice().sort((a,b)=>(Date.parse(b.time||b.published_date||'')||0)-(Date.parse(a.time||a.published_date||'')||0));
    const hot=stories.filter(s=>s.breaking||/breaking|strike|attack|war|missile|ceasefire|tariff|oil|sanction/i.test(String(s.title||''))).slice(0,5);
    const drivers=Object.entries(d.breakdownScores||{}).sort((a,b)=>b[1]-a[1]).slice(0,6);
    sec.innerHTML=`<div class="section-head"><div><h2>V2.7 · LIVE INTELLIGENCE CORE</h2><div class="muted">Evidence-first monitoring across markets, conflicts, politics and public reporting. No API key is required for the dashboard's market collector.</div></div><div class="gp-v27-badges"><span class="gp-v27-badge">DATA ${ageText(d.updatedAt)}</span><span class="gp-v27-badge">${live}/${inds.length||0} MARKETS LIVE</span></div></div>
      <div class="gp-v27-grid"><div class="gp-v27-card"><div class="muted" style="margin-bottom:8px">MARKET PRESSURE</div><div class="gp-v27-market">${marketCards(md)||'<div class="muted">Market collector has not returned a usable quote yet. The dashboard will retain the last good value rather than inventing one.</div>'}</div><div class="gp-v27-note">Quotes are server-collected every five minutes. “Checked” is when Global Pulse fetched the quote; “close” is when the exchange's last official market value occurred. Crypto is treated as live 24/7.</div></div>
      <div class="gp-v27-card"><div class="muted" style="margin-bottom:8px">SOURCE HEALTH</div><div class="gp-v27-health"><div class="gp-v27-health-row"><i class="gp-v27-dot live"></i><b>Online</b><strong class="gp-v27-health-num">${online}</strong></div><div class="gp-v27-health-row"><i class="gp-v27-dot stale"></i><b>Degraded</b><strong class="gp-v27-health-num">${degraded}</strong></div><div class="gp-v27-health-row"><i class="gp-v27-dot failed"></i><b>Failed</b><strong class="gp-v27-health-num">${failed}</strong></div></div><div class="gp-v27-note">Health reflects the latest collector result and usable current articles. Failed sources do not become fake “live” data.</div></div></div>
      <div class="gp-v27-two" style="margin-top:12px"><div class="gp-v27-card"><div class="muted" style="margin-bottom:8px">TOP CURRENT SIGNALS</div><div class="gp-v27-headline">${(hot.length?hot:stories.slice(0,5)).map(s=>`<div><a href="${esc(url(s.url||s.source))}" target="_blank" rel="noopener noreferrer">${esc(s.title||'Public report')}</a><div class="gp-v27-meta">${esc(s.sourceLabel||s.sourceType||'Public source')} · ${ageText(s.time||s.published_date)}</div></div>`).join('')||'<div class="muted">No current headlines available.</div>'}</div></div>
      <div class="gp-v27-card"><div class="muted" style="margin-bottom:8px">PRESSURE DRIVERS</div><div>${drivers.map(([k,v])=>`<div class="gp-v27-conflict"><div><b>${esc(k)}</b><span>${esc((d.driverSignals&&d.driverSignals[k]&&d.driverSignals[k].matches)||0)} matching signals · ${esc((d.driverSignals&&d.driverSignals[k]&&d.driverSignals[k].sources)||0)} source domains</span></div><strong class="gp-v27-score">${Math.round(Number(v)||0)}</strong></div>`).join('')}</div></div></div>`;
    let stamp=document.getElementById('gp-v27-stamp');if(!stamp){stamp=document.createElement('div');stamp.id='gp-v27-stamp';stamp.className='gp-v27-note';sec.appendChild(stamp)}stamp.textContent='V2.7 refresh layer · snapshot checked '+ageText(d.updatedAt)+' · '+stale+' stale market values · '+markers.length+' unique map signals.';
  }
  function boot(){if(window.DATA)render(window.DATA)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
  window.addEventListener('globalpulse:dataready',boot);setInterval(boot,30000);
})();
