/* Global Pulse V2.3 — conflict escalation, event timeline and regional intelligence. */
(function(){
  'use strict';
  const esc=v=>String(v==null?'':v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const n=v=>Number.isFinite(Number(v))?Number(v):0;
  const url=v=>{try{const u=new URL(String(v||'').trim(),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
  const articleUrl=a=>url(a&&(a.url||a.original_link||a.source_url||a.link||a.sourceUrl||a.href));
  const ago=v=>{const t=Date.parse(v||'');if(!Number.isFinite(t))return'';const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<1?'just now':m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
  function css(){if(document.getElementById('gp-v23-css'))return;const s=document.createElement('style');s.id='gp-v23-css';s.textContent='.gp-v23-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:12px}.gp-v23-panel{background:var(--panel2);border:1px solid var(--line);border-radius:11px;padding:11px}.gp-v23-list{display:grid;gap:7px;max-height:300px;overflow:auto}.gp-v23-event{padding:9px;border:1px solid var(--line);border-radius:8px}.gp-v23-event b{font-size:10px}.gp-v23-event small{display:block;color:var(--muted);margin-top:3px}.gp-v23-region{display:grid;grid-template-columns:1fr auto;gap:7px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.gp-v23-region:last-child{border-bottom:0}.gp-v23-bar{height:7px;background:#142231;border-radius:99px;overflow:hidden;margin-top:5px}.gp-v23-fill{height:100%;background:#ff6678}.gp-v23-badge{font-size:9px;font-weight:900;padding:4px 7px;border-radius:99px}.gp-v23-high{color:#ff6678;background:rgba(255,102,120,.12)}.gp-v23-watch{color:#ffc857;background:rgba(255,200,87,.12)}.gp-v23-stable{color:#62a0ff;background:rgba(98,160,255,.12)}.gp-v23-note{font-size:9px;color:var(--muted);margin-top:9px;line-height:1.5}@media(max-width:720px){.gp-v23-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
  function render(d){css();const wrap=document.querySelector('.wrap');if(!wrap)return;let sec=document.getElementById('gp-v23-monitor');if(!sec){sec=document.createElement('section');sec.id='gp-v23-monitor';sec.className='panel wide';const anchor=document.getElementById('gp-v22-monitor')||document.getElementById('gp-early-warning')||document.getElementById('conflictSection');wrap.insertBefore(sec,anchor||null)}
    const stories=Array.isArray(d.stories)?d.stories:[], conflicts=Array.isArray(d.conflicts)?d.conflicts:[];
    const events=stories.filter(a=>articleUrl(a)).sort((a,b)=>Date.parse(b.publishedDate||b.published_date||b.time||0)-Date.parse(a.publishedDate||a.published_date||a.time||0)).slice(0,12);
    const regions={};conflicts.forEach(c=>{const r=c.region||c.location||'Global';regions[r]=Math.max(regions[r]||0,n(c.activityScore??c.score??c.tension??c.priority))});
    const rs=Object.entries(regions).sort((a,b)=>b[1]-a[1]).slice(0,8);
    const ew=d.earlyWarning||{};const level=String(ew.level||'WATCH').toUpperCase();
    sec.innerHTML='<div class="section-head"><div><h2>V2.3 · CONFLICT ESCALATION &amp; EVENT TIMELINE</h2><div class="muted">A compact view of recent reporting pressure and the regions carrying the strongest conflict signals.</div></div><span class="gp-v23-badge '+(level==='HIGH'?'gp-v23-high':level==='ELEVATED'?'gp-v23-watch':'gp-v23-stable')+'">'+esc(level)+'</span></div><div class="gp-v23-grid"><div class="gp-v23-panel"><div class="muted" style="margin-bottom:8px">LATEST EVENT TIMELINE</div><div class="gp-v23-list">'+(events.length?events.map(a=>'<div class="gp-v23-event"><b>'+esc(a.title||'Untitled report')+'</b><small>'+esc(a.sourceLabel||a.sourceName||a.sourceType||'Public source')+' · '+esc(ago(a.publishedDate||a.published_date||a.time))+'</small></div>').join(''):'<div class="muted">No linked events in this snapshot.</div>')+'</div></div><div class="gp-v23-panel"><div class="muted" style="margin-bottom:8px">REGIONAL PRESSURE</div>'+(rs.length?rs.map(x=>'<div class="gp-v23-region"><div><b style="font-size:10px">'+esc(x[0])+'</b><div class="gp-v23-bar"><div class="gp-v23-fill" style="width:'+Math.max(0,Math.min(100,x[1]))+'%"></div></div></div><strong>'+Math.round(x[1])+'</strong></div>').join(''):'<div class="muted">Regional conflict scores unavailable.</div>')+'</div></div><div class="gp-v23-note">Escalation is a monitoring signal based on current stored scores, recent reporting volume and trend indicators. It is not a forecast and does not establish that a conflict will escalate.</div>';
  }
  function boot(){const d=window.DATA;if(d)render(d)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();document.addEventListener('globalpulse:dataready',boot);setInterval(boot,60000);
})();