/* Global Pulse — cross-domain Intelligence Brain + main-page market surface. */
(function(){
  'use strict';
  if(window.__GP_BRAIN_UI__)return;
  window.__GP_BRAIN_UI__=true;
  var esc=function(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]||m;});};
  var money=function(v,d){var n=Number(v);if(!Number.isFinite(n))return '—';return n.toLocaleString(undefined,{minimumFractionDigits:d||2,maximumFractionDigits:d||2});};
  function css(){if(document.getElementById('gp-brain-css'))return;var s=document.createElement('style');s.id='gp-brain-css';s.textContent='#gp-brain{grid-column:1/-1}.gp-brain-stats,.gp-market-grid{display:flex;gap:7px;overflow:auto}.gp-brain-stat,.gp-market-item{min-width:105px;padding:9px;border:1px solid #1b2b3d;border-radius:9px;background:#08131e}.gp-brain-stat b{display:block;font-size:18px}.gp-brain-stat span,.gp-market-meta{font-size:8px;color:#91a4b8}.gp-brain-list{display:grid;gap:7px;margin-top:10px}.gp-brain-row{padding:9px;border:1px solid #1b2b3d;border-radius:9px;background:#08131e}.gp-brain-row strong{font-size:10px}.gp-brain-row span{display:block;color:#91a4b8;font-size:8px;margin-top:3px}.gp-market-item{min-width:140px}.gp-market-name{font-size:9px;font-weight:850}.gp-market-price{font-size:15px;font-weight:950;margin-top:4px}.gp-up{color:#48df83}.gp-down{color:#ff6678}.gp-flat{color:#91a4b8}.gp-open{display:inline-block;margin-top:8px;padding:7px 10px;border:1px solid #31506a;border-radius:7px;color:#62a0ff;font-size:9px;font-weight:900}@media(max-width:720px){.gp-market-item{min-width:130px}}';document.head.appendChild(s);}
  function market(d){var m=d&&d.marketData||{},qs=Array.isArray(m.indicators)?m.indicators:[];var el=document.getElementById('gp-market-main');if(!qs.length)return;if(!el){el=document.createElement('section');el.id='gp-market-main';el.className='panel';var wrap=document.querySelector('.wrap');if(wrap)wrap.prepend(el);else return;}el.innerHTML='<div class="section-head"><div><h2>MARKET & ECONOMIC PULSE</h2><div class="muted">Public market context · no API key required</div></div><span class="tag '+(m.liveCount?'green':'amber')+'">'+esc(m.liveCount||0)+' LIVE</span></div><div class="gp-market-grid">'+qs.slice(0,18).map(function(q){var ch=Number(q.changePercent),cl=ch>0?'gp-up':ch<0?'gp-down':'gp-flat';return '<div class="gp-market-item"><div class="gp-market-name">'+esc(q.name||q.symbol)+'</div><div class="gp-market-price">'+money(q.price,q.decimals||2)+'</div><div class="'+cl+'">'+(Number.isFinite(ch)?(ch>0?'+':'')+ch.toFixed(2)+'%':'—')+'</div><div class="gp-market-meta">'+esc(q.sessionStatus||q.status||'')+' · '+esc(q.currency||'')+'</div></div>';}).join('')+'</div><div class="gp-market-meta">Source: '+esc(m.source||'public market data')+' · refreshed '+esc(m.updatedAt||'')+'</div><a class="gp-open" href="markets.html">OPEN FULL MARKETS DASHBOARD ↗</a>';
  }
  function brain(b){if(!b||!Array.isArray(b.nodes))return;var el=document.getElementById('gp-brain');if(!el){el=document.createElement('section');el.id='gp-brain';el.className='panel';var grid=document.querySelector('.grid');if(grid)grid.appendChild(el);else return;}var nodes=b.nodes.slice().sort(function(a,c){return Number(c.weight||0)-Number(a.weight||0);});el.innerHTML='<div class="section-head"><div><h2>GLOBAL PULSE INTELLIGENCE BRAIN</h2><div class="muted">Current news, conflicts, global situation-map signals, events, claims, assessments, historical signals and markets connected in one evidence graph.</div></div><span class="tag blue">CROSS-DOMAIN</span></div><div class="gp-brain-stats"><div class="gp-brain-stat"><b>'+esc(b.stats&&b.stats.nodes||nodes.length)+'</b><span>brain nodes</span></div><div class="gp-brain-stat"><b>'+esc(b.stats&&b.stats.edges||0)+'</b><span>relationships</span></div><div class="gp-brain-stat"><b>'+esc(b.stats&&b.stats.newsRecords||0)+'</b><span>news records</span></div><div class="gp-brain-stat"><b>'+esc(b.stats&&b.stats.mapSignals||0)+'</b><span>map signals</span></div><div class="gp-brain-stat"><b>'+esc(b.stats&&b.stats.marketIndicators||0)+'</b><span>market feeds</span></div></div><div class="gp-brain-list">'+nodes.slice(0,12).map(function(n){return '<div class="gp-brain-row"><strong>'+esc(n.label)+'</strong><span>'+esc(n.kind)+' · '+Number(n.mentions||n.weight||0)+' mentions · '+Number((n.evidence||[]).length)+' evidence records</span></div>';}).join('')+'</div>';
  }
  async function load(){css();try{var s=await fetch('data/snapshot.json?brain='+Date.now(),{cache:'no-store'});if(s.ok){var d=await s.json();window.DATA=d;market(d);}}catch(e){}try{var r=await fetch('data/intelligence_brain.json?brain='+Date.now(),{cache:'no-store'});if(r.ok)brain(await r.json());}catch(e){}}
  function run(){if(document.querySelector('.wrap'))load();else setTimeout(run,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
