(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const gradeClass=g=>g==='A'?'green':g==='B'?'blue':g==='C'?'amber':'red';
const gradeText=g=>({A:'A · WELL-CORROBORATED',B:'B · MODERATELY CORROBORATED',C:'C · LIMITED CORROBORATION',D:'D · INSUFFICIENT / CONFLICTING'}[g]||'D · INSUFFICIENT / CONFLICTING');
async function load(){try{const r=await fetch('data/event_intelligence.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);window.GP_EVENT_INTELLIGENCE=await r.json();install()}catch(e){console.warn('Global Pulse event intelligence unavailable',e)}}
function install(){if(document.getElementById('gp-event-intel'))return;const host=document.createElement('section');host.id='gp-event-intel';host.className='panel';host.innerHTML='<div class="section-head"><div><h2>EVENT INTELLIGENCE</h2><div class="muted">Evidence quality, corroboration, contradictions and context</div></div><span class="tag blue">EVIDENCE-AWARE</span></div><div id="gp-ei-method" class="muted" style="margin:0 0 10px">Scores are monitoring aids — not truth probabilities. Multiple outlets may repeat the same underlying report.</div><div id="gp-ei-content"></div>';const target=document.querySelector('.wrap');if(!target)return;target.appendChild(host);render()}
function render(){const el=document.getElementById('gp-ei-content'),d=window.GP_EVENT_INTELLIGENCE||{},events=Array.isArray(d.events)?d.events:[];if(!events.length){el.innerHTML='<div class="empty">No enriched events available yet.</div>';return}el.innerHTML=events.slice(0,12).map(e=>{const score=Number(e.corroborationScore||0),g=e.evidenceGrade||'D',ent=(e.entityCandidates||[]).slice(0,5).map(x=>'<span class="tag amber">'+esc(x)+'</span>').join(''),reg=(e.regionalContext||[]).map(x=>'<span class="tag blue">'+esc(x.region)+'</span>').join(''),spill=(e.spilloverCandidates||[]).slice(0,4).map(x=>esc(x)).join(', ')||'None detected',cave=(e.caveats||[]).slice(0,3).map(x=>'<li>'+esc(x)+'</li>').join(''),urls=(e.evidenceUrls||[]).slice(0,4).filter(Boolean).map(u=>'<a class="open" target="_blank" rel="noopener noreferrer" href="'+esc(u)+'">Source</a>').join('');const flags=(e.consistencyFlags||[]).slice(0,3).map(f=>'<li><b>'+esc(f.type||'review')+':</b> '+esc(f.reason||'Review report disagreement')+'</li>').join('');return '<article class="item" style="margin-bottom:9px"><div><span class="tag '+gradeClass(g)+'">'+esc(gradeText(g))+'</span><span class="tag blue">'+score+'/100 corroboration</span><span class="tag">'+esc(e.category||'general')+'</span></div><strong>'+esc(e.title||'Untitled event')+'</strong><div class="muted">'+Number(e.reportCount||0)+' reports · '+Number(e.uniqueSourceDomains||0)+' domains · '+Number(e.nonAggregatorDomains||0)+' independent-quality domains · '+Number(e.independentReportingGroups||0)+' reporting groups</div><div style="margin-top:7px">'+ent+reg+'</div><div class="muted" style="margin-top:7px"><b>Evidence status:</b> '+esc(e.evidenceStatus||'unknown')+' · <b>Source quality:</b> '+Number(e.averageSourceQuality||0)+'/100 · <b>Concentration:</b> '+Math.round(Number(e.domainConcentration||0)*100)+'%</div>'+(flags?'<details style="margin-top:7px"><summary>Conflicts / review flags</summary><ul class="muted">'+flags+'</ul></details>':'')+'<div class="muted" style="margin-top:7px"><b>Spillover candidates:</b> '+spill+'</div><details style="margin-top:7px"><summary>Evidence & caveats</summary><div class="muted" style="margin-top:7px"><b>Source mix:</b> '+esc(Object.entries(e.sourceBreakdown||{}).map(x=>x[0]+' ('+x[1]+')').join(', ')||'None')+'</div><ul class="muted">'+cave+'</ul>'+urls+'</details></article>'}).join('')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();
})();
