(function(){'use strict';
if(window.__gpBreakingInstalled)return;window.__gpBreakingInstalled=true;
const API='https://api.gdeltproject.org/api/v2/doc/doc?query='+encodeURIComponent('(Russia OR Ukraine OR NATO OR missile OR airstrike OR bombing OR invasion OR attack OR coup OR earthquake OR tsunami OR hurricane OR wildfire OR oil OR sanctions)')+'&mode=artlist&format=json&maxrecords=30&timespan=15min&sort=datedesc';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const url=v=>{try{const u=new URL(String(v||''),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
const time=r=>r?.time||r?.published_date||r?.publishedDate||r?.published_at||'';
function mount(){if(document.getElementById('gp-breaking'))return;const el=document.createElement('section');el.id='gp-breaking';el.className='gp-breaking';el.innerHTML='<div class="gp-breaking-head"><strong>⚡ BREAKING / RAPID INTELLIGENCE</strong><span id="gp-breaking-status">checking open-data feeds…</span></div><div id="gp-breaking-list" class="gp-breaking-list"></div><div class="gp-breaking-note">Rapid alerts are unconfirmed until corroborated. Confirmed/high-confidence reporting is incorporated into the next Global Pulse intelligence calculation cycle.</div>';const anchor=document.querySelector('main.wrap')||document.querySelector('.wrap')||document.body;anchor.prepend(el);return el}
function render(rows){const list=document.getElementById('gp-breaking-list'),status=document.getElementById('gp-breaking-status');if(!list)return;const seen=new Set(),items=(Array.isArray(rows)?rows:[]).filter(r=>r&&url(r.url||r.source||r.link)&&r.title).filter(r=>{const u=url(r.url||r.source||r.link);if(seen.has(u))return false;seen.add(u);return true}).sort((a,b)=>(Date.parse(time(b))||0)-(Date.parse(time(a))||0)).slice(0,8);status.textContent=items.length?items.length+' rapid reports · refreshed '+new Date().toLocaleTimeString():'no rapid reports in the last 15 minutes';list.innerHTML=items.length?items.map(r=>{const href=url(r.url||r.source||r.link);return '<article><span>OPEN-DATA DISCOVERY</span><a href="'+esc(href)+'" target="_blank" rel="noopener noreferrer">'+esc(r.title)+'</a><small>'+esc(r.domain||r.sourceLabel||r.source||r.sourcecountry||'Public source')+' · '+esc(time(r)?new Date(time(r)).toLocaleString():'time unavailable')+'</small></article>'}).join(''):'<div class="gp-breaking-empty">No rapid-impact reports detected in the current window.</div>'}
async function json(urlPath){const r=await fetch(urlPath,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function poll(){mount();try{const snap=window.DATA||await json('data/snapshot.json?ts='+Date.now());const live=window.LIVE_ARTICLES||await json('data/live_articles.json?ts='+Date.now());window.LIVE_ARTICLES=live;const merged=[...(live.articles||[]),...(snap.stories||[]),...(snap.breaking?.articles||[])];const recent=merged.filter(x=>{const t=Date.parse(time(x));return !Number.isFinite(t)||Date.now()-t<=60*60000});if(recent.length){render(recent);return}}catch(e){}try{const d=await json(API+'&_='+Date.now());render(d.articles||d.results||[])}catch(e){try{const d=await json('data/breaking_news.json?v='+Date.now());render(d.articles||d||[])}catch{const s=document.getElementById('gp-breaking-status');if(s)s.textContent='live feeds unavailable · showing scheduled snapshot'}}}
function classify(el){const id=String(el.id||'').toLowerCase(),cls=String(el.className||'').toLowerCase(),heading=String(el.querySelector?.('h1,h2,h3')?.textContent||'').toLowerCase().replace(/\s+/g,' '),s=id+' '+cls+' '+heading;if(id==='gp-breaking'||s.includes('breaking / rapid')||s.includes('rapid intelligence'))return 0;if(s.includes('what changed')||s.includes('material changes')||id.includes('whatchanged'))return 1;if(id==='top'||s.includes('global index')||s.includes('global tension')||s.includes('current assessment'))return 2;if(id==='conflictsection'||s.includes('active conflict')||s.includes('conflict watch'))return 3;if(id==='evidencecenter'||id==='analysiscenter'||s.includes('event intelligence')||s.includes('priority intelligence')||s.includes('investigation')||s.includes('evidence center'))return 4;if(id==='mapsection'||s.includes('global situation map')||s.includes('global map'))return 5;if(s.includes('regional intelligence')||s.includes('regional watch')||id.includes('regional'))return 6;if(id==='newssection'||id==='reporting'||s.includes('latest reporting')||s.includes('live reporting'))return 7;if(s.includes('event history')||s.includes('historical trends')||s.includes('history'))return 8;if(s.includes('market context')||s.includes('market impact')||s.includes('markets'))return 9;if(s.includes('intelligence web')||s.includes('3d intelligence')||id.includes('globalgraph'))return 10;if(s.includes('watchlist')||id.includes('watchlist'))return 11;if(s.includes('source health')||s.includes('data health')||s.includes('system status')||id.includes('sourcehealth'))return 12;return 20}
function applyOrder(){const main=document.querySelector('main.wrap');if(!main)return;if(!document.getElementById('gp-intel-order-css')){const st=document.createElement('style');st.id='gp-intel-order-css';st.textContent='.wrap{grid-auto-flow:row}.wrap>*{order:20}.wrap>#gp-breaking{order:0}.wrap>#top{order:2}.wrap>#conflictSection{order:3}.wrap>#mapSection{order:5}.wrap>#newsSection{order:7}.wrap>#reporting{order:7}.wrap>#evidenceCenter{order:4}.wrap>#analysisCenter{order:4}.wrap>#globalGraph{order:10}.wrap>*[data-gp-order]{order:var(--gp-order,20)}.gp-breaking{margin:0}.gp-breaking-note{max-width:100%}';document.head.appendChild(st)}[...main.children].forEach(el=>{if(el.tagName==='SCRIPT'||el.tagName==='STYLE')return;const n=classify(el);el.style.setProperty('--gp-order',String(n));el.dataset.gpOrder=String(n);el.style.order=String(n)})}
function install(){mount();applyOrder();poll();setInterval(poll,60000);if(window.MutationObserver){let pending=false;new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;applyOrder()})}).observe(document.querySelector('main.wrap')||document.body,{childList:true,subtree:false})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
