/* Global Pulse — source health, freshness and content monitor */
(function(){'use strict';
 const ENDPOINT='data/source_health.json'; let remote=null,loading=false;
 function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function age(v){const n=Number(v);if(!Number.isFinite(n))return 'freshness unavailable';if(n<1)return 'checked <1 min ago';if(n<60)return 'last success '+Math.round(n)+' min ago';const h=n/60;return h<24?'last success '+(h<10?h.toFixed(1):Math.round(h))+' hr ago':'last success '+Math.round(h/24)+' days ago'}
 function data(){return remote&&Array.isArray(remote.sources)?remote:(window.DATA||{})}
 function render(){const d=data(),health=Array.isArray(d.sources)?d.sources:(Array.isArray(d.sourceHealth)?d.sourceHealth:[]);if(!health.length)return false;const list=document.querySelector('.gp-v22-health-list');if(!list)return false;const summary=d.summary||{},online=Number(summary.online)||health.filter(x=>x.status==='online').length,failed=Number(summary.failed)||health.filter(x=>x.status==='failed').length,withData=Number(summary.onlineWithData)||health.filter(x=>['data_available','fallback_data_available'].includes(x.contentStatus)).length,empty=Number(summary.onlineEmpty)||health.filter(x=>x.contentStatus==='online_empty').length,fallback=Number(summary.fallbackData)||health.filter(x=>x.contentStatus==='fallback_data_available').length;const count=document.querySelector('#gp-v22-monitor .gp-layer-count');if(count)count.textContent=withData+'/'+health.length+' with data · '+empty+' empty · '+failed+' failed'+(fallback?' · '+fallback+' recovered':'');list.innerHTML=health.map(x=>{const st=String(x.status||'unknown').toLowerCase(),cs=String(x.contentStatus||'').toLowerCase();const cls=st==='failed'?'gp-v22-bad':cs==='online_empty'?'gp-v22-warn':'gp-v22-ok';let label=st==='failed'?'FAILED':cs==='online_empty'?'ONLINE · EMPTY':cs==='fallback_data_available'?'ONLINE · RECOVERED':'ONLINE';const rows=Number(x.rowsFetched)||0;const detail=cs==='online_empty'?'feed reachable, no entries returned':rows+' entries returned this run';const err=x.error?' · '+x.error:'';return '<div class="gp-v22-health-row"><span><b>'+esc(x.name)+'</b><small>'+esc(age(x.freshnessMinutes))+' · '+esc(detail)+'</small>'+(err?'<small class="gp-health-error">'+esc(err)+'</small>':'')+'</span><b class="'+cls+'">'+label+'</b></div>'}).join('');const panel=document.getElementById('gp-v22-monitor');if(panel&&!document.getElementById('gp-source-health-note')){const n=document.createElement('div');n.id='gp-source-health-note';n.className='muted';n.style.cssText='margin-top:7px;font-size:8px;line-height:1.4';n.textContent='ONLINE means the endpoint responded. ONLINE · EMPTY means it responded but supplied no feed entries. Recovered sources use a no-key GDELT domain mirror when a direct publisher feed is reachable but empty.';panel.querySelector('.gp-v22-health')?.appendChild(n)}return true}
 async function refresh(){if(loading)return;loading=true;try{const r=await fetch(ENDPOINT+'?v='+Date.now(),{cache:'no-store'});if(r.ok)remote=await r.json()}catch(e){}finally{loading=false;render()}}
 function css(){if(document.getElementById('gp-source-health-css'))return;const s=document.createElement('style');s.id='gp-source-health-css';s.textContent='.gp-v22-health-row>span{min-width:0}.gp-v22-health-row span b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.gp-v22-health-row small{display:block;color:var(--muted);font-size:8px;margin-top:3px;line-height:1.3}.gp-v22-health-row{align-items:center}.gp-v22-health-row>.gp-v22-ok,.gp-v22-health-row>.gp-v22-warn,.gp-v22-health-row>.gp-v22-bad{white-space:nowrap}.gp-health-error{color:#d8a0a0!important;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:75vw}';document.head.appendChild(s)}
 function run(){css();render();refresh()}
 document.addEventListener('DOMContentLoaded',run);window.addEventListener('globalpulse:dataready',()=>setTimeout(run,30));setInterval(refresh,60000);
})();
