/* Global Pulse — live tension renderer + resilient live-feed recovery. */
(function(){
'use strict';
var IDS=['Conflict activity','Diplomatic strain','Economic pressure','Market volatility','Military posture','Climate & humanitarian pressure'];
var META={
'Conflict activity':{desc:'Active fighting, attacks, clashes and major conflict events.',keys:/\b(war|armed conflict|fighting|battle|offensive|airstrike|shelling|invasion|insurgent|insurgency|militant attack|clash|bombing|hostage crisis)\b/i},
'Diplomatic strain':{desc:'Sanctions, diplomatic crises, expulsions, ultimatums and negotiation breakdowns.',keys:/\b(sanction|sanctions|diplomatic crisis|expel|expulsion|ultimatum|negotiation|ceasefire talks|treaty|summit|envoy|foreign minister)\b/i},
'Economic pressure':{desc:'Trade restrictions, inflation, energy/supply disruption and macroeconomic stress.',keys:/\b(inflation|tariff|tariffs|trade war|sanction|recession|supply disruption|oil price|gas price|shipping|freight|central bank|interest rate|gdp|economy)\b/i},
'Market volatility':{desc:'Large moves or stress in equities, bonds, currencies, commodities and financial markets.',keys:/\b(stock market|stocks|shares|bond yields?|treasury yields?|currency|forex|exchange rate|dollar|euro|yen|yuan|oil prices?|crude prices?|natural gas prices?|market volatility|market selloff|market rally|volatility index|plunge|surge)\b/i},
'Military posture':{desc:'Military deployments, weapons activity, exercises, mobilization and force posture.',keys:/\b(troops?|forces?|military|missile|missiles|drone|drones|airstrike|air strikes|bombers?|carrier|navy|mobiliz|exercise|weapons?|defense|defence|deployment|offensive)\b/i},
'Climate & humanitarian pressure':{desc:'Drought, floods, extreme weather, food insecurity and health outbreaks that can create pressure.',keys:/\b(drought|water shortage|water stress|water scarcity|flood|flooding|cyclone|hurricane|typhoon|storm surge|landslide|heatwave|heat wave|extreme heat|wildfire|forest fire|food insecurity|food crisis|famine|acute hunger|crop failure|epidemic|outbreak|cholera|malaria|pandemic|disease outbreak)\b/i}
};
var WATCH=[
['ukraine','Ukraine–Russia War','Europe','HIGH',['ukraine','russia','kyiv','donetsk','crimea','kharkiv','zaporizhzhia','zelensky','putin']],
['gaza','Gaza / Israel–Hamas','Middle East','HIGH',['gaza','hamas','palestinian','rafah','west bank','israel-hamas']],
['israel-iran','Israel–Iran Regional Front','Middle East','HIGH',['israel-iran','israel iran','iran israel','tehran','iranian nuclear','iranian missile']],
['hormuz','Iran / Strait of Hormuz','Middle East','HIGH',['strait of hormuz','hormuz','persian gulf','gulf tanker','iran oil shipping']],
['yemen','Yemen / Red Sea','Middle East','HIGH',['yemen','houthi','red sea','bab el-mandeb','aden shipping']],
['sudan','Sudan Civil War','Africa','CRITICAL',['sudan','sudanese','khartoum','darfur','kordofan','rsf','saf sudan']],
['drc','Eastern DRC Conflict','Africa','HIGH',['democratic republic of congo','drc','eastern congo','goma','m23','north kivu','south kivu']],
['somalia','Somalia / al-Shabaab','Africa','HIGH',['somalia','somali','al-shabaab','mogadishu']],
['nigeria','Nigeria Insurgency / Banditry','Africa','HIGH',['nigeria','nigerian','boko haram','iswap','banditry','bandits']],
['sahel-mali','Mali / Sahel Insurgency','Africa','HIGH',['mali','malian','jnim','bamako']],
['myanmar','Myanmar Civil War','Asia','HIGH',['myanmar','burma','junta','rakhine','mandalay','naypyidaw']],
['pakistan','Pakistan Militancy / Border Risk','Asia','HIGH',['pakistan','pakistani','ttp','balochistan','islamabad']],
['taiwan','Taiwan Strait Pressure','Indo-Pacific','HIGH',['taiwan','taipei','taiwan strait','pla','chinese military']],
['korea','Korean Peninsula','Indo-Pacific','HIGH',['north korea','south korea','pyongyang','kim jong','dmz','korean peninsula']],
['venezuela-guyana','Venezuela–Guyana / Essequibo','Americas','MODERATE',['venezuela','guyana','essequibo']],
['haiti','Haiti Security Crisis','Americas','HIGH',['haiti','haitian','port-au-prince','gang violence']],
['mexico-cartels','Mexico Cartel Conflict','Americas','HIGH',['mexico','mexican cartel','sinaloa','cjng','cartel']],
['colombia','Colombia Armed Groups','Americas','MODERATE',['colombia','colombian','eln','farc','cauca']]
];
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function num(v,f){v=Number(v);return Number.isFinite(v)?Math.max(0,Math.min(100,Math.round(v))):f}
function stories(d){return Array.isArray(d&&d.stories)?d.stories:[]}
function timeOf(a){return a&&(a.time||a.publishedAt||a.published_date||a.pubDate||a.datetime||a.timestamp||a.seendate||a.seenDate)||''}
function parseTime(v){var s=String(v||'').trim(),m=s.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/);if(m)s=m[1]+'-'+m[2]+'-'+m[3]+'T'+m[4]+':'+m[5]+':'+m[6]+'Z';var t=Date.parse(s);return Number.isFinite(t)?t:NaN}
function baseline(level){return level==='CRITICAL'?46:level==='HIGH'?37:level==='MODERATE'?27:22}
function articleText(a){return String([a.title,a.headline,a.summary,a.summary_snippet,a.description,a.tag,a.sourceLabel,a.sourceType,a.category,a.region,a.location].join(' ')).toLowerCase()}
function makeLiveConflicts(rows){var now=Date.now();return WATCH.map(function(w){var hits=[],sources={};rows.forEach(function(a){var text=articleText(a);if(!w[4].some(function(k){return text.indexOf(String(k).toLowerCase())>=0}))return;var t=parseTime(timeOf(a));if(Number.isFinite(t)&&t>now+5*60000)return;var age=Number.isFinite(t)?Math.max(0,(now-t)/3600000):72;if(age>168)return;var recency=age<1?1.4:age<6?1.25:age<24?1.1:age<72?.9:.7;hits.push(Math.min(32,12*recency));sources[a.sourceLabel||a.source||a.sourceType||'Public source']=1});hits.sort(function(a,b){return b-a});var evidence=hits.slice(0,8).reduce(function(a,b){return a+b},0),breadth=Math.min(18,Math.max(0,Object.keys(sources).length-1)*5),score=Math.min(100,Math.round(baseline(w[3])+evidence*.72+breadth));return{id:w[0],name:w[1],region:w[2],status:'Active signal',escalation:score>=82?'CRITICAL':score>=68?'HIGH':score>=50?'MODERATE':'LOW',activityScore:score,delta:0,signalCount:hits.length,sourceCount:Object.keys(sources).length,recent:'Live-feed activity score built from current public reporting.',signals:[]}})}
function derive(d,name){var m=META[name],pool=stories(d),total=0,hit=0,sources={};pool.forEach(function(s){var text=[s.title,s.summary,s.tag,s.sourceLabel,s.sourceType].join(' '),w=1,t=parseTime(timeOf(s));if(Number.isFinite(t)){var age=(Date.now()-t)/3600000;if(age<6)w=1.35;else if(age<24)w=1.15;else if(age>72)w=.7}total+=w;if(m.keys.test(text)){hit+=w;sources[s.sourceLabel||s.sourceType||'Public source']=1}});if(!pool.length)return{score:35,matches:0,sources:0};var share=hit/Math.max(total,.01);return{score:Math.max(0,Math.min(100,Math.round(30+Math.min(70,share*100)))),matches:Math.round(hit),sources:Object.keys(sources).length}}
function conflictScore(c){var s=c&&c.activityScore;if(s==null)s=c&&c.tension_score;if(s==null)s=c&&c.tension;if(s==null)s=c&&c.score;if(s==null)s=c&&c.priority;return num(s,0)}
function conflictLevel(s){return s>=80?'CRITICAL':s>=60?'HIGH':s>=35?'ELEVATED':'LOW'}
function conflictTrend(c){var d=Number(c&&c.delta);if(Number.isFinite(d)){if(d>2)return'RISING';if(d<-2)return'FALLING'}return'STABLE'}
function renderActiveConflicts(d){var list=document.querySelector('.conflict-list'),items=Array.isArray(d.conflicts)?d.conflicts:[];if(!list||!items.length)return;var cards=list.querySelectorAll('.ccard');items.slice(0,cards.length).forEach(function(c,i){var card=cards[i],s=conflictScore(c),line=card.querySelector('.scoreline'),b=line&&line.querySelector('b'),track=card.querySelector('.track'),fill=track&&track.querySelector('.fill');if(b)b.textContent=String(s);if(fill)fill.style.width=s+'%';if(line){var old=line.querySelector('.gp-conflict-meta');if(old)old.remove();var meta=document.createElement('span');meta.className='gp-conflict-meta';meta.textContent=conflictLevel(s)+' · '+conflictTrend(c);line.appendChild(meta)}card.setAttribute('data-tension',String(s));card.setAttribute('aria-label',String(c.name||'Conflict')+' tension '+s+' out of 100, '+conflictLevel(s)+', '+conflictTrend(c))})}
function render(d){d=d||{};var box=document.getElementById('breakdown');if(box){var raw=d.breakdownScores||{},meta=d.driverSignals||{};box.classList.add('gp-tension-drivers');box.innerHTML='';IDS.forEach(function(name){var fallback=derive(d,name),score=num(raw[name],fallback.score),info=meta[name]||{},matches=Number.isFinite(Number(info.matches))?Number(info.matches):fallback.matches,sourceCount=Number.isFinite(Number(info.sources))?Number(info.sources):fallback.sources,label=score>=75?'HIGH':score>=55?'ELEVATED':score>=40?'WATCH':'LOW';var row=document.createElement('div');row.className='gp-driver';row.innerHTML='<div class="gp-driver-head"><div><b>'+esc(name)+'</b><span>'+esc(META[name].desc)+'</span></div><strong>'+score+'</strong></div><div class="gp-driver-track"><i style="width:'+score+'%"></i></div><div class="gp-driver-foot"><span class="gp-driver-state">'+label+'</span><span>'+matches+' matching signals · '+sourceCount+' sources</span></div>';box.appendChild(row)})}var scoreEl=document.getElementById('globalScore');if(scoreEl&&Number.isFinite(Number(d.tension)))scoreEl.textContent=Math.round(Number(d.tension));var deltaEl=document.getElementById('globalDelta');if(deltaEl&&Number.isFinite(Number(d.tension)))deltaEl.textContent=Number(d.tension)>=70?'Elevated global pressure':Number(d.tension)>=45?'Moderate global pressure':'Lower global pressure';var note=document.getElementById('gp-tension-note');if(!note&&box){note=document.createElement('div');note.id='gp-tension-note';box.parentNode.appendChild(note)}if(note)note.textContent='Live activity model · conflict scores use current public reporting, recency and source diversity. A headline count alone does not determine tension.';renderActiveConflicts(d)}
function ensureStyle(){if(document.getElementById('gp-tension-css'))return;var s=document.createElement('style');s.id='gp-tension-css';s.textContent='.gp-tension-drivers{display:grid!important;gap:12px!important;height:auto!important;min-height:0!important}.gp-driver{padding:10px 0;border-bottom:1px solid var(--line)}.gp-driver:last-child{border-bottom:0}.gp-driver-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:start}.gp-driver-head b{display:block;font-size:12px}.gp-driver-head span{display:block;margin-top:3px;color:var(--muted);font-size:9px;line-height:1.35}.gp-driver-head strong{font-size:19px;line-height:1;font-variant-numeric:tabular-nums;color:var(--amber)}.gp-driver-track{height:8px;margin-top:8px;background:#06101a;border:1px solid #142334;border-radius:99px;overflow:hidden}.gp-driver-track i{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,var(--green),var(--amber),var(--red));transition:width .35s ease}.gp-driver-foot{display:flex;justify-content:space-between;gap:8px;margin-top:5px;color:var(--muted);font-size:9px}.gp-driver-state{font-weight:900;letter-spacing:.08em}.gp-tension-drivers .gp-driver:hover{background:rgba(98,160,255,.035)}#gp-tension-note{margin-top:8px;color:var(--muted);font-size:9px;line-height:1.4}.gp-conflict-meta{margin-left:8px;color:var(--muted);font-size:9px;font-weight:800;letter-spacing:.04em}.gp-live-recovery-note{margin-top:7px;color:var(--muted);font-size:9px}@media(max-width:720px){.gp-driver-head span{font-size:8px}.gp-driver-foot{font-size:8px}.gp-conflict-meta{font-size:8px}}';document.head.appendChild(s)}
async function recoverLive(){try{var r=await fetch('data/live_articles.json?gp_live='+Date.now(),{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)return false;var p=await r.json(),rows=Array.isArray(p.articles)?p.articles:[];if(!rows.length)return false;var d=window.DATA&&typeof window.DATA==='object'?window.DATA:{};d.conflicts=makeLiveConflicts(rows);d.stories=rows.map(function(a){return{title:a.title||a.headline||'Untitled report',summary:a.summary||a.summary_snippet||a.description||'',sourceLabel:a.sourceLabel||a.source||a.source_name||'Public source',time:timeOf(a),url:a.url||a.original_link||a.link||''}});d.updatedAt=p.updatedAt||new Date().toISOString();d.sourceStatus='LIVE FEED RECOVERY · '+rows.length+' articles';d._liveRecovery=true;window.DATA=d;if(typeof window.renderStories==='function')window.renderStories();render(d);var status=document.getElementById('dataStatus');if(status)status.textContent='Live feed active · '+new Date(d.updatedAt).toLocaleTimeString();var live=document.getElementById('liveText');if(live)live.textContent='LIVE';return true}catch(e){return false}}
function run(){ensureStyle();var d=window.DATA;if(d&&Array.isArray(d.conflicts)&&d.conflicts.length){render(d);return}recoverLive()}
document.addEventListener('DOMContentLoaded',run);document.addEventListener('globalpulse:dataready',run);window.addEventListener('globalpulse:dataready',run);setTimeout(run,1200);setTimeout(run,5000);setInterval(run,60000);
})();
