/* Global Pulse — historical event timeline */
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const css=`<style id="gp-history-css">#gp-event-history{margin:14px 0}.gp-history-grid{display:grid;gap:8px}.gp-history-card{background:var(--panel2,#081019);border:1px solid var(--line,#1b2b3d);border-radius:11px;padding:10px}.gp-history-head{display:flex;justify-content:space-between;gap:8px;align-items:start}.gp-history-title{font-weight:850;font-size:13px;line-height:1.3}.gp-history-meta{font-size:10px;color:var(--muted,#91a4b8);margin-top:4px}.gp-history-track{display:flex;gap:4px;overflow-x:auto;padding:9px 2px 4px}.gp-history-point{min-width:108px;padding:7px;border:1px solid var(--line,#1b2b3d);border-radius:8px;background:#09121c}.gp-history-point b{display:block;font-size:11px}.gp-history-point span{display:block;font-size:9px;color:var(--muted,#91a4b8);margin-top:2px}.gp-history-details{margin-top:6px}.gp-history-details summary{cursor:pointer;color:var(--blue,#62a0ff);font-size:10px;font-weight:800}.gp-history-links{display:grid;gap:4px;margin-top:6px}.gp-history-links a{font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.gp-history-more{display:flex;justify-content:center;margin-top:9px}.gp-history-more button{min-width:140px}</style>`;
function mount(){if(document.getElementById('gp-event-history'))return;document.head.insertAdjacentHTML('beforeend',css);const wrap=document.querySelector('.wrap')||document.body;const el=document.createElement('section');el.id='gp-event-history';el.className='panel';el.innerHTML='<div class="section-head"><div><h2>EVENT HISTORY</h2><div class="muted">How tracked events developed over the last 30 days</div></div><span class="tag blue">TIMELINE</span></div><div id="gp-history-list" class="gp-history-grid"><div class="empty">Loading historical event data…</div></div>';wrap.prepend(el);load();}
function load(){fetch('data/event_history.json?ts='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('history unavailable');return r.json()}).then(d=>render(d)).catch(e=>{const x=document.getElementById('gp-history-list');if(x)x.innerHTML='<div class="empty">Historical timeline unavailable right now.</div>';});}
function render(d){const root=document.getElementById('gp-history-list');if(!root)return;const all=Object.values(d?.events||{}).filter(e=>(e.observations||[]).length).sort((a,b)=>(b.observations?.length||0)-(a.observations?.length||0));if(!all.length){root.innerHTML='<div class="empty">No repeated event observations yet. The timeline will build as refreshes accumulate.</div>';return;}let shown=5;const draw=()=>{root.innerHTML=all.slice(0,shown).map(e=>{const obs=(e.observations||[]).slice(-12);const first=obs[0],last=obs[obs.length-1];const age=first?.observedAt?new Date(first.observedAt).toLocaleString():'';const points=obs.map(o=>'<div class="gp-history-point"><b>'+esc((o.title||'Update').slice(0,48))+'</b><span>'+esc(new Date(o.observedAt).toLocaleString())+'</span><span>'+Number(o.reportCount||0)+' reports · '+Number(o.sourceCount||0)+' sources</span><span>'+esc(String(o.confidence||'unknown').toUpperCase())+'</span></div>').join('');const links=(last?.urls||[]).slice(0,5).map(u=>'<a href="'+esc(u)+'" target="_blank" rel="noopener noreferrer">'+esc(u)+'</a>').join('');return '<article class="gp-history-card"><div class="gp-history-head"><div><div class="gp-history-title">'+esc(e.title||'Tracked event')+'</div><div class="gp-history-meta">'+esc(e.category||'general')+' · tracked since '+esc(age)+'</div></div><span class="tag amber">'+obs.length+' updates</span></div><div class="gp-history-track">'+points+'</div><details class="gp-history-details"><summary>View latest evidence links</summary><div class="gp-history-links">'+(links||'<span class="muted">No links recorded.</span>')+'</div></details></article>';}).join('')+(shown<all.length?'<div class="gp-history-more"><button id="gp-history-more">See more ('+(all.length-shown)+')</button></div>':'');const b=document.getElementById('gp-history-more');if(b)b.onclick=()=>{shown=Math.min(all.length,shown+5);draw();};};draw();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
