(function(){'use strict';
if(window.__gpBreakingInstalled)return;window.__gpBreakingInstalled=true;
const API='https://api.gdeltproject.org/api/v2/doc/doc?query='+encodeURIComponent('(Russia OR Ukraine OR NATO OR missile OR airstrike OR bombing OR explosion OR invasion OR attack OR coup OR earthquake OR tsunami OR hurricane OR wildfire OR oil OR sanctions)')+'&mode=artlist&format=json&maxrecords=30&timespan=15min&sort=datedesc';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const url=v=>{try{const u=new URL(String(v||''));return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
function mount(){if(document.getElementById('gp-breaking'))return;const el=document.createElement('section');el.id='gp-breaking';el.className='gp-breaking';el.innerHTML='<div class="gp-breaking-head"><strong>⚡ BREAKING / RAPID INTELLIGENCE</strong><span id="gp-breaking-status">checking open-data feeds…</span></div><div id="gp-breaking-list" class="gp-breaking-list"></div><div class="gp-breaking-note">Rapid alerts are unconfirmed until corroborated. Confirmed/high-confidence reporting is incorporated into the next Global Pulse intelligence calculation cycle.</div>';const anchor=document.querySelector('main.wrap')||document.querySelector('.wrap')||document.body;anchor.prepend(el);return el}
function render(rows){const list=document.getElementById('gp-breaking-list'),status=document.getElementById('gp-breaking-status');if(!list)return;const seen=new Set(),items=(Array.isArray(rows)?rows:[]).filter(r=>r&&r.url&&r.title).filter(r=>{if(seen.has(r.url))return false;seen.add(r.url);return true}).slice(0,8);status.textContent=items.length?items.length+' rapid reports · refreshed '+new Date().toLocaleTimeString():'no rapid reports in the last 15 minutes';list.innerHTML=items.length?items.map(r=>{const href=url(r.url);return '<article><span>OPEN-DATA DISCOVERY</span><a href="'+esc(href)+'" target="_blank" rel="noopener noreferrer">'+esc(r.title)+'</a><small>'+esc(r.domain||r.sourcecountry||'GDELT')+'</small></article>'}).join(''):'<div class="gp-breaking-empty">No rapid-impact reports detected in the current 15-minute window.</div>'}
async function poll(){try{const r=await fetch(API+'&_='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();render(d.articles||d.results||[])}catch(e){const s=document.getElementById('gp-breaking-status');if(s)s.textContent='live open-data feed unavailable · using scheduled snapshot';try{const r=await fetch('data/breaking_news.json?v='+Date.now(),{cache:'no-store'});const d=await r.json();render(d.articles||[])}catch{}}}
function classify(el){const id=String(el.id||'').toLowerCase();const cls=String(el.className||'').toLowerCase();const heading=String(el.querySelector?.('h1,h2,h3')?.textContent||'').toLowerCase().replace(/\s+/g,' ');const s=id+' '+cls+' '+heading;if(id==='gp-breaking'||s.includes('breaking / rapid')||s.includes('rapid intelligence'))return 0;if(s.includes('what changed')||s.includes('material changes')||id.includes('whatchanged'))return 1;if(id==='top'||s.includes('global index')||s.includes('global tension')||s.includes('current assessment'))return 2;if(id==='conflictsection'||s.includes('active conflict')||s.includes('conflict watch'))return 3;if(id==='evidencecenter'||id==='analysiscenter'||s.includes('event intelligence')||s.includes('priority intelligence')||s.includes('investigation')||s.includes('evidence center'))return 4;if(id==='mapsection'||s.includes('global situation map')||s.includes('global map'))return 5;if(s.includes('regional intelligence')||s.includes('regional watch')||id.includes('regional'))return 6;if(id==='newssection'||id==='reporting'||s.includes('latest reporting')||s.includes('live reporting'))return 7;if(s.includes('event history')||s.includes('historical trends')||s.includes('history'))return 8;if(s.includes('market context')||s.includes('market impact')||s.includes('markets'))return 9;if(s.includes('intelligence web')||s.includes('3d intelligence')||id.includes('globalgraph'))return 10;if(s.includes('watchlist')||id.includes('watchlist'))return 11;if(s.includes('source health')||s.includes('data health')||s.includes('system status')||id.includes('sourcehealth'))return 12;return 20}
function applyOrder(){const main=document.querySelector('main.wrap');if(!main)return;if(!document.getElementById('gp-intel-order-css')){const st=document.createElement('style');st.id='gp-intel-order-css';st.textContent='.wrap{grid-auto-flow:row}.wrap>*{order:20}.wrap>#gp-breaking{order:0}.wrap>#top{order:2}.wrap>#conflictSection{order:3}.wrap>#mapSection{order:5}.wrap>#newsSection{order:7}.wrap>#reporting{order:7}.wrap>#evidenceCenter{order:4}.wrap>#analysisCenter{order:4}.wrap>#globalGraph{order:10}.wrap>*[data-gp-order]{order:var(--gp-order,20)}.gp-breaking{margin:0}.gp-breaking-note{max-width:100%}';document.head.appendChild(st)}[...main.children].forEach(el=>{if(el.tagName==='SCRIPT'||el.tagName==='STYLE')return;const n=classify(el);el.style.setProperty('--gp-order',String(n));el.dataset.gpOrder=String(n);el.style.order=String(n)})}
function install(){mount();applyOrder();poll();setInterval(poll,60000);if(window.MutationObserver){let pending=false;new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;applyOrder()})}).observe(document.querySelector('main.wrap')||document.body,{childList:true,subtree:false})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
