/* Global Pulse — source health + freshness monitor */
(function(){'use strict';
 const ENDPOINT='data/source_health.json'; let remote=null, loading=false;
 function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function age(v){const n=Number(v);if(!Number.isFinite(n))return 'freshness unavailable';if(n<1)return 'checked <1 min ago';if(n<60)return 'last success '+Math.round(n)+' min ago';const h=n/60;return h<24?'last success '+(h<10?h.toFixed(1):Math.round(h))+' hr ago':'last success '+Math.round(h/24)+' days ago'}
 function data(){return remote&&Array.isArray(remote.sources)?remote:(window.DATA||{})}
 function render(){const d=data(),health=Array.isArray(d.sources)?d.sources:(Array.isArray(d.sourceHealth)?d.sourceHealth:[]),list=document.querySelector('.gp-v22-health-list');if(!list)return false;const summary=d.summary||{},online=Number(summary.online)||health.filter(x=>x.status==='online').length,degraded=Number(summary.degraded)||health.filter(x=>x.status==='degraded').length,failed=Number(summary.failed)||health.filter(x=>x.status==='failed').length,coverage=Number(summary.coveragePercent);const count=document.querySelector('#gp-v22-monitor .gp-layer-count');if(count)count.textContent=online+'/'+health.length+' online'+(degraded?' · '+degraded+' degraded':'')+(failed?' · '+failed+' failed':'')+(Number.isFinite(coverage)?' · '+coverage+'% covered':'');list.innerHTML=health.length?health.map(x=>{const st=String(x.status||'unknown').toLowerCase();const cls=st==='online'?'gp-v22-ok':st==='degraded'?'gp-v22-warn':st==='failed'?'gp-v22-bad':'gp-v22-warn';const label=st==='online'?'ONLINE':st==='degraded'?'DEGRADED':st==='failed'?'FAILED':'UNKNOWN';const fallback=x.fallbackCoverage&&st!=='online'?' · fallback: '+x.fallback:'';const err=x.error?' · '+x.error:'';return '<div class="gp-v22-health-row"><span><b>'+esc(x.name)+'</b><small>'+esc(age(x.freshnessMinutes))+esc(fallback)+'</small>'+(err?'<small class="gp-health-error">'+esc(err)+'</small>':'')+'</span><b class="'+cls+'">'+label+'</b></div>'}).join(''):'<div class="muted">No source-health telemetry is available yet.</div>';const panel=document.getElementById('gp-v22-monitor');if(panel&&!document.getElementById('gp-source-health-note')){const n=document.createElement('div');n.id='gp-source-health-note';n.className='muted';n.style.cssText='margin-top:7px;font-size:8px;line-height:1.4';n.textContent='Health is measured per collector run. A failed primary retains its last successful check and is marked covered when an alternate no-key feed can still supply related reporting.';panel.querySelector('.gp-v22-health')?.appendChild(n)}return true}
 async function refresh(){if(loading)return;loading=true;try{const r=await fetch(ENDPOINT+'?v='+Date.now(),{cache:'no-store'});if(r.ok)remote=await r.json()}catch(e){}finally{loading=false;render()}}
 function css(){if(document.getElementById('gp-source-health-css'))return;const s=document.createElement('style');s.id='gp-source-health-css';s.textContent='.gp-v22-health-row>span{min-width:0}.gp-v22-health-row span b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.gp-v22-health-row small{display:block;color:var(--muted);font-size:8px;margin-top:3px;line-height:1.3}.gp-v22-health-row{align-items:center}.gp-v22-health-row>.gp-v22-ok,.gp-v22-health-row>.gp-v22-warn,.gp-v22-health-row>.gp-v22-bad{white-space:nowrap}.gp-health-error{color:#d8a0a0!important;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:75vw}';document.head.appendChild(s)}
 function run(){css();render();refresh()}
 document.addEventListener('DOMContentLoaded',run);window.addEventListener('globalpulse:dataready',()=>setTimeout(run,30));setInterval(refresh,60000);
})();
