/* Global Pulse — interactive evidence web with relationship colors. */
(function(){
  'use strict';
  const esc=v=>String(v==null?'':v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const safeUrl=v=>{try{const u=new URL(String(v||''),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const edgeKind=e=>{const t=String(e.relationship||e.type||e.category||e.topic||e.label||'').toLowerCase();if(/oil|crude|petroleum|lng|gas|energy/.test(t))return'oil';if(/rare earth|lithium|cobalt|critical mineral|mineral|nickel|uranium/.test(t))return'resource';if(/economic|trade|market|finance|investment|currency|supply|shipping|commodity/.test(t))return'economic';if(/military|defense|weapons|troop|missile|conflict|war/.test(t))return'military';if(/politic|government|election|diplomacy|treaty|sanction|alliance/.test(t))return'political';return'connection'};
  const edgeColor=k=>({connection:'#62a0ff',political:'#aa8df7',economic:'#ffc857',oil:'#fb923c',resource:'#48df83',military:'#ff6678'}[k]||'#62a0ff');
  const nodeKind=n=>{const k=String(n.kind||n.type||'actor').toLowerCase();if(/country|nation|state/.test(k))return'country';if(/economic|market|company|finance/.test(k))return'economic';if(/resource|oil|energy|mineral/.test(k))return'resource';if(/military|defense/.test(k))return'military';return k};
  const nodeColor=k=>({country:'#62a0ff',actor:'#62a0ff',political:'#aa8df7',economic:'#ffc857',resource:'#48df83',strategic:'#3fc5ff',military:'#ff6678'}[k]||'#62a0ff');
  function boot(){
    if(document.getElementById('gp-intel-web'))return true;
    const g=window.DATA&&window.DATA.intelligenceGraph;if(!g||!Array.isArray(g.nodes)||!Array.isArray(g.edges))return false;
    const wrap=document.querySelector('.wrap');if(!wrap)return false;
    const sec=document.createElement('section');sec.className='panel wide';sec.id='gp-intel-web';
    sec.innerHTML='<div class="section-head"><div><h2>INTELLIGENCE WEB</h2><div class="muted">Evidence-linked relationships across countries, politics, economics, energy, resources and military activity.</div></div><div class="gp-web-count">'+g.nodes.length+' nodes · '+g.edges.length+' evidence links</div></div><div class="gp-web-legend"><span><i data-k="country"></i>Countries</span><span><i data-k="political"></i>Politics</span><span><i data-k="economic"></i>Economic</span><span><i data-k="oil"></i>Oil / energy</span><span><i data-k="resource"></i>Rare earth / resources</span><span><i data-k="military"></i>Military</span></div><div class="gp-web-controls"><input id="gp-web-search" placeholder="Search actor, country, issue…" aria-label="Search intelligence web"><select id="gp-web-kind"><option value="all">All categories</option><option value="country">Countries</option><option value="actor">Actors</option><option value="political">Politics</option><option value="economic">Economics</option><option value="resource">Resources</option><option value="military">Military</option><option value="strategic">Strategic</option></select><button id="gp-web-reset">Reset</button></div><div class="gp-web" id="gp-web-canvas"></div><div class="gp-web-detail" id="gp-web-detail">Tap a node to inspect connected entities and the evidence behind each relationship.</div><div class="gp-web-note">Relationship colors classify the stored evidence type; they do not imply causation. Evidence links point back to the underlying public reporting where available.</div>';
    const style=document.createElement('style');style.textContent='.gp-web-legend{display:flex;gap:11px;flex-wrap:wrap;margin:-2px 0 10px;font-size:9px;color:var(--muted)}.gp-web-legend span{display:inline-flex;align-items:center;gap:5px}.gp-web-legend i{width:9px;height:9px;border-radius:50%;display:inline-block}.gp-web-legend i[data-k="country"]{background:#62a0ff}.gp-web-legend i[data-k="political"]{background:#aa8df7}.gp-web-legend i[data-k="economic"]{background:#ffc857}.gp-web-legend i[data-k="oil"]{background:#fb923c}.gp-web-legend i[data-k="resource"]{background:#48df83}.gp-web-legend i[data-k="military"]{background:#ff6678}';document.head.appendChild(style);
    const mapSection=document.getElementById('map')&&document.getElementById('map').closest('section');wrap.insertBefore(sec,mapSection||wrap.firstElementChild||null);
    const canvas=sec.querySelector('#gp-web-canvas'),search=sec.querySelector('#gp-web-search'),kind=sec.querySelector('#gp-web-kind');
    const nodes=g.nodes.slice(0,120),edges=g.edges.filter(e=>nodes.some(n=>n.label===e.source)&&nodes.some(n=>n.label===e.target)).slice(0,300);
    let w=Math.max(320,canvas.clientWidth||900),h=450,cx=w/2,cy=h/2,pos={};
    function layout(){pos={};nodes.forEach((n,i)=>{const a=i/Math.max(1,nodes.length)*Math.PI*2,r=Math.min(w,h)*.36;pos[n.label]={x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r*.72}})}layout();
    function render(){const q=(search.value||'').toLowerCase().trim(),k=kind.value,visible=nodes.filter(n=>(!q||n.label.toLowerCase().includes(q))&&(k==='all'||nodeKind(n)===k||(k==='actor'&&nodeKind(n)==='actor'))),set=new Set(visible.map(n=>n.label));let svg='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Interactive intelligence relationship web">';edges.forEach(e=>{if(!set.has(e.source)||!set.has(e.target))return;const a=pos[e.source],b=pos[e.target],ek=edgeKind(e),c=edgeColor(ek);svg+='<line x1="'+a.x.toFixed(1)+'" y1="'+a.y.toFixed(1)+'" x2="'+b.x.toFixed(1)+'" y2="'+b.y.toFixed(1)+'" stroke="'+c+'" stroke-opacity="'+Math.min(.8,.2+n(e.weight||1)*.04)+'" stroke-width="'+Math.min(4,1+(e.weight||1)*.3)+'"/>'});visible.forEach(n=>{const p=pos[n.label],size=Math.min(15,5+Math.sqrt(n.mentions||1)*1.4),nk=nodeKind(n),c=nodeColor(nk);svg+='<g class="gp-node" data-node="'+esc(n.label)+'" tabindex="0" aria-label="'+esc(n.label)+'"><circle cx="'+p.x.toFixed(1)+'" cy="'+p.y.toFixed(1)+'" r="'+size.toFixed(1)+'" fill="'+c+'" stroke="#eef5ff" stroke-width="1.2"/><text x="'+p.x.toFixed(1)+'" y="'+(p.y+size+12).toFixed(1)+'" text-anchor="middle">'+esc(n.label)+'</text></g>'});svg+='</svg>';canvas.innerHTML=svg;canvas.querySelectorAll('.gp-node').forEach(el=>{const act=()=>detail(el.dataset.node);el.addEventListener('click',act);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();act()}})})}
    const n=v=>Number.isFinite(Number(v))?Number(v):0;
    function detail(name){const links=edges.filter(e=>e.source===name||e.target===name).sort((a,b)=>n(b.weight)-n(a.weight)).slice(0,12);let html='<strong>'+esc(name)+'</strong> · '+links.length+' strongest evidence links';if(!links.length){sec.querySelector('#gp-web-detail').innerHTML=html+'<br><span>No linked evidence in this snapshot.</span>';return}html+='<div class="gp-web-links">'+links.map(e=>{const other=e.source===name?e.target:e.source,ev=Array.isArray(e.evidence)?e.evidence:[],latest=ev[0],link=latest&&safeUrl(latest.url),ek=edgeKind(e);return '<div class="gp-link-row"><span>'+esc(other)+' <b style="color:'+edgeColor(ek)+'">'+esc(ek.toUpperCase())+' · '+n(e.weight)+'×</b></span>'+(link?'<a href="'+esc(link)+'" target="_blank" rel="noopener noreferrer">Evidence ↗</a>':'')+(latest&&latest.title?'<small>'+esc(latest.source||'Public source')+' · '+esc(latest.title)+'</small>':'')+'</div>'}).join('')+'</div>';sec.querySelector('#gp-web-detail').innerHTML=html}
    sec.querySelector('#gp-web-reset').onclick=()=>{search.value='';kind.value='all';render()};search.addEventListener('input',render);kind.addEventListener('change',render);window.addEventListener('resize',()=>{const nw=canvas.clientWidth;if(nw>300&&Math.abs(nw-w)>40){w=nw;cx=w/2;layout();render()}});render();return true;
  }
  let tries=0;const timer=setInterval(()=>{tries++;if(boot()||tries>120)clearInterval(timer)},250);
  document.addEventListener('globalpulse:dataready',()=>{if(!document.getElementById('gp-intel-web'))boot()});
})();
