/* Global Pulse — local-only watchlist and alert surface. No visitor profile is sent to the server. */
(function(){'use strict';const KEY='globalPulseWatchlistV1';let terms=[];const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');terms=Array.isArray(x)?x.filter(x=>typeof x==='string').slice(0,20):[]}catch{terms=[]}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(terms))}catch{}}
function mount(){if(document.getElementById('gp-watchlist'))return;const s=document.createElement('section');s.id='gp-watchlist';s.className='panel';s.innerHTML='<div class="section-head"><div><h2>MY WATCHLIST</h2><div class="muted">Track topics or entities locally on this device</div></div><span class="tag blue">LOCAL ONLY</span></div><div class="gp-watch-add"><input id="gp-watch-input" placeholder="e.g. Sudan, Iran, oil, NATO" maxlength="50"><button id="gp-watch-add" type="button">ADD</button></div><div id="gp-watch-chips" class="gp-watch-chips"></div><div id="gp-watch-alerts" class="gp-watch-alerts"><div class="empty">Add a topic to start monitoring.</div></div><div class="muted gp-watch-note">Watchlist terms stay in your browser local storage. Global Pulse does not send them to the intelligence pipeline.</div></section>';const wrap=document.querySelector('.wrap')||document.body;wrap.prepend(s);s.querySelector('#gp-watch-add').onclick=add; s.querySelector('#gp-watch-input').onkeydown=e=>{if(e.key==='Enter')add()};render();poll()}
function add(){const i=document.getElementById('gp-watch-input'),v=i?.value.trim();if(!v)return;const key=v.toLowerCase();if(!terms.some(x=>x.toLowerCase()===key)&&terms.length<20)terms.push(v);i.value='';save();render();poll()}
function remove(v){terms=terms.filter(x=>x!==v);save();render();poll()}
function render(){const chips=document.getElementById('gp-watch-chips');if(!chips)return;chips.innerHTML=terms.length?terms.map(t=>'<button type="button" class="gp-watch-chip" data-term="'+esc(t)+'">'+esc(t)+' ×</button>').join(''):'<span class="muted">No watched topics yet.</span>';chips.querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>remove(b.dataset.term))}
async function poll(){const box=document.getElementById('gp-watch-alerts');if(!box||!terms.length)return;try{const [e,w]=await Promise.all([fetch('data/live_events.json?v='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():{}),fetch('data/what_changed.json?v='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():{}).catch(()=>({}))]);const events=e.events||[],items=[...events.map(x=>({title:x.title,detail:(x.reportCount||0)+' reports · '+String(x.confidence||'unknown').toUpperCase()+' confidence'})),...(w.items||[]).map(x=>({title:x.title,detail:x.detail||'Recent change'}))];const hits=[];for(const item of items){const hay=(item.title+' '+item.detail).toLowerCase();const matched=terms.filter(t=>hay.includes(t.toLowerCase()));if(matched.length)hits.push({...item,matched})}box.innerHTML=hits.length?hits.slice(0,10).map(x=>'<article class="gp-watch-alert"><b>'+esc(x.title)+'</b><span>'+esc(x.detail)+'</span><small>Matches: '+esc(x.matched.join(', '))+'</small></article>').join(''):'<div class="empty">No current matches for your watched topics.</div>'}catch{box.innerHTML='<div class="empty">Watchlist data is temporarily unavailable.</div>'}}
const st=document.createElement('style');st.textContent='#gp-watchlist{margin:10px 0}.gp-watch-add{display:flex;gap:7px;margin:9px 0}.gp-watch-add input{flex:1;min-width:0}.gp-watch-chips{display:flex;gap:6px;flex-wrap:wrap}.gp-watch-chip{min-height:28px;padding:5px 8px;font-size:8px}.gp-watch-alerts{display:grid;gap:6px;margin-top:9px}.gp-watch-alert{padding:8px;border:1px solid #1b2b3d;border-radius:9px;background:#08131e}.gp-watch-alert b{display:block;font-size:10px;line-height:1.35}.gp-watch-alert span,.gp-watch-alert small{display:block;color:#91a4b8;font-size:8px;margin-top:3px}.gp-watch-note{font-size:7px;margin-top:8px}@media(max-width:600px){.gp-watch-add button{min-width:62px}}';document.head.appendChild(st);load();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();setInterval(poll,60000)})();
