/* Global Pulse — final browser QA hardening layer. */
(function(){
'use strict';
if(window.__GP_QA_HARDENED__)return;window.__GP_QA_HARDENED__=true;
function style(){if(document.getElementById('gp-qa-style'))return;var s=document.createElement('style');s.id='gp-qa-style';s.textContent=`#gp-data-load-error{margin:12px 0;padding:14px;border:1px solid rgba(255,102,120,.5);border-radius:11px;background:rgba(80,15,25,.28);color:#eef5ff}#gp-data-load-error strong{display:block;color:#ff6678;margin-bottom:4px}#gp-data-load-error button{margin-top:8px;min-height:44px}#gp-how-to-read{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;padding:16px;background:rgba(2,7,12,.82);backdrop-filter:blur(8px)}#gp-how-to-read .card{width:min(620px,100%);max-height:calc(100dvh - 32px);overflow:auto;background:#0b131d;border:1px solid #2b4055;border-radius:16px;padding:18px;box-shadow:0 20px 70px rgba(0,0,0,.5)}#gp-how-to-read h2{color:#eef5ff;margin:0 0 8px;font-size:15px}#gp-how-to-read p{color:#b7c4d1;font-size:11px;line-height:1.55}.gp-qa-tier{display:grid;grid-template-columns:18px 1fr;gap:8px;align-items:start;margin:7px 0;color:#b7c4d1;font-size:11px}.gp-qa-dot{width:12px;height:12px;border-radius:50%;margin-top:2px}.gp-qa-dot.high{background:#48df83}.gp-qa-dot.moderate{background:#ffc857}.gp-qa-dot.limited{background:#fb923c}.gp-qa-dot.unverified{background:#ff6678}.gp-no-breaking{padding:18px;border:1px dashed #2b4055;border-radius:10px;color:#b7c4d1;text-align:center}.gp-qa-contradiction{display:inline-block;margin:5px 5px 2px 0;padding:4px 7px;border:1px solid rgba(255,102,120,.55);border-radius:999px;color:#ff8b99;background:rgba(255,102,120,.08);font:800 9px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.04em}.gp-qa-marker{outline:2px solid transparent}.gp-qa-marker:focus{outline-color:#62a0ff;outline-offset:3px}.gp-qa-touch,.gp-command-link,.gp-mapbar button,#gp-minute-refresh,.gp-list-cap{min-height:44px!important}.gp-qa-score-subtext{color:#b7c4d1!important}.gp-qa-deep-link{cursor:pointer}@media(max-width:720px){#gp-how-to-read{padding:8px}#gp-how-to-read .card{padding:14px}.gp-no-breaking{padding:14px}}`;document.head.appendChild(s)}
function dataError(){if(window.DATA||document.getElementById('gp-data-load-error'))return;var host=document.querySelector('.wrap')||document.body;if(!host)return;var e=document.createElement('div');e.id='gp-data-load-error';e.setAttribute('role','alert');e.innerHTML='<strong>LIVE DATA UNAVAILABLE</strong><span>Global Pulse could not load the current snapshot. This is a data-fetch failure, not a stale-data condition.</span><br><button type="button" id="gp-data-retry">Retry snapshot</button>';host.insertBefore(e,host.firstChild);e.querySelector('#gp-data-retry').onclick=function(){location.reload()}}
function onboarding(){if(localStorage.getItem('gp.howToRead.v1')==='1'||document.getElementById('gp-how-to-read'))return;var e=document.createElement('div');e.id='gp-how-to-read';e.setAttribute('role','dialog');e.setAttribute('aria-modal','true');e.setAttribute('aria-labelledby','gp-how-title');e.innerHTML='<div class="card"><h2 id="gp-how-title">How to read Global Pulse</h2><p>Signals show what public evidence is being reported. They are indicators for investigation, not proof or predictions.</p><div class="gp-qa-tier"><i class="gp-qa-dot high"></i><div><b>High confidence</b><br>Multiple strong or independent evidence paths support the assessment.</div></div><div class="gp-qa-tier"><i class="gp-qa-dot moderate"></i><div><b>Moderate confidence</b><br>Useful corroboration exists, but important uncertainty remains.</div></div><div class="gp-qa-tier"><i class="gp-qa-dot limited"></i><div><b>Limited confidence</b><br>Evidence is thin, indirect, or dependent on fewer sources.</div></div><div class="gp-qa-tier"><i class="gp-qa-dot unverified"></i><div><b>Unverified</b><br>A report or claim is visible for investigation but is not established.</div></div><p>Map colors identify signal categories. Confidence is separate from color: border style and opacity indicate evidence strength.</p><button id="gp-how-close" type="button" class="gp-qa-touch">Got it</button></div>';document.body.appendChild(e);var close=function(){localStorage.setItem('gp.howToRead.v1','1');e.remove()};e.querySelector('#gp-how-close').onclick=close;e.addEventListener('click',function(ev){if(ev.target===e)close()})}
function mapA11y(){document.querySelectorAll('.leaflet-marker-icon').forEach(function(m,i){if(m.dataset.gpA11y==='1')return;m.dataset.gpA11y='1';m.setAttribute('role','button');m.setAttribute('tabindex','0');m.setAttribute('aria-label','Global Pulse map signal '+(i+1));m.title='Global Pulse map signal';m.classList.add('gp-qa-marker')})}
function wrapMapRender(){if(typeof window.renderMap!=='function'||window.__GP_MAP_RENDER_WRAPPED__)return;var original=window.renderMap;window.renderMap=function(){try{return original.apply(this,arguments)}catch(e){console.error('Global Pulse map render failed safely',e);var c=document.getElementById('gpMapCount');if(c)c.textContent='Map data unavailable';return null}};window.__GP_MAP_RENDER_WRAPPED__=true}
function contradictionFlags(){document.querySelectorAll('.gp-claim,.gp-ic-grid .item').forEach(function(card){if(card.querySelector('.gp-qa-contradiction'))return;var text=(card.textContent||'').toLowerCase();if(!/\b(disputed|contradict|contradiction|unconfirmed|unverified|denied|conflicting)\b/.test(text))return;var b=document.createElement('span');b.className='gp-qa-contradiction';b.textContent=/unverified|unconfirmed/.test(text)?'UNCONFIRMED':'CONTRADICTED / DISPUTED';card.insertBefore(b,card.firstChild)})}
function emptyBreaking(){var host=document.querySelector('#breaking-intelligence,#breaking-news,#breakingSection,[data-section="breaking"]');if(!host)return;var list=host.querySelector('.stories,.items,[data-breaking-list]');if(!list)return;var visible=[].slice.call(list.children).filter(function(x){return !x.hidden&&!x.matches('button')&&!x.classList.contains('gp-no-breaking')});if(visible.length||list.querySelector('.gp-no-breaking'))return;var e=document.createElement('div');e.className='gp-no-breaking';e.setAttribute('role','status');e.textContent='No breaking events right now. The monitor is still watching public sources.';list.appendChild(e)}
function deepLinks(){document.querySelectorAll('.ccard,.gp-claim,[data-event-id],[data-node-id]').forEach(function(el){if(el.dataset.gpDeepLink==='1')return;var id=el.dataset.eventId||el.dataset.nodeId||el.getAttribute('data-id');if(!id)return;el.dataset.gpDeepLink='1';el.classList.add('gp-qa-deep-link');el.addEventListener('click',function(){history.replaceState(null,'','#'+encodeURIComponent(String(id)))})});var hash=decodeURIComponent(location.hash.replace(/^#/,'')).trim();if(hash&&window.CSS&&CSS.escape)setTimeout(function(){var target=document.querySelector('[data-event-id="'+CSS.escape(hash)+'"],[data-node-id="'+CSS.escape(hash)+'"],[data-id="'+CSS.escape(hash)+'"]');if(target)target.scrollIntoView({block:'center',behavior:'smooth'})},500)}
function observe(){new MutationObserver(function(){wrapMapRender();mapA11y();contradictionFlags();emptyBreaking();deepLinks()}).observe(document.body,{childList:true,subtree:true})}
function boot(){style();onboarding();observe();wrapMapRender();mapA11y();contradictionFlags();emptyBreaking();deepLinks();setTimeout(function(){if(!window.DATA)dataError()},8000)}
window.addEventListener('globalpulse:dataready',function(){var e=document.getElementById('gp-data-load-error');if(e)e.remove();wrapMapRender();mapA11y();contradictionFlags();emptyBreaking();deepLinks()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
