(function(){
  'use strict';
  if(window.__GP_GLOBE_GL__) return;
  window.__GP_GLOBE_GL__=true;
  var DATA_URL='data/snapshot.json', state={data:null,points:[],globe:null,ready:false}, els={};
  function $(id){return document.getElementById(id)}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function num(v){var n=Number(v);return Number.isFinite(n)?n:null}
  function arr(v){return Array.isArray(v)?v:[]}
  function color(m){var t=String(m.type||m.eventType||m.layer||'').toLowerCase();if(/conflict|attack|war|military|terror|battle/.test(t))return '#ff315b';if(/economic|market|finance|trade|energy/.test(t))return '#ffd447';if(/politic|diplom|government/.test(t))return '#b66cff';if(/hazard|quake|storm|climate|environment/.test(t))return '#49ff9a';if(/osint|report|social/.test(t))return '#35f5c0';return '#55b9ff'}
  function normalize(d){var out=[];function add(m,i,prefix){if(!m)return;var lat=num(m.lat!=null?m.lat:m.latitude),lng=num(m.lng!=null?m.lng:(m.lon!=null?m.lon:m.longitude));if(lat===null||lng===null||lat<-90||lat>90||lng<-180||lng>180)return;out.push({id:String(m.id||prefix+'-'+i),lat:lat,lng:lng,title:m.title||m.name||'Intelligence signal',source:m.source||m.sourceLabel||'Global Pulse',type:m.type||m.eventType||m.layer||'signal',region:m.region||'',url:m.url||m.sourceUrl||'',confidence:m.confidence||'',detail:m.detail||m.description||'',color:color(m),size:Math.max(.12,Math.min(.7,Number(m.magnitude||m.intensity||.28)))})}arr(d&&d.markers).forEach(function(m,i){add(m,i,'marker')});var o=d&&d.osintMaps||{};arr(o.gdeltPoints).forEach(function(m,i){add(m,i,'gdelt')});arr(o.reportedAreaPoints).forEach(function(m,i){add(m,i,'reported')});var seen={};return out.filter(function(p){var k=p.id+'|'+p.lat.toFixed(3)+'|'+p.lng.toFixed(3);if(seen[k])return false;seen[k]=1;return true}).slice(0,4000)}
  function inject(){var map=$('map');if(!map||$('gp-globe-wrap'))return;var host=map.parentElement;if(!host)return;var wrap=document.createElement('div');wrap.id='gp-globe-wrap';wrap.className='gp-globe-wrap';wrap.innerHTML='<div class="gp-globe-toolbar"><button type="button" id="gp-globe-toggle">◉ 3D GLOBE</button><button type="button" id="gp-globe-auto">AUTO ROTATE: ON</button><button type="button" id="gp-globe-reset">RESET</button><span id="gp-globe-count">CONNECTING TO GLOBAL GRID…</span></div><div class="gp-globe-stage" id="gp-globe-stage"><div id="gp-globe-canvas" aria-label="Interactive Matrix-style 3D global intelligence globe"></div><div class="gp-globe-hud"><span>GLOBAL PULSE // SIGNAL MATRIX</span><span id="gp-globe-clock">--:--:--</span></div><div class="gp-globe-hint">DRAG · PINCH TO ZOOM · TAP A SIGNAL</div></div><div id="gp-globe-detail" class="gp-globe-detail" hidden></div>';host.insertBefore(wrap,map);els.wrap=wrap;els.stage=$('gp-globe-stage');els.container=$('gp-globe-canvas');els.detail=$('gp-globe-detail');bind()}
  function bind(){$('gp-globe-toggle').addEventListener('click',function(){var active=els.stage.classList.toggle('active');$('map').classList.toggle('gp-2d-hidden',active);this.classList.toggle('active',active);this.textContent=active?'◉ 2D MAP':'◉ 3D GLOBE';if(active){setTimeout(function(){initGlobe();resize()},30);setTimeout(resize,300)}else if(window.gpGlobalMap)setTimeout(function(){window.gpGlobalMap.invalidateSize()},80)});$('gp-globe-auto').addEventListener('click',function(){if(!state.globe)return;var on=!state.globe.controls().autoRotate;state.globe.controls().autoRotate=on;this.textContent='AUTO ROTATE: '+(on?'ON':'OFF');this.classList.toggle('active',on)});$('gp-globe-reset').addEventListener('click',function(){if(state.globe)state.globe.pointOfView({lat:20,lng:10,altitude:2.15},900)});window.addEventListener('resize',resize,{passive:true});document.addEventListener('globalpulse:dataready',load,{passive:true})}
  function initGlobe(){if(state.globe||!window.Globe||!els.container)return;try{var G=window.Globe;state.globe=G(els.container).backgroundColor('#010504').globeImageUrl('https://unpkg.com/three-globe@2.44.0/example/img/earth-night.jpg').bumpImageUrl('https://unpkg.com/three-globe@2.44.0/example/img/earth-topology.png').showAtmosphere(true).atmosphereColor('#49ff9a').atmosphereAltitude(.12).pointsData(state.points).pointLat('lat').pointLng('lng').pointColor('color').pointRadius('size').pointAltitude(.018).pointResolution(8).pointLabel(function(p){return '<div style="font:11px ui-monospace,monospace;max-width:260px;color:#d8ffe9;background:#03100c;border:1px solid #49ff9a;padding:8px;border-radius:6px"><b>'+esc(p.title)+'</b><br>'+esc(p.region||'Global')+' · '+esc(p.source)+'</div>'}).ringsData([]).ringLat('lat').ringLng('lng').ringColor('color').ringMaxRadius(2.8).ringPropagationSpeed(1.4).ringRepeatPeriod(1800).onPointClick(showDetail);state.globe.controls().autoRotate=true;state.globe.controls().autoRotateSpeed=.35;state.globe.controls().enableDamping=true;state.globe.controls().dampingFactor=.08;state.globe.pointOfView({lat:20,lng:10,altitude:2.15},0);updatePoints();state.ready=true;updateCount()}catch(e){state.globe=null;if($('gp-globe-count'))$('gp-globe-count').textContent='3D ENGINE ERROR — 2D MAP AVAILABLE';console.error('Global Pulse Globe.gl error',e)}}
  function updatePoints(){if(!state.globe)return;state.globe.pointsData(state.points);var pulse=state.points.filter(function(p){return /conflict|attack|war|military|terror|battle/i.test(p.type)}).slice(0,180);state.globe.ringsData(pulse);updateCount()}
  function showDetail(p){if(!els.detail)return;els.detail.hidden=false;var link=p.url&&/^https?:\/\//i.test(p.url)?'<a href="'+esc(p.url)+'" target="_blank" rel="noopener noreferrer">OPEN SOURCE ↗</a>':'';els.detail.innerHTML='<strong>'+esc(p.title)+'</strong><div>'+esc(p.region||'Global')+' · '+esc(p.source)+' · '+esc(p.type)+'</div>'+(p.confidence?'<div>Confidence: '+esc(p.confidence)+'</div>':'')+(p.detail?'<div>'+esc(p.detail)+'</div>':'')+link}
  function updateCount(){var c=$('gp-globe-count');if(c)c.textContent=(state.points.length||0)+' SIGNALS · '+(state.ready?'DATA LINK: ONLINE':'DATA LINK: LOADING')}
  function resize(){if(state.globe&&els.stage){var r=els.stage.getBoundingClientRect();state.globe.width(Math.max(280,r.width||280)).height(Math.max(280,r.height||280))}}
  async function load(){try{var d=window.DATA&&typeof window.DATA==='object'?window.DATA:null;if(!d){var r=await fetch(DATA_URL+'?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);d=await r.json()}state.data=d;state.points=normalize(d);updatePoints();updateCount()}catch(e){console.warn('Global Pulse 3D data load failed',e)}}
  function boot(){inject();load()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
  window.addEventListener('globalpulse:dataready',function(){load();if(els.stage&&els.stage.classList.contains('active'))setTimeout(initGlobe,30)});
  setInterval(function(){var c=$('gp-globe-clock');if(c)c.textContent=new Date().toLocaleTimeString([], {hour12:false})},1000);
})();
