/* Global Pulse V2.6 repairs: one conflict dialog, visible V5 trend, no duplicate map popups. */
(function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const n=v=>Number.isFinite(Number(v))?Number(v):0;
  const ago=v=>{const t=Date.parse(v||'');if(!Number.isFinite(t))return '';const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<1?'just now':m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
  function css(){if(document.getElementById('gp-v26-css'))return;const s=document.createElement('style');s.id='gp-v26-css';s.textContent='.gp-v26-note{font-size:9px;color:var(--muted);margin-top:6px}.gp-v26-modal{position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:14px;background:rgba(0,0,0,.78);backdrop-filter:blur(7px)}.gp-v26-dialog{position:relative;width:min(700px,100%);max-height:88vh;overflow:auto;background:#0b131d;color:var(--text);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 24px 90px rgba(0,0,0,.6)}.gp-v26-dialog h2{margin:0 45px 5px 0;font-size:19px}.gp-v26-close{position:absolute;right:10px;top:10px;width:35px;height:35px;border-radius:50%;font-size:20px}.gp-v26-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:12px 0}.gp-v26-metric{background:var(--panel2);border:1px solid var(--line);border-radius:9px;padding:9px}.gp-v26-metric span,.gp-v26-metric strong{display:block}.gp-v26-metric span{font-size:8px;color:var(--muted)}.gp-v26-metric strong{font-size:15px;margin-top:4px}.gp-v26-track{height:7px;background:#172434;border-radius:99px;overflow:hidden;margin:10px 0 14px}.gp-v26-track i{display:block;height:100%;background:#ff6678;border-radius:inherit}.gp-v26-source{padding:10px 0;border-top:1px solid var(--line)}.gp-v26-source strong{display:block;font-size:11px;line-height:1.35}.gp-v26-source small{display:block;color:var(--muted);font-size:9px;margin-top:4px}.gp-v26-source a{display:inline-block;margin-top:7px;color:var(--blue);font-size:9px;font-weight:800;text-decoration:none}@media(max-width:720px){.gp-v26-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}';document.head.appendChild(s)}
  function modal(c,d){
    document.querySelectorAll('.gp-conflict-modal,.gp-v26-modal').forEach(x=>x.remove());
    const score=Math.max(0,Math.min(100,n(c.activityScore??c.score??c.tension??c.priority)));
    const stories=[...(Array.isArray(d.stories)?d.stories:[])]; const words=String([c.name,c.title,c.region,c.location,c.id].filter(Boolean).join(' ')).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2&&!/^(the|and|for|with|from|war|conflict|risk|front|security|regional|civil|internal|armed|groups|pressure|spillover|political|residual|instability|insurgency|criminal|flashpoint|militia)$/.test(x));
    const seen=new Set(); const sources=stories.map(s=>{const text=String([s.title,s.summary,s.tag,s.category,s.sourceLabel,s.source].filter(Boolean).join(' ')).toLowerCase();const hits=words.filter(w=>text.includes(w)).length;const url=String(s.source||s.url||'');return {s,hits,url}}).filter(x=>x.hits&&/^https?:\/\//i.test(x.url)).sort((a,b)=>b.hits-a.hits||Date.parse(b.s.time||'')-Date.parse(a.s.time||'')).filter(x=>{if(seen.has(x.url))return false;seen.add(x.url);return true}).slice(0,5);
    const overlay=document.createElement('div');overlay.className='gp-v26-modal';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');
    const box=document.createElement('div');box.className='gp-v26-dialog';
    const close=document.createElement('button');close.className='gp-v26-close';close.type='button';close.textContent='×';close.setAttribute('aria-label','Close conflict details');box.appendChild(close);
    const h=document.createElement('h2');h.textContent=c.name||c.title||c.conflict||'Active Conflict';box.appendChild(h);
    const sub=document.createElement('div');sub.className='muted';sub.textContent=(c.region||c.location||'Global')+' · '+(c.status||c.escalation||c.severity||'MONITOR');box.appendChild(sub);
    const metrics=document.createElement('div');metrics.className='gp-v26-metrics';[['Activity score',Math.round(score)],['Signal',c.status||c.escalation||c.severity||'MONITOR'],['Confidence',c.confidence||'OPEN-DATA'],['Updated',ago(c.updatedAt||d.updatedAt)||'current']].forEach(([a,b])=>{const m=document.createElement('div');m.className='gp-v26-metric';m.innerHTML='<span>'+esc(a)+'</span><strong>'+esc(b)+'</strong>';metrics.appendChild(m)});box.appendChild(metrics);
    const track=document.createElement('div');track.className='gp-v26-track';track.innerHTML='<i style="width:'+score+'%"></i>';box.appendChild(track);
    const p=document.createElement('p');p.className='muted';p.textContent=c.recent||'Score reflects the current conflict activity signal in the snapshot.';box.appendChild(p);
    const sh=document.createElement('h3');sh.textContent='Latest supporting sources';sh.style.margin='14px 0 4px';box.appendChild(sh);
    const list=document.createElement('div');if(!sources.length){list.innerHTML='<div class="muted">No directly matched source links are available in the current snapshot.</div>'}else sources.forEach(x=>{const row=document.createElement('div');row.className='gp-v26-source';const t=document.createElement('strong');t.textContent=x.s.title||'Public report';row.appendChild(t);const meta=document.createElement('small');meta.textContent=(x.s.sourceLabel||x.s.sourceType||'Public source')+' · '+ago(x.s.time||x.s.published_date||x.s.publishedAt);row.appendChild(meta);const a=document.createElement('a');a.href=x.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Read source report ↗';row.appendChild(a);list.appendChild(row)});box.appendChild(list);overlay.appendChild(box);document.body.appendChild(overlay);
    const done=()=>{overlay.remove();document.removeEventListener('keydown',key)};const key=e=>{if(e.key==='Escape')done()};close.onclick=done;overlay.onclick=e=>{if(e.target===overlay)done()};document.addEventListener('keydown',key);close.focus();
  }
  async function trend(){
    const panel=document.getElementById('gp-v22-monitor');if(!panel)return;
    try{const r=await fetch('data/history.json?t='+Date.now(),{cache:'no-store'});const h=await r.json();const d=window.DATA||{};const v=Number(d.scoreVersion)||5;const pts=(Array.isArray(h)?h:[]).filter(x=>Number(x?.scoreVersion||0)===v&&Number.isFinite(Number(x?.tension))).slice(-48);const current={updatedAt:d.updatedAt,tension:n(d.tension),scoreVersion:v};if(!pts.length||pts[pts.length-1].updatedAt!==current.updatedAt)pts.push(current);const box=panel.querySelector('.gp-v22-chart');if(!box)return;const vals=pts.map(x=>n(x.tension));const w=760,hh=170,p=18,min=Math.max(0,Math.min(...vals)-5),max=Math.min(100,Math.max(...vals)+5),range=Math.max(1,max-min);const xy=(val,i)=>[p+(i/Math.max(1,vals.length-1))*(w-p*2),hh-p-((val-min)/range)*(hh-p*2)];let graphic='';if(vals.length===1){const y=xy(vals[0],0)[1];graphic='<line x1="18" y1="'+y.toFixed(1)+'" x2="742" y2="'+y.toFixed(1)+'" stroke="#62a0ff" stroke-width="3"/><circle cx="380" cy="'+y.toFixed(1)+'" r="5" fill="#ffc857"/>'}else{const path=vals.map((x,i)=>xy(x,i).map(a=>a.toFixed(1)).join(',')).join(' ');const last=xy(vals[vals.length-1],vals.length-1);graphic='<polyline points="'+path+'" fill="none" stroke="#62a0ff" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/><circle cx="'+last[0].toFixed(1)+'" cy="'+last[1].toFixed(1)+'" r="4" fill="#ffc857"/>'}box.querySelector('svg')?.remove();box.insertAdjacentHTML('beforeend','<svg viewBox="0 0 '+w+' '+hh+'" role="img" aria-label="Global tension trend"><line x1="18" y1="152" x2="742" y2="152" stroke="#1b2b3d"/><line x1="18" y1="18" x2="18" y2="152" stroke="#1b2b3d"/>'+graphic+'<text x="24" y="30" class="gp-v22-axis">'+Math.round(max)+'</text><text x="24" y="148" class="gp-v22-axis">'+Math.round(min)+'</text><text x="680" y="30" class="gp-v22-axis">'+Math.round(vals[vals.length-1])+'</text></svg>');const note=box.querySelector('.gp-v26-note');if(note)note.textContent=vals.length<2?'1 V5 snapshot · history will build automatically every refresh.':vals.length+' V5 snapshots · updated every refresh.';else box.insertAdjacentHTML('beforeend','<div class="gp-v26-note">'+(vals.length<2?'1 V5 snapshot · history will build automatically every refresh.':vals.length+' V5 snapshots · updated every refresh.')+'</div>');
    }catch(e){}
  }
  function start(){css();trend();setInterval(trend,5000);document.addEventListener('globalpulse:dataready',trend);document.addEventListener('click',e=>{const card=e.target.closest&&e.target.closest('#conflictList .ccard');if(!card)return;e.preventDefault();e.stopImmediatePropagation();const name=card.querySelector('h3')?.textContent?.trim();const d=window.DATA||{};const c=(d.conflicts||[]).find(x=>(x.name||x.title||x.conflict)===name);if(c)modal(c,d)},true);document.addEventListener('keydown',e=>{const card=e.target.closest&&e.target.closest('#conflictList .ccard');if(!card||!(e.key==='Enter'||e.key===' '))return;e.preventDefault();e.stopImmediatePropagation();const name=card.querySelector('h3')?.textContent?.trim();const d=window.DATA||{};const c=(d.conflicts||[]).find(x=>(x.name||x.title||x.conflict)===name);if(c)modal(c,d)},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
