/* Global Pulse V2.4 — climate, disaster, food and health pressure intelligence. */
(function(){
  'use strict';
  const esc=v=>String(v==null?'':v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const n=v=>Number.isFinite(Number(v))?Number(v):0;
  const clean=v=>{try{const u=new URL(String(v||'').trim(),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const articleUrl=a=>clean(a&&(a.url||a.source||a.original_link||a.source_url||a.link||a.sourceUrl||a.href));
  const climateRx={
    'Drought & water':/drought|water shortage|water stress|reservoir|water supply/i,
    'Floods & storms':/flood|flooding|cyclone|hurricane|typhoon|storm|landslide|glacier/i,
    'Heat & fire':/heatwave|heat wave|extreme heat|wildfire|forest fire|extreme cold/i,
    'Food security':/famine|food insecurity|food crisis|hunger|crop failure|harvest failure/i,
    'Health outbreaks':/epidemic|outbreak|disease|cholera|malaria|avian flu|pandemic/i
  };
  function metricFromStories(stories,rx){const rows=stories.filter(a=>rx.test(String([a.title,a.summary,a.tag,a.sourceLabel,a.sourceType].join(' '))));return Math.min(100,Math.round(Math.min(1,rows.length/18)*100));}
  function addDriverBar(d){
    const box=document.querySelector('#breakdown');if(!box)return;
    let row=box.querySelector('[data-gp-climate-driver]');
    if(!row){row=document.createElement('div');row.className='bar';row.dataset.gpClimateDriver='true';row.innerHTML='<span>Climate &amp; humanitarian</span><div class="track"><div class="fill"></div></div><b>0</b>';box.appendChild(row)}
    const value=Math.max(0,Math.min(100,n((d.breakdownScores||{})['Climate & humanitarian pressure'])));
    row.querySelector('.fill').style.width=value+'%';row.querySelector('b').textContent=Math.round(value);
  }
  function css(){if(document.getElementById('gp-v24-css'))return;const s=document.createElement('style');s.id='gp-v24-css';s.textContent='.gp-v24-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}.gp-v24-card{background:var(--panel2);border:1px solid var(--line);border-radius:11px;padding:11px}.gp-v24-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.gp-v24-metric{border:1px solid var(--line);border-radius:9px;padding:9px;min-width:0}.gp-v24-metric b{display:block;font-size:18px}.gp-v24-metric span{display:block;color:var(--muted);font-size:9px;line-height:1.25;margin-top:4px}.gp-v24-bar{height:7px;background:#142231;border-radius:99px;overflow:hidden;margin-top:6px}.gp-v24-fill{height:100%;background:linear-gradient(90deg,var(--green),var(--amber),var(--red))}.gp-v24-list{display:grid;gap:7px;max-height:310px;overflow:auto}.gp-v24-story{padding:8px;border-bottom:1px solid var(--line)}.gp-v24-story:last-child{border-bottom:0}.gp-v24-story a{font-size:10px;font-weight:800;color:var(--text)}.gp-v24-story small{display:block;color:var(--muted);font-size:9px;margin-top:3px}.gp-v24-note{font-size:9px;color:var(--muted);line-height:1.5;margin-top:9px}.gp-v24-source{font-size:10px;padding:6px 0;border-bottom:1px solid var(--line)}.gp-v24-source:last-child{border-bottom:0}.gp-v24-source b{color:var(--green)}@media(max-width:800px){.gp-v24-grid{grid-template-columns:1fr}.gp-v24-metrics{grid-template-columns:repeat(2,1fr)}.gp-v24-metric:last-child{grid-column:span 2}}';document.head.appendChild(s)}
  function render(d){css();addDriverBar(d);const wrap=document.querySelector('.wrap');if(!wrap)return;let sec=document.getElementById('gp-v24-climate');if(!sec){sec=document.createElement('section');sec.id='gp-v24-climate';sec.className='panel wide';const anchor=document.getElementById('gp-v23-monitor')||document.getElementById('gp-v22-monitor')||document.getElementById('conflictSection');wrap.insertBefore(sec,anchor?anchor.nextSibling:null)}
    const stories=Array.isArray(d.stories)?d.stories:[];const cm=d.climatePressure||{};const score=n((d.breakdownScores||{})['Climate & humanitarian pressure']);
    const metrics=Object.keys(climateRx).map(k=>({name:k,value:n(cm[k]??metricFromStories(stories,climateRx[k]))}));
    const linked=stories.filter(a=>articleUrl(a)&&Object.values(climateRx).some(rx=>rx.test(String([a.title,a.summary,a.tag,a.sourceLabel,a.sourceType].join(' ')))).slice(0,8);
    sec.innerHTML='<div class="section-head"><div><h2>V2.4 · CLIMATE &amp; HUMANITARIAN PRESSURE</h2><div class="muted">A live risk layer for drought, floods, extreme heat/fire, food insecurity and health outbreaks.</div></div><span class="gp-v23-badge '+(score>=70?'gp-v23-high':score>=45?'gp-v23-watch':'gp-v23-stable')+'">'+(score>=70?'HIGH':score>=45?'ELEVATED':'WATCH')+'</span></div><div class="gp-v24-metrics">'+metrics.map(m=>'<div class="gp-v24-metric"><b>'+Math.round(m.value)+'</b><span>'+esc(m.name)+'</span><div class="gp-v24-bar"><div class="gp-v24-fill" style="width:'+Math.max(0,Math.min(100,m.value))+'%"></div></div></div>').join('')+'</div><div class="gp-v24-grid" style="margin-top:12px"><div class="gp-v24-card"><div class="muted" style="margin-bottom:7px">LATEST CLIMATE / DISASTER REPORTING</div><div class="gp-v24-list">'+(linked.length?linked.map(a=>'<div class="gp-v24-story"><a href="'+esc(articleUrl(a))+'" target="_blank" rel="noopener noreferrer">'+esc(a.title||'Untitled report')+'</a><small>'+esc(a.sourceLabel||a.sourceName||a.sourceType||'Public source')+'</small></div>').join(''):'<div class="muted">No linked climate or humanitarian stories in the current snapshot.</div>')+'</div></div><div class="gp-v24-card"><div class="muted" style="margin-bottom:7px">DATA SOURCES</div><div class="gp-v24-source"><b>GDACS</b> — disaster alerts and impact signals</div><div class="gp-v24-source"><b>FAO GIEWS</b> — food and agricultural early warning</div><div class="gp-v24-source"><b>GDELT</b> — near-live global reporting signals</div><div class="gp-v24-source"><b>Relief / humanitarian reporting</b> — crisis context where available</div><div class="gp-v24-note">Climate pressure is deliberately separate from conflict and economics but can amplify both through water stress, food prices, displacement, infrastructure damage and public-health pressure.</div></div></div><div class="gp-v24-note">Method: the index combines current open-source reporting and disaster-alert signals. It is an analytical monitoring signal, not an official climate index, medical diagnosis, famine declaration or weather forecast. Official hazard and food-security systems should be consulted for decisions.</div>';
  }
  function boot(){if(window.DATA)render(window.DATA)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
  document.addEventListener('globalpulse:dataready',boot);setInterval(boot,60000);
})();
