/* Global Pulse — canonical UI core. Consolidates the durable V2.2–V2.7 UI behaviors. */
(function(){
'use strict';
if(window.__gpCoreInstalled)return;window.__gpCoreInstalled=true;
const A=v=>Array.isArray(v)?v:[];
const N=v=>Number.isFinite(Number(v))?Number(v):0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
function css(){if(document.getElementById('gp-core-css'))return;const s=document.createElement('style');s.id='gp-core-css';s.textContent=`
:root{--gp-mono:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace}.gp-core-mono,.score,.gp-statusbar,.gp-scrubber,.gp-map-legend{font-variant-numeric:tabular-nums;font-family:var(--gp-mono)}
.gp-statusbar{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:7px 10px;border:1px solid var(--line);border-radius:9px;background:var(--panel2);font-size:9px;color:var(--muted)}.gp-status-live i{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--green);margin-right:5px}.gp-status-live.stale i{background:var(--amber)}
.gp-skeleton{position:relative;overflow:hidden;color:transparent!important;background:#101b27!important;border-radius:8px;min-height:24px}.gp-skeleton:after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.08),transparent);animation:gp-shimmer 1.2s infinite}@keyframes gp-shimmer{to{transform:translateX(100%)}}
.gp-map-legend{display:flex;gap:7px;flex-wrap:wrap;margin:7px 0;font-size:9px}.gp-map-legend span{padding:4px 7px;border:1px solid var(--line);border-radius:999px;background:var(--panel2)}.gp-map-legend i{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:4px}
.gp-scrubber{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:7px 0}.gp-scrubber input{flex:1;min-width:120px}.gp-scrubber button{min-height:30px;padding:5px 8px;font-size:9px}.gp-scrub-date{min-width:130px;color:var(--muted)}.gp-refresh-change{animation:gp-pulse .65s ease}@keyframes gp-pulse{50%{transform:scale(1.015);filter:brightness(1.2)}}
.gp-confidence-high{border-style:solid!important;opacity:1}.gp-confidence-moderate{border-style:dashed!important}.gp-confidence-limited{border-style:dotted!important;opacity:.82}.gp-confidence-unverified{border-style:dashed!important;opacity:.58}.gp-collapse-toggle{width:100%;text-align:left;padding:7px 9px;margin-top:7px;font-size:10px}.gp-collapse-body{display:none;margin-top:7px}.gp-collapse-body.open{display:block}.gp-list-cap{display:block;width:100%;margin:9px 0 0;padding:8px;border:1px solid var(--line);border-radius:8px;background:var(--panel2);color:var(--text);font-size:10px;font-weight:800}.gp-health-failover{color:var(--amber)}
`;document.head.appendChild(s)}
function linkTokens(){if(document.getElementById('gp-token-link'))return;const l=document.createElement('link');l.id='gp-token-link';l.rel='stylesheet';l.href='global_pulse_tokens.css?v=1';document.head.appendChild(l)}
function statusBar(d){const wrap=document.querySelector('.wrap');if(!wrap)return;let b=document.getElementById('gp-core-status');if(!b){b=document.createElement('div');b.id='gp-core-status';b.className='gp-statusbar';wrap.insertBefore(b,wrap.firstElementChild)}const fh=d?.failoverState||{},total=N(fh.total||fh.feedsChecked||A(d?.sourceHealth).length),down=N(fh.down||fh.failed||fh.failedSources?.length),last=d?.lastSuccessfulRefresh||d?.lastSuccessAt||d?.pipeline?.lastSuccessfulRefresh||d?.updatedAt;const stale=last&&Date.now()-Date.parse(last)>15*60000;b.innerHTML='<span class="gp-status-live '+(stale?'stale':'')+'"><i></i><strong>'+(stale?'STALE DATA':'OPEN-DATA MONITOR')+'</strong></span><span>'+(total?Math.max(0,total-down)+' of '+total+' feeds healthy · ':'')+'last successful refresh: '+esc(last?new Date(last).toLocaleString():'unknown')+'</span>'}
function skeleton(){const score=document.getElementById('globalScore'),map=document.getElementById('map');if(score&&!window.DATA)score.classList.add('gp-skeleton');if(map&&!window.DATA)map.classList.add('gp-skeleton')}
function refreshPulse(){['#globalScore','#tensionScore','#globalDelta'].forEach(sel=>{const e=document.querySelector(sel);if(!e)return;e.classList.remove('gp-refresh-change');void e.offsetWidth;e.classList.add('gp-refresh-change')})}
function addLegend(){const map=document.getElementById('map');if(!map||document.getElementById('gp-map-legend'))return;const l=document.createElement('div');l.id='gp-map-legend';l.className='gp-map-legend';const colors=[['#ff6678','Conflict'],['#fb923c','Energy'],['#ffc857','Economic'],['#62a0ff','Strategic'],['#aa8df7','Political'],['#48df83','Resource']];l.innerHTML=colors.map(x=>'<span><i style="background:'+x[0]+'"></i>'+x[1]+'</span>').join('');map.parentElement.insertBefore(l,map)}
function confidenceClass(m){const c=String(m?.confidence||'').toLowerCase();return c.includes('high')?'gp-confidence-high':c.includes('moderate')?'gp-confidence-moderate':c.includes('limited')?'gp-confidence-limited':'gp-confidence-unverified'}
function scrubMap(date){const d=window.DATA;if(!d||typeof window.renderMap!=='function')return;const original=A(d.markers),cut=Date.parse(date);d.markers=original.filter(m=>{const t=Date.parse(m?.timestamp||m?.time||m?.date||m?.updatedAt||'');return !Number.isFinite(t)||t<=cut});try{window.renderMap()}finally{d.markers=original};document.querySelectorAll('#map .leaflet-marker-icon').forEach((el,i)=>{if(original[i])el.classList.add(confidenceClass(original[i]))})}
async function addScrubber(){const map=document.getElementById('map');if(!map||document.getElementById('gp-scrubber'))return;try{const r=await fetch('data/history.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);const h=await r.json(),rows=A(h).filter(x=>x&&x.updatedAt);if(!rows.length)return;const box=document.createElement('div');box.id='gp-scrubber';box.className='gp-scrubber';box.innerHTML='<button type="button" id="gp-scrub-play">▶ Play</button><input id="gp-scrub-range" type="range" min="0" max="'+(rows.length-1)+'" value="'+(rows.length-1)+'"><span id="gp-scrub-date" class="gp-scrub-date"></span>';map.parentElement.insertBefore(box,map);const range=box.querySelector('#gp-scrub-range'),label=box.querySelector('#gp-scrub-date'),set=i=>{const row=rows[Math.max(0,Math.min(rows.length-1,Number(i)))];range.value=i;label.textContent=new Date(row.updatedAt).toLocaleString();scrubMap(row.updatedAt)};range.oninput=()=>set(range.value);set(rows.length-1);let timer=null;box.querySelector('#gp-scrub-play').onclick=()=>{if(timer){clearInterval(timer);timer=null;box.querySelector('#gp-scrub-play').textContent='▶ Play';return}box.querySelector('#gp-scrub-play').textContent='⏸ Pause';let i=Number(range.value);timer=setInterval(()=>{i++;if(i>=rows.length){clearInterval(timer);timer=null;box.querySelector('#gp-scrub-play').textContent='▶ Play';return}set(i)},900)}}catch(e){}}
function persistFilter(){if(window.__gpFilterWired)return;window.__gpFilterWired=true;document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('.filter,[data-map-filter],#mapFilters button');if(!b)return;localStorage.setItem('gp.mapFilter',String(b.dataset.filter||b.dataset.mapFilter||b.textContent||'All').trim().toLowerCase())},true);const saved=localStorage.getItem('gp.mapFilter');if(saved)setTimeout(()=>{const b=[...document.querySelectorAll('.filter,[data-map-filter],#mapFilters button')].find(x=>String(x.dataset.filter||x.dataset.mapFilter||x.textContent||'').trim().toLowerCase()===saved);if(b)b.click()},100)}
function collapseLongText(){document.querySelectorAll('.ccard,.story,.item').forEach(card=>{if(card.dataset.gpCollapse==='1')return;const text=[...card.querySelectorAll('p,.detail,.description,.why-matters,.summary')].find(x=>x.textContent.trim().length>220);if(!text)return;card.dataset.gpCollapse='1';const body=document.createElement('div');body.className='gp-collapse-body';body.append(...[...text.childNodes]);text.textContent='';text.appendChild(body);const btn=document.createElement('button');btn.type='button';btn.className='gp-collapse-toggle';btn.textContent='Why This Matters / details ▾';btn.onclick=()=>{body.classList.toggle('open');btn.textContent=body.classList.contains('open')?'Hide details ▴':'Why This Matters / details ▾'};text.parentNode.insertBefore(btn,text)})}
function capLists(){document.querySelectorAll('.stories,.items,.conflict-list').forEach(list=>{if(list.dataset.gpCap==='1')return;const kids=[...list.children].filter(x=>!x.matches('button,.gp-list-cap'));if(kids.length<=5)return;list.dataset.gpCap='1';kids.slice(5).forEach(x=>x.hidden=true);const b=document.createElement('button');b.type='button';b.className='gp-list-cap';b.textContent='See more ('+(kids.length-5)+') ↓';b.onclick=()=>{const open=b.dataset.open==='1';kids.slice(5).forEach(x=>x.hidden=open);b.dataset.open=open?'0':'1';b.textContent=open?'See more ('+(kids.length-5)+') ↓':'Show less ↑'};list.appendChild(b)})}
function health(d){const sh=A(d?.sourceHealth);if(!sh.length)return;let p=document.getElementById('gp-health-failover');if(!p){p=document.createElement('div');p.id='gp-health-failover';p.className='gp-health-failover gp-core-mono';const anchor=document.getElementById('gp-core-status')||document.querySelector('.wrap');if(anchor)anchor.appendChild(p)}const down=sh.filter(x=>['failed','error','offline'].includes(String(x.status||'').toLowerCase())).length;p.textContent=down+' of '+sh.length+' feeds down'}
function newsFallback(){if(window.__gpNewsFallback)return;window.__gpNewsFallback=true;fetch('data/live_articles.json?t='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{if(!d)return;window.LIVE_ARTICLES=d;const target=window.DATA||{},incoming=A(d.articles),seen=new Set(A(target.stories).map(x=>x.url||x.source));target.stories=A(target.stories).concat(incoming.filter(x=>x.url&&!seen.has(x.url)).map(x=>({title:x.title,url:x.url,source:x.source||x.source_name||'Live source',sourceLabel:x.source||x.source_name||'Live source',published_date:x.published_date,time:x.published_date,summary:x.summary_snippet||'',sourceType:x.sourceType||x.source_type||'live-rss'}))).sort((a,b)=>(Date.parse(b.time||b.published_date)||0)-(Date.parse(a.time||a.published_date)||0)).slice(0,1000);if(typeof window.renderStories==='function')window.renderStories();document.dispatchEvent(new CustomEvent('globalpulse:live-news-ready'))}).catch(()=>{})}
function apply(d){if(!d)return;statusBar(d);health(d);addLegend();addScrubber();persistFilter();collapseLongText();capLists();refreshPulse();const map=document.getElementById('map'),score=document.getElementById('globalScore');if(map)map.classList.remove('gp-skeleton');if(score)score.classList.remove('gp-skeleton')}
async function boot(){css();linkTokens();skeleton();newsFallback();if(window.DATA)apply(window.DATA);else setTimeout(()=>{if(window.DATA)apply(window.DATA)},1000)}
window.addEventListener('globalpulse:dataready',()=>{apply(window.DATA||{});newsFallback()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();setInterval(()=>{if(window.DATA)apply(window.DATA)},30000);
})();
