#!/usr/bin/env python3
"""Install resilient map-v3 enhancements.

Map rendering stays keyless. Google Maps is used only as an external place
link; Google-hosted place photos are never scraped or cached. If an upstream
source supplies a legitimate image URL, it is shown in the marker popup.
"""
from pathlib import Path

INDEX=Path(__file__).resolve().parent/'index.html'
MARK='<!-- GP-MAP-V3-ENHANCEMENTS -->'
CSS='''<style id="gp-map-v3-css">.gp-map-v3{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin:-2px 0 9px}.gp-map-v3 button{font-size:10px;min-height:34px;padding:7px 9px}.gp-map-v3 button.active{border-color:var(--amber);color:var(--amber);background:rgba(255,200,87,.1)}.gp-region-stats{display:flex;gap:7px;overflow:auto;margin:0 0 9px;padding-bottom:2px}.gp-region-stat{min-width:110px;padding:8px 9px;border:1px solid var(--line);border-radius:9px;background:#08131e}.gp-region-stat b{display:block;font-size:16px}.gp-region-stat span{font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em}.gp-heat-legend{font-size:9px;color:var(--muted);margin:0 0 8px}.gp-map-media{display:block;width:100%;max-height:170px;object-fit:cover;border-radius:8px;margin:7px 0 8px;border:1px solid #1b2b3d;background:#07101a}.gp-map-media-credit{font-size:9px;color:#91a4b8;margin-top:-4px;margin-bottom:6px}.gp-map-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.gp-map-action{display:inline-block;padding:6px 8px;border:1px solid #1b2b3d;border-radius:7px;background:#09121c;color:#62a0ff;font-size:10px;font-weight:800}.gp-map-action:hover{background:#102033}.gp-map-photo-note{font-size:9px;color:#91a4b8;margin-top:6px;line-height:1.35}</style>'''
JS=r'''<script id="gp-map-v3-js">(function(){"use strict";let installed=false,heat=null,heatOn=false;const esc=v=>String(v??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]||m));const regionOf=m=>String(m?.region||m?.country||"Other").trim()||"Other";const valid=m=>Number.isFinite(Number(m?.lat??m?.latitude))&&Number.isFinite(Number(m?.lng??m?.lon??m?.longitude));const validUrl=v=>{try{const u=new URL(String(v||""));return /^https?:$/.test(u.protocol)}catch(_){return false}};const photoOf=m=>{for(const k of ["imageUrl","image_url","image","thumbnailUrl","thumbnail","photoUrl","photo_url","mediaUrl","media_url"]){if(validUrl(m?.[k]))return String(m[k])}if(Array.isArray(m?.images))for(const v of m.images)if(validUrl(v))return String(v);return ""};const mapsUrl=(m,lat,lng)=>{for(const k of ["googleMapsUrl","google_maps_url","mapsUrl","maps_url"]){if(validUrl(m?.[k]))return String(m[k])}return "https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(lat+","+lng)};const markerFor=(lat,lng)=>{const ms=Array.isArray(window.DATA?.markers)?window.DATA.markers:[];let best=null,dist=Infinity;for(const m of ms){const a=Number(m?.lat??m?.latitude),b=Number(m?.lng??m?.lon??m?.longitude);if(!Number.isFinite(a)||!Number.isFinite(b))continue;const d=Math.abs(a-lat)+Math.abs(b-lng);if(d<dist){dist=d;best=m}}return best&&dist<0.0001?best:null};
function points(){return(Array.isArray(DATA.markers)?DATA.markers:[]).filter(valid).map(m=>[Number(m.lat??m.latitude),Number(m.lng??m.lon??m.longitude),Math.max(.2,Math.min(1.5,Number(m.importance||1))),m])}
function addBaseSwitch(map){if(!window.L||map.__gpBaseSwitch)return;let dark=null;map.eachLayer(x=>{if(!dark&&x instanceof L.TileLayer)dark=x});if(!dark)return;const street=L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"});L.control.layers({"Dark intelligence":dark,"OpenStreetMap":street},null,{collapsed:true,position:"topright"}).addTo(map);map.__gpBaseSwitch=true}
function drawHeat(){if(!window.gpGlobalMap)return;if(heat){window.gpGlobalMap.removeLayer(heat);heat=null}if(!heatOn)return;const pts=points();if(window.L.heatLayer){heat=L.heatLayer(pts.map(x=>[x[0],x[1],x[2]]),{radius:28,blur:24,maxZoom:7,max:1.5});heat.addTo(window.gpGlobalMap)}else{heat=L.layerGroup();const seen=new Map();pts.forEach(x=>{const k=Math.round(x[0])+","+Math.round(x[1]);seen.set(k,(seen.get(k)||0)+x[2])});seen.forEach((v,k)=>{const[a,b]=k.split(',').map(Number);L.circle([a,b],{radius:Math.min(120000,18000*Math.sqrt(v)),color:'#ffc857',weight:1,fillOpacity:.12}).addTo(heat)});heat.addTo(window.gpGlobalMap)}}
function regionStats(stats){const counts={};points().forEach(x=>{const r=regionOf(x[3]);counts[r]=(counts[r]||0)+1});const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8);stats.innerHTML=top.map(([r,n])=>'<div class="gp-region-stat"><b>'+n+'</b><span>'+esc(r)+'</span></div>').join('');document.getElementById('gpRegionTotal').textContent=Object.values(counts).reduce((a,b)=>a+b,0)+' mapped signals'}
function installPopupMedia(map){map.on("popupopen",e=>{const src=e.popup&&e.popup._source;if(!src)return;const ll=src.getLatLng(),m=markerFor(ll.lat,ll.lng);if(!m)return;const el=e.popup.getElement();if(!el)return;const content=el.querySelector(".leaflet-popup-content");if(!content||content.querySelector(".gp-map-actions"))return;const photo=photoOf(m),mu=mapsUrl(m,ll.lat,ll.lng),source=String(m.sourceUrl||m.url||"");let html="";if(photo)html+='<a href="'+esc(photo)+'" target="_blank" rel="noopener noreferrer"><img class="gp-map-media" src="'+esc(photo)+'" loading="lazy" referrerpolicy="no-referrer" alt="Source image"></a><div class="gp-map-media-credit">Image supplied by the event/source feed.</div>';html+='<div class="gp-map-actions"><a class="gp-map-action" href="'+esc(mu)+'" target="_blank" rel="noopener noreferrer">Open in Google Maps ↗</a>';if(source&&validUrl(source))html+='<a class="gp-map-action" href="'+esc(source)+'" target="_blank" rel="noopener noreferrer">Open source ↗</a>';html+='</div>';if(!photo)html+='<div class="gp-map-photo-note">No source image was supplied for this signal. Google Maps may have place imagery available after opening the location.</div>';content.insertAdjacentHTML("beforeend",html)})}
function boot(){if(installed||!window.L||!window.DATA||!document.querySelector("#map"))return;const bar=document.querySelector(".gp-mapbar");if(!bar)return;installed=true;const row=document.createElement("div");row.className="gp-map-v3";row.innerHTML='<button type="button" id="gpHeatToggle">INTENSITY OFF</button><button type="button" id="gpFitAll">FIT ALL</button><span class="gp-map-count" id="gpRegionTotal"></span>';bar.parentElement.insertBefore(row,bar.nextSibling);const stats=document.createElement("div");stats.className="gp-region-stats";bar.parentElement.insertBefore(stats,row.nextSibling);const legend=document.createElement("div");legend.className="gp-heat-legend";legend.textContent="Intensity = concentration of sourced map signals; not a prediction or casualty measure.";bar.parentElement.insertBefore(legend,stats.nextSibling);addBaseSwitch(window.gpGlobalMap);installPopupMedia(window.gpGlobalMap);document.getElementById("gpHeatToggle").onclick=()=>{heatOn=!heatOn;document.getElementById("gpHeatToggle").textContent=heatOn?"INTENSITY ON":"INTENSITY OFF";document.getElementById("gpHeatToggle").classList.toggle("active",heatOn);drawHeat()};document.getElementById("gpFitAll").onclick=()=>{const p=points();if(p.length&&window.gpGlobalMap)window.gpGlobalMap.fitBounds(L.latLngBounds(p.map(x=>[x[0],x[1]])).pad(.06),{maxZoom:5})};regionStats(stats);const old=window.renderMap;if(typeof old==='function')window.renderMap=function(){old();setTimeout(()=>{regionStats(stats);drawHeat()},20)};setTimeout(drawHeat,50)}const t=setInterval(()=>{if(installed||boot())clearInterval(t)},250);setTimeout(()=>clearInterval(t),30000)})();</script>'''

s=INDEX.read_text(encoding='utf-8');start=s.find(MARK)
if start>=0:
    end=s.find('</body>',start);s=s[:start]+MARK+'\n'+CSS+'\n'+JS+'\n'+s[end:]
else:
    s=s.replace('</head>',CSS+'\n</head>',1);s=s.replace('</body>',MARK+'\n'+JS+'\n</body>',1)
INDEX.write_text(s,encoding='utf-8');print('Installed map v3: intensity, regional coverage, keyless basemap switcher, source photos, Google Maps links')
