/* Global Pulse Intelligence Web — stable evidence-first renderer. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),GRAPH='data/intelligence_graph.json',SNAP='data/snapshot.json';
const NODE_COLORS={actor:'#5da8ff',political:'#b58cff',economic:'#ffc857',strategic:'#48d9ff',military:'#ff5368',resource:'#39df88',oil:'#ff922e'};
const EDGE_COLORS={conflict:'#ff5368',military:'#ff5368',political:'#b58cff',economic:'#ffc857',strategic:'#48d9ff',security:'#48d9ff',resource:'#39df88',oil:'#ff922e',energy:'#ff922e',diplomatic:'#9b8cff',trade:'#ffc857',graph:'#5da8ff',general:'#5da8ff'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const href=v=>{try{let u=new URL(String(v||''),location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
const ends=e=>[String(e.source?.id??e.source??e.sid??''),String(e.target?.id??e.target??e.tid??'')];
function evidenceClean(a){return Array.isArray(a)?a.filter(x=>x&&((x.title&&String(x.title).trim())||href(x.url||x.link))).slice(0,12):[]}
function normalize(d){let g=d?.intelligenceGraph&&typeof d.intelligenceGraph==='object'?d.intelligenceGraph:null,r=g||d||{},nodes=(Array.isArray(r.nodes)?r.nodes:[]).map((n,i)=>({...n,id:String(n.id||'node-'+i),label:String(n.label||n.name||n.title||n.id||'Entity '+(i+1)),kind:String(n.kind||'actor'),mentions:Number(n.mentions)||0,evidence:evidenceClean(n.evidence)}));let valid=new Set(nodes.map(n=>n.id)),links=(Array.isArray(r.edges)?r.edges:[]).map(e=>{let [s,t]=ends(e),ev=evidenceClean(e.evidence);return{source:s,target:t,sid:s,tid:t,weight:Math.max(1,Number(e.weight)||1),types:Array.isArray(e.types)?e.types.map(String):[],relationship:String(e.relationship||'Both entities are referenced in the same public evidence record.'),evidence:ev,evidenceCount:ev.length}}).filter(e=>valid.has(e.source)&&valid.has(e.target)&&e.source!==e.target);return{nodes,links,updatedAt:r.updatedAt||d?.updatedAt||'',method:r.method||'Evidence-backed public reporting graph',caution:r.caution||''}}
function get(path){return fetch(path+'?v='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()})}
function edgeColor(e){let t=(e.types||[]).map(x=>String(x).toLowerCase());for(const k of ['conflict','military','political','economic','strategic','security','resource','oil','energy','diplomatic','trade','graph'])if(t.some(x=>x.includes(k)))return EDGE_COLORS[k];let r=String(e.relationship||'').toLowerCase();for(const k of ['conflict','military','political','economic','strategic','security','resource','oil','energy','diplomatic','trade'])if(r.includes(k))return EDGE_COLORS[k];return EDGE_COLORS.general}
async function load(){try{let g=normalize(await get(GRAPH));if(g.nodes.length)return g}catch{}return normalize(await get(SNAP))}
async function main(data){let base=data,active={nodes:[],links:[]},selected=null,dialog=false,filter='all',query='',controls=true,orbit=false,orbitFrame=0,paused=false;const peer=(e,id)=>{let[a,b]=ends(e);return a===String(id)?b:a};const related=n=>active.links.filter(e=>ends(e).includes(String(n.id)));
function styles(){let g=window.__gpGraph;if(!g)return;g.nodeColor(n=>selected?(n.id===selected.id?'#fff':related(selected).some(e=>peer(e,selected.id)===n.id)?NODE_COLORS[n.kind]||NODE_COLORS.actor:'#203542'):NODE_COLORS[n.kind]||NODE_COLORS.actor);g.linkColor(e=>selected&&ends(e).includes(String(selected.id))?'#fff':edgeColor(e));g.linkOpacity(e=>selected&&ends(e).includes(String(selected.id))?.98:.88);g.linkWidth(e=>Math.max(2.5,Math.min(10,2.5+Math.sqrt(Number(e.weight)||1))))}
function close(){dialog=false;selected=null;const d=$('details');if(d){d.classList.remove('open');d.style.display='none';d.style.pointerEvents='none';d.setAttribute('aria-hidden','true')}paused=false;try{window.__gpGraph.resumeAnimation();window.__gpGraph.d3ReheatSimulation()}catch{}styles()}
function card(e){let u=href(e.url||e.link);return'<article class="source-card"><div class="source-head"><b>'+esc(e.source||'Public source')+'</b>'+(e.time?'<em>'+esc(e.time)+'</em>':'')+'</div><strong>'+esc(e.title||'Public intelligence record')+'</strong>'+(e.summary?'<p>'+esc(e.summary)+'</p>':'')+(u?'<a href="'+esc(u)+'" target="_blank" rel="noopener noreferrer">OPEN ORIGINAL SOURCE ↗</a>':'<span class="no-link">Source URL unavailable</span>')+'</article>'}
function show(n){if(!n||dialog&&selected?.id===n.id)return;selected=n;dialog=true;paused=true;orbit=false;cancelAnimationFrame(orbitFrame);$('orbit')?.classList.remove('active');try{window.__gpGraph.pauseAnimation()}catch{}controls=false;$('controls').classList.add('collapsed');$('control-toggle').textContent='☰ OPEN FILTERS';$('control-toggle').setAttribute('aria-expanded','false');const d=$('details');d.style.display='block';d.style.pointerEvents='auto';d.setAttribute('aria-hidden','false');let con=related(n),by=new Map(active.nodes.map(x=>[x.id,x])),all=[],seen=new Set(),add=e=>{let k=href(e?.url||e?.link)||e?.title;if(e&&k&&!seen.has(k)){seen.add(k);all.push(e)}};n.evidence.forEach(add);con.forEach(e=>e.evidence.forEach(add));let h='<div class="title">'+esc(n.label)+'</div><div class="meta">NETWORK ENTITY · '+esc(n.kind.toUpperCase())+'</div><div class="chips"><span>'+con.length+' connections</span><span>'+Number(n.mentions||0)+' mentions</span><span>'+all.length+' evidence records</span></div><div class="method">'+esc(base.method)+'</div><div class="section"><b>WHY THIS NODE IS CONNECTED</b>';if(!con.length)h+='<p class="muted">No evidence-backed relationship is currently published for this node.</p>';else h+='<div class="evidence">'+con.slice(0,12).map(e=>{let id=peer(e,n.id),p=by.get(id),ev=e.evidence||[];return'<article class="relation"><div class="relation-title"><strong>'+esc(p?.label||id)+'</strong><span style="color:'+esc(edgeColor(e))+'">'+ev.length+' source records</span></div><div class="reason"><b>Connection basis:</b> '+esc(e.relationship)+'</div>'+(e.types?.length?'<div class="type-line">SIGNALS · '+esc(e.types.join(' · '))+'</div>':'')+(ev.length?ev.slice(0,4).map(card).join(''):'<div class="no-evidence">No source attached to this edge.</div>')+'</article>'}).join('')+'</div>';h+='</div><div class="section"><b>SOURCES FOR THIS NODE</b><div class="evidence">'+(all.length?all.slice(0,16).map(card).join(''):'<p class="muted">No directly attached source records.</p>')+'</div></div>';$('detail').innerHTML=h;$('details').classList.add('open');styles()}
function render(){let q=query.trim().toLowerCase(),matches=base.nodes.filter(n=>!q||n.label.toLowerCase().includes(q)||n.id.toLowerCase().includes(q)),focus=matches.filter(n=>filter==='all'||n.kind===filter),ids=new Set(focus.map(n=>n.id)),keep=new Set(ids);if(q||filter!=='all')base.links.forEach(e=>{let[a,b]=ends(e);if(ids.has(a))keep.add(b);if(ids.has(b))keep.add(a)});else base.nodes.forEach(n=>keep.add(n.id));active={nodes:base.nodes.filter(n=>keep.has(n.id)),links:base.links.filter(e=>{let[a,b]=ends(e);return keep.has(a)&&keep.has(b)})};close();window.__gpGraph.graphData(active);window.__gpGraph.d3ReheatSimulation();styles();$('stats').innerHTML='<b>'+focus.length+'</b> matching entities · <b>'+active.nodes.length+'</b> visible · <b>'+active.links.length+'</b> evidence-backed connections · updated '+esc(base.updatedAt||'unknown')}
let graphBuilder=new ForceGraph3D($('graph'),{controlType:'orbit',rendererConfig:{antialias:true,alpha:true,powerPreference:'high-performance'}}).backgroundColor('#03070b').showNavInfo(false).nodeId('id').nodeRelSize(5).nodeVal(n=>Math.max(5,Math.min(18,5+Math.sqrt(Math.max(1,n.mentions))*1.25))).nodeLabel(n=>'<b>'+esc(n.label)+'</b><br>'+esc(n.kind)+' · '+n.mentions+' mentions').nodeColor(n=>NODE_COLORS[n.kind]||NODE_COLORS.actor).linkColor(edgeColor).linkOpacity(.88).linkWidth(e=>Math.max(2.5,Math.min(10,2.5+Math.sqrt(Number(e.weight)||1)))).linkDirectionalParticles(()=>paused?0:2).linkDirectionalParticleSpeed(.012).enableNodeDrag(true).onNodeClick(show).onNodeHover(n=>{$('graph').style.cursor=n?'pointer':'grab'}).d3VelocityDecay(.65).d3AlphaDecay(.08).warmupTicks(80).cooldownTicks(120);window.__gpGraph=graphBuilder;
if(window.SpriteText){graphBuilder.nodeThreeObject(n=>{const s=new SpriteText(n.label);s.color=NODE_COLORS[n.kind]||NODE_COLORS.actor;s.textHeight=4.2;s.padding=2;s.backgroundColor='rgba(2,8,13,.82)';s.borderRadius=3;s.borderWidth=.35;s.borderColor=NODE_COLORS[n.kind]||NODE_COLORS.actor;s.material.depthWrite=false;return s}).nodeThreeObjectExtend(true)}
try{graphBuilder.d3Force('charge').strength(-420).distanceMax(1100);graphBuilder.d3Force('link').distance(e=>Math.max(95,180-(Number(e.weight)||1)*11))}catch{}
const details=$('details'),closeBtn=$('close');details.addEventListener('pointerdown',e=>e.stopPropagation(),true);details.addEventListener('click',e=>e.stopPropagation(),true);details.addEventListener('touchstart',e=>e.stopPropagation(),{capture:true,passive:false});closeBtn.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation()},{capture:true});closeBtn.addEventListener('pointerup',e=>{e.preventDefault();e.stopPropagation();close()},{capture:true});closeBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();close()},{capture:true});closeBtn.addEventListener('touchend',e=>{e.preventDefault();e.stopPropagation();close()},{capture:true});$('control-toggle').onclick=()=>{controls=!controls;$('controls').classList.toggle('collapsed',!controls);$('control-toggle').textContent=controls?'☰ CLOSE FILTERS':'☰ OPEN FILTERS';$('control-toggle').setAttribute('aria-expanded',String(controls))};$('clear').onclick=()=>{$('search').value='';query='';render()};$('refresh').onclick=()=>load().then(x=>{base=x;render()}).catch(()=>{});$('search').oninput=e=>{query=e.target.value;render()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.kind||'all';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});$('reset').onclick=()=>{filter='all';query='';$('search').value='';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.kind==='all'));render()};$('orbit').onclick=function(){orbit=!orbit;this.classList.toggle('active',orbit);cancelAnimationFrame(orbitFrame);if(orbit){let a=0;const go=()=>{if(!orbit)return;window.__gpGraph.cameraPosition({x:720*Math.sin(a),y:150,z:720*Math.cos(a)});a+=.0025;orbitFrame=requestAnimationFrame(go)};go()}};$('flow').onclick=function(){paused=!paused;this.classList.toggle('active',!paused);window.__gpGraph.linkDirectionalParticles(()=>paused?0:2)};document.querySelectorAll('.period').forEach(b=>b.onclick=()=>{$('trend').textContent='FILTER · '+b.dataset.period.toUpperCase()});render();$('details').style.pointerEvents='none';$('details').setAttribute('aria-hidden','true');$('loading').style.display='none';setInterval(()=>{if(!document.hidden&&!dialog)load().then(x=>{if(x.updatedAt!==base.updatedAt){base=x;render()}}).catch(()=>{})},60000)}
$('stats').textContent='Loading evidence graph…';load().then(main).catch(e=>{$('loading').innerHTML='<span class="error">INTELLIGENCE DATA UNAVAILABLE<br><small>'+esc(e.message)+'</small></span>'});
})();
