(()=>{'use strict';
const DATA='data/intelligence_brain.json';
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const ACTION_WORDS=/\b(announced|approved|imposed|sanctioned|deployed|struck|attacked|launched|intercepted|conducted|restricted|banned|tariff|tariffs|export control|exercise|drill|patrol|warship|missile|aircraft|troops|forces|diplomatic|negotiat|agreement|deal|meeting|visit|warning|threat|election|stimulus|regulation|investigation|arrested|seized|blocked|withdrew|recognized|signed|pledged)\b/i;
const TARGETS={
 'UNITED STATES':/\b(united states|u\.s\.?|usa|america|american|washington|pentagon|white house|state department)\b/i,
 'CHINA':/\b(china|chinese|beijing|pla|people.s liberation army)\b/i
};
function latest(e){return e?.time||e?.published_at||e?.publishedAt||e?.date||''}
function text(e){return[e?.title,e?.summary,e?.description,e?.source].filter(Boolean).join(' ')}
function score(e){let s=0,t=text(e);if(ACTION_WORDS.test(t))s+=5;if(latest(e))s+=2;if(e?.url)s+=1;if(/\b(taiwan|south china sea|russia|iran|nato|ukraine|trade|semiconductor|sanction|tariff|military|navy|technology)\b/i.test(t))s+=2;return s}
function collect(data){const out={};for(const key of Object.keys(TARGETS))out[key]=[];for(const n of Array.isArray(data.nodes)?data.nodes:[]){const body=[n.label,n.name,n.country,n.group,n.summary,n.description].filter(Boolean).join(' ');for(const key of Object.keys(TARGETS)){if(!TARGETS[key].test(body))continue;for(const e of Array.isArray(n.evidence)?n.evidence:[]){const t=text(e);if(ACTION_WORDS.test(t)||/\b(taiwan|south china sea|russia|iran|nato|ukraine|trade|semiconductor|sanction|tariff|military|navy|technology)\b/i.test(t))out[key].push({title:e.title||n.label,source:e.source||'Source',url:e.url||'',time:latest(e),summary:e.summary||n.summary||'',score:score(e)});}}}for(const key of Object.keys(out)){const seen=new Set();out[key]=out[key].filter(x=>{const k=(x.title+'|'+x.url).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>(b.score-a.score)||String(b.time).localeCompare(String(a.time))).slice(0,6)}return out}
function install(data){if(document.getElementById('aegis-action-panel'))return;const style=document.createElement('style');style.textContent=`#aegis-action-panel{position:fixed;left:14px;bottom:78px;z-index:80;width:min(620px,calc(100vw - 28px));background:rgba(2,8,13,.94);border:1px solid #193244;border-radius:14px;padding:11px;box-shadow:0 18px 60px #000;backdrop-filter:blur(16px);font:10px system-ui,sans-serif}#aegis-action-panel .ah{display:flex;justify-content:space-between;align-items:center;gap:8px;color:#39ff88;font-weight:950;letter-spacing:.12em}#aegis-action-panel .as{color:#8198aa;font-size:8px;margin-top:3px}#aegis-action-panel .cols{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}#aegis-action-panel .actor{border:1px solid #193244;border-radius:9px;padding:8px;min-width:0}#aegis-action-panel .actor h4{margin:0 0 5px;color:#eaf4ff;font-size:9px}#aegis-action-panel .item{border-top:1px solid #132733;padding:6px 0}.item:first-child{border-top:0}.item b{display:block;color:#dcecf5;font-size:8px;line-height:1.3}.item span{display:block;color:#8198aa;font-size:7px;margin-top:3px}.item a{color:#39ff88;text-decoration:none}.empty{color:#8198aa;font-size:8px;padding:6px 0}@media(max-width:700px){#aegis-action-panel{left:8px;bottom:55px;width:calc(100vw - 16px)}#aegis-action-panel .cols{grid-template-columns:1fr}}`;document.head.appendChild(style);const p=document.createElement('section');p.id='aegis-action-panel';const collected=collect(data);const render=(key,label)=>{const rows=collected[key];return `<div class="actor"><h4>${label} // ACTION SIGNALS</h4>${rows.length?rows.map(x=>`<div class="item"><b>${esc(x.title)}</b><span>${esc(x.source)}${x.time?' · '+esc(x.time):''}${x.url?` · <a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">EVIDENCE</a>`:''}</span></div>`).join(''):'<div class="empty">No recent action-classified evidence in the current Brain dataset.</div>'}</div>`};p.innerHTML=`<div class="ah"><span>STRATEGIC ACTION INTELLIGENCE</span><span>${collected['UNITED STATES'].length+collected.CHINA.length} SIGNALS</span></div><div class="as">Evidence-linked activity surfaced from the same Brain dataset. Presence is not proof of causation or intent.</div><div class="cols">${render('UNITED STATES','UNITED STATES')}${render('CHINA','CHINA')}</div>`;document.body.appendChild(p)}
fetch(DATA,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Brain data unavailable');return r.json()}).then(install).catch(()=>{});
})();