(()=>{'use strict';
const DATA='data/intelligence_brain.json';
const C={military:'#ff8a3d',economic:'#ffc857',diplomatic:'#39ff88',technology:'#8b7cff',security:'#5da8ff',political:'#d28cff',maritime:'#35d7c4',energy:'#ffcf66',default:'#8aa0b2'};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let actions=[],root,svg,raf=0;
function norm(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
function ensure(){if(root)return;root=document.createElement('div');root.id='gp-action-flow-layer';root.style.cssText='position:fixed;inset:0;z-index:7;pointer-events:none;overflow:hidden';svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.style.cssText='position:absolute;inset:0;width:100%;height:100%;overflow:visible';root.appendChild(svg);document.body.appendChild(root)}
function collect(d){actions=[];(d.nodes||[]).forEach(n=>(n.actions||[]).forEach(a=>{if(!a||!a.actor||!a.target||!a.action||!Array.isArray(a.evidence)||!a.evidence.length)return;actions.push({actor:n.label||a.actor,target:a.target,action:a.action,category:String(a.category||'security').toLowerCase(),importance:Number(a.importance||a.weight||1),evidence:a.evidence})}));}
function labelMap(){const m=new Map();document.querySelectorAll('.gp-label').forEach(e=>m.set(norm(e.textContent),e));return m}
function draw(){raf=0;ensure();while(svg.firstChild)svg.removeChild(svg.firstChild);const map=labelMap();let i=0;for(const a of actions){const s=map.get(norm(a.actor)),t=map.get(norm(a.target));if(!s||!t||s===t)continue;const sr=s.getBoundingClientRect(),tr=t.getBoundingClientRect(),x1=sr.left+sr.width/2,y1=sr.top+sr.height/2,x2=tr.left+tr.width/2,y2=tr.top+tr.height/2,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy);if(len<35)continue;const color=C[a.category]||C.default;const id='gpaf'+(++i);const defs=document.createElementNS('http://www.w3.org/2000/svg','defs'),mk=document.createElementNS('http://www.w3.org/2000/svg','marker');mk.id=id;mk.setAttribute('markerWidth','7');mk.setAttribute('markerHeight','7');mk.setAttribute('refX','6');mk.setAttribute('refY','3.5');mk.setAttribute('orient','auto');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M0,0 L7,3.5 L0,7 Z');path.setAttribute('fill',color);mk.appendChild(path);defs.appendChild(mk);svg.appendChild(defs);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',x1);line.setAttribute('y1',y1);line.setAttribute('x2',x2);line.setAttribute('y2',y2);line.setAttribute('stroke',color);line.setAttribute('stroke-width',String(Math.min(3,1+Math.log1p(a.importance))));line.setAttribute('stroke-opacity','.72');line.setAttribute('stroke-dasharray','6 7');line.setAttribute('marker-end',`url(#${id})`);svg.appendChild(line);const g=document.createElementNS('http://www.w3.org/2000/svg','g');const tx=x1+dx*.5,ty=y1+dy*.5;const bg=document.createElementNS('http://www.w3.org/2000/svg','rect');bg.setAttribute('x',tx-55);bg.setAttribute('y',ty-9);bg.setAttribute('width','110');bg.setAttribute('height','18');bg.setAttribute('rx','7');bg.setAttribute('fill','#02070c');bg.setAttribute('fill-opacity','.9');bg.setAttribute('stroke',color);bg.setAttribute('stroke-opacity','.45');const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',tx);text.setAttribute('y',ty+3);text.setAttribute('text-anchor','middle');text.setAttribute('fill','#eaf4ff');text.setAttribute('font-size','8');text.setAttribute('font-family','system-ui,sans-serif');text.setAttribute('font-weight','700');text.textContent=a.action.length>26?a.action.slice(0,25)+'…':a.action;g.appendChild(bg);g.appendChild(text);svg.appendChild(g)} }
function queue(){if(!raf)raf=requestAnimationFrame(draw)}
async function init(){try{const r=await fetch(DATA+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)return;collect(await r.json());queue();new MutationObserver(queue).observe(document.getElementById('graph')||document.body,{childList:true,subtree:true});addEventListener('resize',queue);setInterval(queue,500)}catch(e){console.warn('Action flow layer unavailable',e)}}
init();
})();
