/* Global Pulse Intelligence Web — stable mobile renderer + live source resolver. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),GRAPH='data/intelligence_graph.json',SNAP='data/snapshot.json',LIVE='data/live_articles.json';
const NODE_COLORS={actor:'#5da8ff',political:'#b58cff',economic:'#ffc857',strategic:'#48d9ff',military:'#ff5368',resource:'#39df88',oil:'#ff922e'};
const EDGE_COLORS={conflict:'#ff5368',military:'#ff5368',political:'#b58cff',economic:'#ffc857',strategic:'#48d9ff',security:'#48d9ff',resource:'#39df88',oil:'#ff922e',energy:'#ff922e',diplomatic:'#9b8cff',trade:'#ffc857',graph:'#5da8ff',general:'#5da8ff'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const href=v=>{try{const raw=String(v||'').trim();if(!/^https?:\/\//i.test(raw))return'';const u=new URL(raw);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
const normTitle=v=>String(v||'').toLowerCase().replace(/[‘’“”]/g,"'").replace(/[^a-z0-9]+/g,' ').trim();
const ends=e=>[String(e.source?.id??e.source??e.sid??''),String(e.target?.id??e.target??e.tid??'')];
const evidenceUrl=e=>href(e?.original_link)||href(e?.url)||href(e?.sourceUrl)||href(e?.source_url)||href(e?.link)||href(e?.credit?.source_url)||'';
const evidenceClean=a=>Array.isArray(a)?a.filter(x=>x&&((x.title&&String(x.title).trim())||evidenceUrl(x))).slice(0,12):[];
let liveByTitle=new Map(),liveBySourceTitle=new Map();
function indexLive(d){liveByTitle=new Map();liveBySourceTitle=new Map();const a=Array.isArray(d?.articles)?d.articles:[];for(const x of a){const u=evidenceUrl(x);const t=normTitle(x?.title);const s=normTitle(x?.source||x?.sourceLabel||x?.publisher);if(u&&t){if(!liveByTitle.has(t))liveByTitle.set(t,u);if(s)liveBySourceTitle.set(s+'|'+t,u)}}}
function resolveUrl(e){const direct=evidenceUrl(e);if(direct)return direct;const t=normTitle(e?.title),s=normTitle(e?.source);return liveBySourceTitle.get(s+'|'+t)||liveByTitle.get(t)||''}
function enrichEvidence(e){if(!e)return e;const u=resolveUrl(e);if(u&&!e.url)e.url=u;return e}
async function get(path){const r=await fetch(path+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function normalize(d){const g=d?.intelligenceGraph&&typeof d.intelligenceGraph==='object'?d.intelligenceGraph:null,r=g||d||{};const nodes=(Array.isArray(r.nodes)?r.nodes:[]).map((n,i)=>({...n,id:String(n.id||'node-'+i),label:String(n.label||n.name||n.title||n.id||'Entity '+(i+1)),kind:String(n.kind||'actor').toLowerCase(),mentions:Number(n.mentions)||0,evidence:evidenceClean(n.evidence).map(enrichEvidence)}));const valid=new Set(nodes.map(n=>n.id));const links=(Array.isArray(r.edges)?r.edges:[]).map(e=>{const[s,t]=ends(e);return{...e,source:s,target:t,sid:s,tid:t,weight:Math.max(1,Number(e.weight)||1),types:Array.isArray(e.types)?e.types.map(String):[],relationship:String(e.relationship||'Both entities are referenced in the same public evidence record.'),evidence:evidenceClean(e.evidence).map(enrichEvidence)}}).filter(e=>valid.has(e.source)&&valid.has(e.target)&&e.source!==e.target);return{nodes,links,updatedAt:r.updatedAt||d?.updatedAt||'',method:r.method||'Evidence-backed public reporting graph',caution:r.caution||''}}
async function load(){let live={};try{live=await get(LIVE);indexLive(live)}catch{indexLive({})}try{const g=normalize(await get(GRAPH));if(g.nodes.length)return g}catch{}return normalize(await get(SNAP))}
function edgeColor(e){const t=(e.types||[]).map(x=>String(x).toLowerCase()),r=String(e.relationship||'').toLowerCase();for(const k of ['conflict','military','political','economic','strategic','security','resource','oil','energy','diplomatic','trade'])if(t.some(x=>x.includes(k))||r.includes(k))return EDGE_COLORS[k];return EDGE_COLORS.general}
async function main(base){let active={nodes:[],links:[]},selected=null,dialog=false,filter='all',query='',controls=true,orbit=false,orbitFrame=0,paused=false,labelFrame=0;
const peer=(e,id)=>{const[a,b]=ends(e);return a===String(id)?b:a};const related=n=>active.links.filter(e=>ends(e).includes(String(n.id)));
function styles(){const g=window.__gpGraph;if(!g)return;g.nodeColor(n=>selected?(n.id===selected.id?'#ffffff':related(selected).some(e=>peer(e,selected.id)===n.id)?NODE_COLORS[n.kind]||NODE_COLORS.actor:'#263844'):NODE_COLORS[n.kind]||NODE_COLORS.actor);g.nodeVal(n=>selected?(n.id===selected.id?Math.max(16,Math.min(34,12+Math.sqrt(Math.max(1,n.mentions))*2.5)):Math.max(9,Math.min(25,9+Math.sqrt(Math.max(1,n.mentions))*1.7))):Math.max(12,Math.min(30,12+Math.sqrt(Math.max(1,n.mentions))*2)));g.linkColor(e=>selected&&ends(e).includes(String(selected.id))?'#ffffff':edgeColor(e));g.linkOpacity(e=>selected&&ends(e).includes(String(selected.id))?.98:.9);g.linkWidth(e=>Math.max(2.8,Math.min(11,2.8+Math.sqrt(Number(e.weight)||1))))}
function ensureLabel(n){const wrap=$('labels');if(!wrap)return null;const id=String(n.id);let el=wrap.querySelector('[data-node-label="'+CSS.escape(id)+'"]');if(!el){el=document.createElement('div');el.className='node-label';el.dataset.nodeLabel=id;el.innerHTML='<span class="dot"></span><span class="text"></span>';wrap.appendChild(el)}const c=NODE_COLORS[n.kind]||NODE_COLORS.actor;el.querySelector('.text').textContent=String(n.label||n.name||n.title||n.id||'Entity');el.querySelector('.dot').style.background=c;el.querySelector('.dot').style.boxShadow='0 0 8px '+c;el.style.borderColor=c;el.style.display='block';return el}
function syncLabels(){const wrap=$('labels'),g=window.__gpGraph;if(!wrap||!g||typeof g.graph2ScreenCoords!=='function')return;if(dialog){wrap.style.visibility='hidden';wrap.style.opacity='0';return}wrap.style.visibility='visible';wrap.style.opacity='1';const live=new Set();for(const n of active.nodes){const el=ensureLabel(n);if(!el)continue;const x=Number(n.x),y=Number(n.y),z=Number(n.z);if(!Number.isFinite(x)||!Number.isFinite(y)||!Number.isFinite(z)){el.style.visibility='hidden';continue}let p;try{p=g.graph2ScreenCoords(x,y,z)}catch{el.style.visibility='hidden';continue}if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y)){el.style.visibility='hidden';continue}live.add(String(n.id));el.style.left=Math.round(p.x)+'px';el.style.top=Math.round(p.y-28)+'px';el.style.visibility=(p.x>-250&&p.x<window.innerWidth+250&&p.y>-100&&p.y<window.innerHeight+100)?'visible':'hidden'}Array.from(wrap.children).forEach(el=>{if(!live.has(el.dataset.nodeLabel))el.style.display='none'})}
function startLabelLoop(){cancelAnimationFrame(labelFrame);const loop=()=>{syncLabels();labelFrame=requestAnimationFrame(loop)};loop()}
function close(){dialog=false;selected=null;const d=$('details');if(d){d.classList.remove('open');d.style.display='none';d.style.pointerEvents='none';d.setAttribute('aria-hidden','true')}const wrap=$('labels');if(wrap){wrap.style.visibility='visible';wrap.style.opacity='1'}paused=false;try{window.__gpGraph.resumeAnimation();window.__gpGraph.d3ReheatSimulation()}catch{}styles()}
function sourceCard(e){enrichEvidence(e);const u=resolveUrl(e);const title=String(e?.title||'Public intelligence record');return'<article class="source-card"><div class="source-head"><b>'+esc(e.source||'Public source')+'</b>'+(e.time?'<em>'+esc(e.time)+'</em>':'')+'</div><strong>'+esc(title)+'</strong>'+(e.summary?'<p>'+esc(e.summary)+'</p>':'')+(u?'<a class="source-link" href="'+esc(u)+'" target="_blank" rel="noopener noreferrer" referrerpolicy="no-referrer">OPEN ORIGINAL SOURCE ↗</a>':'<button class="source-link source-resolve" type="button" data-title="'+esc(title)+'" data-source="'+esc(e.source||'')+'">OPEN ORIGINAL SOURCE ↗</button>')+'</article>'}
function show(n){if(!n)return;if(dialog&&selected?.id===n.id)return;close();selected=n;dialog=true;paused=true;orbit=false;cancelAnimationFrame(orbitFrame);$('orbit')?.classList.remove('active');try{window.__gpGraph.pauseAnimation()}catch{}controls=false;$('controls').classList.add('collapsed');$('control-toggle').textContent='☰ OPEN FILTERS';$('control-toggle').setAttribute('aria-expanded','false');const wrap=$('labels');if(wrap){wrap.style.visibility='hidden';wrap.style.opacity='0'}const d=$('details');d.style.display='block';d.style.pointerEvents='auto';d.setAttribute('aria-hidden','false');const con=related(n),by=new Map(active.nodes.map(x=>[x.id,x])),all=[],seen=new Set();const add=e=>{enrichEvidence(e);const k=resolveUrl(e)||e?.title;if(e&&k&&!seen.has(k)){seen.add(k);all.push(e)}};n.evidence.forEach(add);con.forEach(e=>(e.evidence||[]).forEach(add));let h='<div class="title">'+esc(n.label)+'</div><div class="meta">NETWORK ENTITY · '+esc(n.kind.toUpperCase())+'</div><div class="chips"><span>'+con.length+' connections</span><span>'+Number(n.mentions||0)+' mentions</span><span>'+all.length+' evidence records</span></div><div class="method">'+esc(base.method)+'</div><div class="section"><b>WHY THIS NODE IS CONNECTED</b>';if(!con.length)h+='<p class="muted">No evidence-backed relationship is currently published for this node.</p>';else h+='<div class="evidence">'+con.slice(0,12).map(e=>{const id=peer(e,n.id),p=by.get(id),ev=e.evidence||[];return'<article class="relation" style="border-left:3px solid '+esc(edgeColor(e))+'"><div class="relation-title"><strong>'+esc(p?.label||id)+'</strong><span>'+ev.length+' source records</span></div><div class="reason"><b>Connection basis:</b> '+esc(e.relationship)+'</div>'+(e.types?.length?'<div class="type-line">SIGNALS · '+esc(e.types.join(' · '))+'</div>':'')+(ev.length?ev.slice(0,4).map(sourceCard).join(''):'<div class="no-evidence">No source attached to this edge.</div>')+'</article>'}).join('')+'</div>';h+='</div><div class="section"><b>SOURCES FOR THIS NODE</b><div class="evidence">'+(all.length?all.slice(0,16).map(sourceCard).join(''):'<p class="muted">No directly attached source records.</p>')+'</div></div>';$('detail').innerHTML=h;$('details').classList.add('open');styles()}
function render(){const q=query.trim().toLowerCase(),matches=base.nodes.filter(n=>!q||n.label.toLowerCase().includes(q)||n.id.toLowerCase().includes(q)),focus=matches.filter(n=>filter==='all'||n.kind===filter),ids=new Set(focus.map(n=>n.id)),keep=new Set(ids);if(q||filter!=='all')base.links.forEach(e=>{const[a,b]=ends(e);if(ids.has(a))keep.add(b);if(ids.has(b))keep.add(a)});else base.nodes.forEach(n=>keep.add(n.id));active={nodes:base.nodes.filter(n=>keep.has(n.id)),links:base.links.filter(e=>{const[a,b]=ends(e);return keep.has(a)&&keep.has(b)})};close();$('labels').innerHTML='';active.nodes.forEach(ensureLabel);window.__gpGraph.graphData(active);styles();setTimeout(()=>{try{window.__gpGraph.zoomToFit(700,90)}catch{}syncLabels()},450);$('stats').innerHTML='<b>'+focus.length+'</b> matching entities · <b>'+active.nodes.length+'</b> visible · <b>'+active.links.length+'</b> evidence-backed connections · updated '+esc(base.updatedAt||'unknown')}
const graphBuilder=new ForceGraph3D($('graph'),{controlType:'orbit',rendererConfig:{antialias:true,alpha:true,powerPreference:'high-performance'}}).backgroundColor('#03070b').showNavInfo(false).nodeId('id').nodeRelSize(6).nodeVal(n=>Math.max(12,Math.min(30,12+Math.sqrt(Math.max(1,n.mentions))*2))).nodeLabel(n=>'<b>'+esc(n.label)+'</b><br>'+esc(n.kind)+' · '+n.mentions+' mentions').nodeColor(n=>NODE_COLORS[n.kind]||NODE_COLORS.actor).linkColor(edgeColor).linkOpacity(.9).linkWidth(e=>Math.max(2.8,Math.min(11,2.8+Math.sqrt(Number(e.weight)||1)))).linkDirectionalParticles(()=>paused?0:2).linkDirectionalParticleSpeed(.012).enableNodeDrag(true).onNodeClick(show).d3VelocityDecay(.65).d3AlphaDecay(.08).warmupTicks(100).cooldownTicks(180);window.__gpGraph=graphBuilder;
try{graphBuilder.d3Force('charge').strength(-650).distanceMax(1500);graphBuilder.d3Force('link').distance(e=>Math.max(120,210-(Number(e.weight)||1)*10))}catch{}
const details=$('details'),closeBtn=$('close');details.addEventListener('pointerdown',e=>e.stopPropagation(),true);details.addEventListener('click',e=>e.stopPropagation(),true);details.addEventListener('touchstart',e=>e.stopPropagation(),{capture:true,passive:true});['pointerup','click','touchend'].forEach(type=>closeBtn.addEventListener(type,e=>{e.preventDefault();e.stopPropagation();close()},{capture:true}));details.addEventListener('click',e=>{const a=e.target.closest?.('.source-resolve');if(!a)return;e.preventDefault();e.stopPropagation();const t=normTitle(a.dataset.title),s=normTitle(a.dataset.source),u=liveBySourceTitle.get(s+'|'+t)||liveByTitle.get(t)||'';if(u)window.open(u,'_blank','noopener,noreferrer');else{a.textContent='SOURCE URL NOT AVAILABLE';a.disabled=true}},{capture:true});$('control-toggle').onclick=()=>{controls=!controls;$('controls').classList.toggle('collapsed',!controls);$('control-toggle').textContent=controls?'☰ CLOSE FILTERS':'☰ OPEN FILTERS';$('control-toggle').setAttribute('aria-expanded',String(controls))};$('clear').onclick=()=>{$('search').value='';query='';render()};$('refresh').onclick=()=>load().then(x=>{base=x;render()}).catch(()=>{});$('search').oninput=e=>{query=e.target.value;render()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.kind||'all';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});$('reset').onclick=()=>{filter='all';query='';$('search').value='';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.kind==='all'));render()};$('orbit').onclick=function(){orbit=!orbit;this.classList.toggle('active',orbit);cancelAnimationFrame(orbitFrame);if(orbit){let a=0;const go=()=>{if(!orbit||paused)return;window.__gpGraph.cameraPosition({x:720*Math.sin(a),y:150,z:720*Math.cos(a)},undefined,0);a+=.0025;orbitFrame=requestAnimationFrame(go)};go()}};$('flow').onclick=function(){paused=!paused;this.classList.toggle('active',!paused);window.__gpGraph.linkDirectionalParticles(()=>paused?0:2)};document.querySelectorAll('.period').forEach(b=>b.onclick=()=>{$('trend').textContent='FILTER · '+b.dataset.period.toUpperCase()});render();startLabelLoop();$('details').style.pointerEvents='none';$('details').setAttribute('aria-hidden','true');$('loading').style.display='none';setInterval(()=>{if(!document.hidden&&!dialog)load().then(x=>{if(x.updatedAt!==base.updatedAt){base=x;render()}}).catch(()=>{})},60000)}
$('stats').textContent='Loading evidence graph…';load().then(main).catch(e=>{$('loading').innerHTML='<span class="error">INTELLIGENCE DATA UNAVAILABLE<br><small>'+esc(e.message)+'</small></span>'});
})();