/** Breaking / Latest Reporting — newest evidence first, five visible with See more. */
import { getState } from '../core/state.js';
import { formatRelativeTime, escapeHtml } from '../core/utils.js';
import { CONFIDENCE_LABELS } from '../core/config.js';
export function renderBreaking(){
 const el=document.getElementById('breakingBody'),updatedEl=document.getElementById('breakingUpdated');if(!el)return;const{liveArticles,snapshot}=getState();let items=Array.isArray(liveArticles)?liveArticles:liveArticles?.articles||snapshot?.stories||snapshot?.liveArticles||[];if(!items.length){el.innerHTML='<div class="gp-state"><div class="gp-state-title">No recent reports</div><div>Live article feed is empty or unavailable. Check source health below.</div></div>';return;}
 items=[...items].sort((a,b)=>new Date(b.published||b.publishedAt||b.published_date||b.publishedDate||b.time||b.date||0)-new Date(a.published||a.publishedAt||a.published_date||a.publishedDate||a.time||a.date||0));
 if(updatedEl&&items[0])updatedEl.textContent=formatRelativeTime(items[0].published||items[0].publishedAt||items[0].published_date||items[0].publishedDate||items[0].time);
 const render=(item,i)=>{const title=item.title||item.headline||'Untitled',summary=item.summary||item.summary_snippet||item.description||item.snippet||'',source=item.sourceLabel||item.sourceName||item.source||item.publisher||'Unknown source',url=item.url||item.link||item.sourceUrl||'#',time=item.published||item.publishedAt||item.published_date||item.publishedDate||item.time||item.date,raw=(item.confidence||item.conf||'limited').toString().toLowerCase(),key=raw.includes('high')||raw==='confirmed'?'high':raw.includes('mod')||raw==='likely'?'moderate':raw.includes('unver')?'unverified':raw.includes('conflict')?'conflicting':'limited',conf=CONFIDENCE_LABELS[key]||CONFIDENCE_LABELS.limited,category=item.tag||item.category||item.topic||(item.breaking?'BREAKING':'');return `<article class="gp-news-item ${i>=5?'gp-extra-item':''}" ${i>=5?'hidden':''}><h3 class="gp-news-title"><a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(title)}</a></h3>${summary?`<p class="gp-news-summary">${escapeHtml(summary)}</p>`:''}<div class="gp-card-meta"><span class="gp-badge ${conf.class}">${conf.label}</span>${category?`<span class="gp-badge category">${escapeHtml(String(category))}</span>`:''}<span class="gp-source">${escapeHtml(source)}</span><span class="gp-time">${formatRelativeTime(time)}</span></div></article>`;};
 const shown=items.slice(0,50);el.innerHTML=`<div class="gp-news-list">${shown.map(render).join('')}</div>${shown.length>5?'<button id="breakingMore" class="gp-btn gp-more" type="button">Show more reporting</button>':''}`;const more=document.getElementById('breakingMore');more?.addEventListener('click',()=>{const hidden=el.querySelectorAll('.gp-extra-item[hidden]');hidden.forEach(x=>x.hidden=false);more.remove();});
}
