/** Active Conflict Watch — ranked real conflict signals, five visible with Show more. */
import { getState } from '../core/state.js';
import { formatRelativeTime, escapeHtml, scoreToLevel } from '../core/utils.js';
import { CONFIDENCE_LABELS } from '../core/config.js';
export function renderConflicts(){
 const el=document.getElementById('conflictsBody'),updatedEl=document.getElementById('conflictsUpdated');if(!el)return;const{snapshot}=getState();let conflicts=Array.isArray(snapshot?.conflicts)?snapshot.conflicts:snapshot?.conflictWatch||snapshot?.activeConflicts||snapshot?.cfrConflicts||[];if(!conflicts.length){el.innerHTML='<div class="gp-state"><div class="gp-state-title">No ranked conflict signals</div><div>Conflict layer is empty or not yet generated in the current snapshot.</div></div>';return;}
 conflicts=[...conflicts].sort((a,b)=>(b.activityScore??b.escalation??b.score??b.risk??0)-(a.activityScore??a.escalation??a.score??a.risk??0));if(updatedEl)updatedEl.textContent=formatRelativeTime(snapshot?.updatedAt);
 const render=(c,i)=>{const name=c.name||c.title||c.conflict||'Unnamed conflict',location=c.region||c.location||(Array.isArray(c.countries)?c.countries.join(', '):''),status=c.status||c.state||c.category||'Active monitoring',score=c.activityScore??c.escalation??c.score??c.risk??null,level=scoreToLevel(score),raw=(c.confidence||'limited').toString().toLowerCase(),key=raw.includes('high')?'high':raw.includes('mod')?'moderate':raw.includes('unver')?'unverified':'limited',conf=CONFIDENCE_LABELS[key]||CONFIDENCE_LABELS.limited,recent=c.recent||c.latest||c.summary||(c.facts&&c.facts[0])||'',analysis=c.analysis||'',signals=c.signalCount??c.signals?.length??null,sources=c.sourceCount??null;return `<div class="gp-card gp-conflict-card ${i>=5?'gp-extra-conflict':''}" ${i>=5?'hidden':''}><div class="gp-card-title">${escapeHtml(name)}</div>${location?`<div style="font-size:12px;color:var(--muted);margin-bottom:6px">${escapeHtml(location)}</div>`:''}<div class="gp-card-meta" style="margin-bottom:8px"><span class="gp-badge ${conf.class}">${conf.label}</span><span class="gp-badge category">${escapeHtml(status)}</span>${score!=null?`<span style="font-weight:700">${Math.round(score)}</span>`:''}</div>${score!=null?`<div class="gp-meter" style="margin-bottom:8px"><div class="gp-meter-bar"><div class="gp-meter-fill ${level}" style="width:${Math.min(100,Number(score))}%"></div></div></div>`:''}${recent?`<div style="font-size:12.5px;color:var(--text-secondary);margin-bottom:4px">${escapeHtml(String(recent).slice(0,220))}</div>`:''}${analysis?`<div style="font-size:11px;color:var(--muted);margin-top:4px"><strong>Analysis:</strong> ${escapeHtml(String(analysis).slice(0,160))}</div>`:''}<div style="font-size:11px;color:var(--muted-2);margin-top:6px">${signals!=null?`${signals} signals`:''} ${sources!=null?`· ${sources} sources`:''}</div></div>`;};
 const shown=conflicts.slice(0,50);el.innerHTML=`<div class="gp-grid gp-grid-2">${shown.map(render).join('')}</div>${shown.length>5?'<button id="conflictsMore" class="gp-btn gp-more" type="button">Show more conflicts</button>':''}<div style="margin-top:12px;font-size:11px;color:var(--muted-2)">Rankings are analytical signals derived from open data. They are not official designations.</div>`;const more=document.getElementById('conflictsMore');more?.addEventListener('click',()=>{el.querySelectorAll('.gp-extra-conflict[hidden]').forEach(x=>x.hidden=false);more.remove();});
}
